force-app/main/default/objects/Campaign/fields/CampaignID__c.field-meta.xml
<CustomField>
    <fullName>CampaignID__c</fullName>
    <description>this captures the unique integer field value associated with that campaign</description>
    <displayFormat>{0000}</displayFormat>
    <label>Campaign ID</label>
    <startingNumber>1000</startingNumber>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should be able to select a date only greater than or equal to today and the time.</description>
    <label>Date From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should not be allowed to select a date different from that entered in "Date From".</description>
    <label>Date To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/InfoMeetingID__c.field-meta.xml
<CustomField>
    <fullName>InfoMeetingID__c</fullName>
    <description>Its an autonumber field to link each campaign with a unique integer value</description>
    <displayFormat>{0000}</displayFormat>
    <label>Info Meeting ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingType__c.field-meta.xml
<CustomField>
    <fullName>MeetingType__c</fullName>
    <description>Type of meeting</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info Meeting - Offline</fullName>
            </value>
            <value>
                <fullName>Info Meeting - Online</fullName>
            </value>
            <value>
                <fullName>Open House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program of campaign</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <label>Campaign Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/CampaignName__c.field-meta.xml
<CustomField>
    <fullName>CampaignName__c</fullName>
    <label>Campaign Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CampaignQuestionsAnswer__c.field-meta.xml
<CustomField>
    <fullName>CampaignQuestionsAnswer__c</fullName>
    <label>Campaign Questions Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/InfoMeetingId__c.field-meta.xml
<CustomField>
    <fullName>InfoMeetingId__c</fullName>
    <label>InfoMeeting ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/EventsHelperTest.cls
@isTest
private class EventsHelperTest{
    @testSetup static void setup(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        system.runAs(tAdminUser) {
            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            String campaignQAndA = '{"CampaignQuestionAnswer":[{"ExtraQuestion":[{"Question":"SchoolName","Answer":"English Championship 2018"},{"Question":"code","Answer":"Quam dolores architecto harum duis neque officia sint dolorum fugiat"}]},{"Question":"Vocabulary Score","Answer":"18"},{"Question":"Vocabulary Percentage","Answer":"A1"},{"Question":"Reading Percentage","Answer":"A1"},{"Question":"Reading Score","Answer":"18"},{"Question":"Listening Percentage","Answer":"A1"},{"Question":"Listening Score","Answer":"18"},{"Question":"Proficiency Level","Answer":"A1"},{"Question":"Total Percentage","Answer":"18"},{"Question":"Total Score","Answer":"18"},{"Question":"Result Level","Answer":"beginner"},{"Question":"Time Taken","Answer":"00:01:28"}]}';
            leadBuilder.setField('CampaignQuestionsAnswer__c',campaignQAndA);
            Lead lead = (Lead)leadBuilder.save().getRecord();
            Event event = new Event();
            event.WhoId = lead.Id;
            event.DurationInMinutes = 30;
            event.ActivityDateTime = DateTime.now();
            event.CampaignName__c = 'Sample';
            event.Type = 'CAM';
            insert event;
        }
    }
  static @isTest void testUpdateSubjectOnEvents(){
      	User tAdminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
          Event event = [SELECT Id,Type,Program__c FROM Event WHERE Type = 'CAM' LIMIT 1];
          EventsHelper.updateSubjectOnEvents(new List<Event>{event});
        }
  }
  static @isTest void testCreateAttachmentForQuestionAnswers(){
      	User tAdminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
          Event event = [SELECT Id FROM Event WHERE Type = 'CAM' LIMIT 1];
          EventsHelper.createAttachmentForQuestionAnswers(new list<Event>{event});
        }
  }
  static @isTest void testAddLeadOrContactAsCampaignMember(){
      	User tAdminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Lead lead = [SELECT Id FROM Lead LIMIT 1];
            Map<String, String> campaignFields = new Map<String, String>{
                'DateFrom__c'=>String.valueOf(DateTime.now().addminutes(1)),
                'DateTo__c'=>String.valueOf(DateTime.now().addminutes(31)),
                'MeetingType__c'=>'ONM'
            };
                
            Campaign campaign = TestDataFactory.createCampaign('Test Campaign',campaignFields,true); 
            Campaign = [Select Id,CampaignID__c FROM Campaign];
            Event imEvent = new Event();
            imEvent.WhoId = lead.Id;
            imEvent.DurationInMinutes = 30;
            imEvent.ActivityDateTime = DateTime.now(); 
            imEvent.CampaignName__c = 'Sample';
            imEvent.InfoMeetingID__c = decimal.valueOf(campaign.CampaignID__c);
            imEvent.Type = 'IM';
            insert imEvent;
            
            EventsHelper.AddLeadOrContactAsCampaignMember(new list<Event>{imEvent});
        }
  }
}