force-app/main/default/objects/Campaign/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should be able to select a date only greater than or equal to today and the time.</description>
    <label>Date From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should not be allowed to select a date different from that entered in "Date From".</description>
    <label>Date To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingCity__c.field-meta.xml
<CustomField 
   >
    <fullName>MeetingCity__c</fullName>
    <description>Displays a list of cities in the market.</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A domicile</fullName>
            </value>
            <value>
                <fullName>Aachen</fullName>
            </value>
            <value>
                <fullName>Aalborg</fullName>
            </value>
            <value>
                <fullName>Aalst</fullName>
            </value>
            <value>
                <fullName>Aarau</fullName>
            </value>
            <value>
                <fullName>Abbotsford, BC</fullName>
            </value>
            <value>
                <fullName>Åbent hus</fullName>
            </value>
            <value>
                <fullName>Åbo</fullName>
            </value>
            <value>
                <fullName>Abrantes</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Acapulco</fullName>
            </value>
            <value>
                <fullName>Adana</fullName>
            </value>
            <value>
                <fullName>Adecco</fullName>
            </value>
            <value>
                <fullName>Admont</fullName>
            </value>
            <value>
                <fullName>Adrar</fullName>
                <label>Adrar </label>
            </value>
            <value>
                <fullName>Agen</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Agropoli</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Ahwaz</fullName>
            </value>
            <value>
                <fullName>Aïn Defla</fullName>
                <label>Aïn Defla </label>
            </value>
            <value>
                <fullName>Aïn Témouchent</fullName>
                <label>Aïn Témouchent </label>
            </value>
            <value>
                <fullName>Aix en Provence</fullName>
            </value>
            <value>
                <fullName>Aix-Marseille</fullName>
            </value>
            <value>
                <fullName>Ajaccio</fullName>
            </value>
            <value>
                <fullName>Aksay</fullName>
            </value>
            <value>
                <fullName>Aktau</fullName>
            </value>
            <value>
                <fullName>Aktobe</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Alajuela</fullName>
            </value>
            <value>
                <fullName>Berlin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingType__c.field-meta.xml
<CustomField>
    <fullName>MeetingType__c</fullName>
    <description>Type of meeting</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info Meeting - Offline</fullName>
            </value>
            <value>
                <fullName>Info Meeting - Online</fullName>
            </value>
            <value>
                <fullName>Open House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program of campaign</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/RecurrenceCampaignTest.cls
/**
 * Created by savita.b on 9/12/2017.
 */

@isTest
private class RecurrenceCampaignTest {

    static testmethod void getRecurrenceForCampaignTest() {
        Test.startTest();
        system.runAs(TestDataFactory.createAdminUser(true)) {

            Map<String,String> campaignValues = new Map<String,String>{

                    'Market__c'=>'DEB',
                    'Program__c'=>'AY',
                    'Salesoffice__c'=>'DEB',
                    'Status'=>'Active',
                    'MeetingType__c'=>'ONM',
                    'MeetingCity__c'=>'Berlin',
                    'DateFrom__c'=>String.valueOf(DateTime.now().addminutes(5)),
                    'DateTo__c'=>String.valueOf(DateTime.now().addminutes(20))
            };

            Campaign campaignRecord= TestDataFactory.createCampaign('test Campaign',campaignValues,TRUE);

            datetime date1 = date.Today();
            List<String> allDates=new List<String>();
            for(integer i=1;i<5;i++){
                DateTime date2 = date1.addDays(i);
                string myDate = date2.format('MM/dd/yyyy');
                allDates.add(myDate);
            }
            integer numberOfRecurrenceExpected = allDates.size();
            integer numberOfRecCreated = RecurrenceCampaignController.getRecurrenceDetails(allDates, campaignRecord.id);
            System.assertEquals(numberOfRecurrenceExpected, numberOfRecCreated);
        }
        Test.stopTest();
    }

    static testmethod void getRecurrenceForCampaignWithDupeTest() {
        Test.startTest();
        system.runAs(TestDataFactory.createAdminUser(true)) {
            Map<String,String> campaignValues = new Map<String,String>{

                    'Market__c'=>'DEB',
                    'Program__c'=>'AY',
                    'Salesoffice__c'=>'DEB',
                    'Status'=>'Active',
                    'MeetingType__c'=>'ONM',
                    'MeetingCity__c'=>'Berlin',
                    'DateFrom__c'=>String.valueOf(DateTime.now().addminutes(5)),
                    'DateTo__c'=>String.valueOf(DateTime.now().addminutes(20))
            };

            Campaign campaignRecord= TestDataFactory.createCampaign('test Campaign',campaignValues,TRUE);

            datetime date1 = date.Today();
            List<String> allDates = new List<String>();
            for(integer i = 0; i < 5; i++) {
                Datetime date2 = date1.addDays(i);
                string mydate = date2.format('MM/dd/yyyy');
                allDates.add(myDate);
            }
            integer numberOfRecurrenceExpected = allDates.size();
            integer numberOfRecCreated = RecurrenceCampaignController.getRecurrenceDetails(allDates, campaignRecord.id);
            System.assertEquals(numberOfRecurrenceExpected - 1, numberOfRecCreated );
        }
        Test.stopTest();
    }
}