force-app/main/default/objects/NoteMigration__c/NoteMigration__c.object-meta.xml
<CustomObject>
    <description>Object will help in content note migration from Poseidon database to Salesforce</description>
    <label>NoteMigration</label>
    <nameField>
        <displayFormat>NM-{000000}</displayFormat>
        <label>NoteMigration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NoteMigrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteMigration__c/fields/ContentNoteId__c.field-meta.xml
<CustomField>
    <fullName>ContentNoteId__c</fullName>
    <description>Salesforce Id of content note record created against this record</description>
    <inlineHelpText>Salesforce Id of content note record created against this record</inlineHelpText>
    <label>ContentNoteId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteMigration__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <description>Salesforce Id of event record where this record should associate as content note.</description>
    <inlineHelpText>Salesforce Id of event record where this record should associate as content note.</inlineHelpText>
    <label>EventId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/NoteMigration__c/fields/IsProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this record is processed for content note creation. false otherwise</description>
    <inlineHelpText>True if this record is processed for content note creation. false otherwise</inlineHelpText>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteMigration__c/fields/LastProcessedDate__c.field-meta.xml
<CustomField>
    <fullName>LastProcessedDate__c</fullName>
    <description>Timestamp when the record was last processed</description>
    <inlineHelpText>Timestamp when the record was last processed</inlineHelpText>
    <label>LastProcessedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NoteMigration__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <description>Salesforce Id of lead record where this record should associate as content note.</description>
    <inlineHelpText>Salesforce Id of lead record where this record should associate as content note.</inlineHelpText>
    <label>LeadId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteMigration__c/fields/NoteContent__c.field-meta.xml
<CustomField>
    <fullName>NoteContent__c</fullName>
    <description>Campaign questions and answers coming from Poseidon</description>
    <inlineHelpText>Campaign questions and answers coming from Poseidon</inlineHelpText>
    <label>NoteContent</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app++/main/default/objects/NoteMigration__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Holds campaign title, maps to content note title field</description>
    <inlineHelpText>Holds campaign title, maps to content note title field</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoteCreatorBatch.cls
//This batch creates ContentNote record based on NoteMigration records  
global class NoteCreatorBatch implements Database.Batchable<SObject>{
    
    //properties
    global String strQuery;   
           
    //constructor
    global NoteCreatorBatch(){
        this.strQuery  = ' Select Id, EventId__c, LeadId__c, Title__c, NoteContent__c from NoteMigration__c ' ;
        this.strQuery += ' where EventId__c != null and LeadId__c != null and Title__c != null and IsProcessed__c = false ';
        this.strQuery += ' order by CreatedDate ';  
        
        if(Test.isRunningTest()){
          this.strQuery += ' Limit 1';
        } 
    }
  
    //start method
    global Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator(strQuery); 
    }
  
    //execute method
    global void execute(Database.BatchableContext context, List<SObject> scope){ 
        /**
        1. Loop on note migration records
        2. Create a map, key - note migration record Id, value - content note record
        3. Insert map values
        4. Loop on note migration record
        5. Create content document link records for lead and event and add them to list
        6. Update note migration records
        7. Insert content document link records
        8. Update note migration records
        **/
        
        List<NoteMigration__c> lstNoteMigrations = new List<NoteMigration__c>();                
        List<ContentDocumentLink> lstContentDocumentLinksToInsert = new List<ContentDocumentLink>();
        
        Map<Id, ContentNote> mapNoteMigrationContentNote = new Map<Id, ContentNote>();
        
        try{            
            lstNoteMigrations = (List<NoteMigration__c>)scope;
            System.debug('*** List size: ' + lstNoteMigrations.size());
            
            //1. Loop on note migration records
            for(NoteMigration__c objNoteMigration : lstNoteMigrations){
                //2. Create a map, key - note migration record Id, value - content note record
                ContentNote noteRecord = new ContentNote();
                noteRecord.Title = objNoteMigration.Title__c;
                noteRecord.Content = Blob.valueOf(EventsHelper.getTheParsedJson(objNoteMigration.NoteContent__c));
                
                mapNoteMigrationContentNote.put(objNoteMigration.Id, noteRecord);                
            }                        
            
            //3. Insert map values
            if(mapNoteMigrationContentNote.size() > 0 && mapNoteMigrationContentNote.values().size() > 0){
                insert mapNoteMigrationContentNote.values();
            }            
            
            //4. Loop on note migration record
            for(NoteMigration__c objNoteMigration : lstNoteMigrations){
                //5. Create content document link records for lead and event and add them to list
                ContentDocumentLink linkRecordEvent = new ContentDocumentLink();
                linkRecordEvent.LinkedEntityId = objNoteMigration.EventId__c;
                linkRecordEvent.ContentDocumentId = mapNoteMigrationContentNote.get(objNoteMigration.Id).Id;                
                linkRecordEvent.ShareType = 'V';
                linkRecordEvent.Visibility = 'AllUsers';
                lstContentDocumentLinksToInsert.add(linkRecordEvent);
                
                ContentDocumentLink linkRecordLead = new ContentDocumentLink();
                linkRecordLead.LinkedEntityId = objNoteMigration.LeadId__c;
                linkRecordLead.ContentDocumentId = mapNoteMigrationContentNote.get(objNoteMigration.Id).Id;                
                linkRecordLead.ShareType = 'V';
                linkRecordLead.Visibility = 'AllUsers';
                
                lstContentDocumentLinksToInsert.add(linkRecordLead);
                
                //6. Update note migration records
                objNoteMigration.IsProcessed__c = true;
                objNoteMigration.LastProcessedDate__c = DateTime.now();
                objNoteMigration.ContentNoteId__c = mapNoteMigrationContentNote.get(objNoteMigration.Id).Id;
            }            
            
            //7. Insert content document link records
            if(lstContentDocumentLinksToInsert.size() > 0){
                insert lstContentDocumentLinksToInsert;
            } 
            
            //8. Update note migration records
            update lstNoteMigrations;                       
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'NoteCreatorBatch', 'excecute', null);            
        }
    }
   
    //finish method
    global void finish(Database.BatchableContext context){    
    }
}