force-app/main/default/objects/BypassTriggersValidation__c/BypassTriggersValidation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypassing triggers and validation rules for specific users/profiles</description>
    <label>Bypass Triggers Validation</label>
</CustomObject>

force-app++/main/default/objects/BypassTriggersValidation__c/fields/DisableTrigger__c.field-meta.xml
<CustomField>
    <fullName>DisableTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disabling Triggers</description>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BypassTriggersValidation__c/fields/TriggerObject__c.field-meta.xml
<CustomField>
    <fullName>TriggerObject__c</fullName>
    <description>Stores Trigger Objects like lead/Opportunity/Account/Task for which we need to bypass.</description>
    <label>Trigger Object</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UtilityTest.cls
@isTest
public class UtilityTest {
string splitstringvalue; 
   string splitchar;
boolean TrueOrFalse {get;set;}    
    @testSetup
    static void testDataSetup(){
        Profile SystemAdminProfile = TestDataFactory.getProfile('System Administrator', true);
        User tAdminUser = TestDataFactory.createAdminUser(True);
    } 
    
    static testMethod void getTriggerSettingsTest(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        system.runAs(tAdminUser) {
        Boolean isDisable = false;
        Test.startTest();
        BypassTriggersValidation__c setupUser = BypassTriggersValidation__c.getInstance();
        setupUser.DisableTrigger__c = null;
        setupUser.DisableTrigger__c = true;
        setupUser.TriggerObject__c = 'Account';
        Utility.getTriggerSettings('setupUser');
        Utility.splitString('splitstringvalue', 'splitchar');
        Datetime inputDatetime = Datetime.newInstance(1960, 2, 19);
        Utility.ConvertDateTimeTodate(inputDatetime);
        isDisable= true;
        
        
        
        Test.stopTest();
        } 
        
    }
    
}