force-app/main/default/objects/Apttus_Config2__AdjustmentLineItem__c/Apttus_Config2__AdjustmentLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents an adjustment to the price of a product/service</description>
    <label>Adjustment Line Item</label>
    <nameField>
        <displayFormat>AD-{0000000000}</displayFormat>
        <label>Adjustment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__AdjustmentLineItem__c/fields/APTS_Language__c.field-meta.xml
<CustomField>
    <fullName>APTS_Language__c</fullName>
    <description>Used to get translation from translations</description>
    <formula>Apttus_Config2__LineItemId__r.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APTS_Language__c</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__AdjustmentLineItem__c/fields/APTS_Market__c.field-meta.xml
<CustomField>
    <fullName>APTS_Market__c</fullName>
    <description>Used for translation</description>
    <formula>Apttus_Config2__LineItemId__r.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APTS_Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <description>This Object will store all the translation for different  values in Apttus</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Transalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdjustmentLineItemHelper.cls
/**
 * Created by arjun.mohan on 10/12/2017.
 */

public class AdjustmentLineItemHelper {

    public static void updateAdjustmentLineItemFieldsBeforeInsert(List<Apttus_Config2__AdjustmentLineItem__c> adjustmentLineItemNewList) {
        Id currentRecordId;
        try {
            String uniqueRecord = '';
            String[] defaultArrayString=Utility.splitString(Label.DefaultTranslation,'-');
            List<string> UniqueStrings = new List<string>();
            //List<String> productsList = new List<String>();
            for (Apttus_Config2__AdjustmentLineItem__c adjustmentLineItemRecord : adjustmentLineItemNewList) {
                UniqueStrings.add( adjustmentLineItemRecord.APTS_Market__c + ' ' +  adjustmentLineItemRecord.APTS_Language__c+' '+adjustmentLineItemRecord.Apttus_Config2__IncentiveId__r.Apttus_Config2__IncentiveCode__c);
                uniqueRecord=defaultArrayString[0]+' '+defaultArrayString[1]+ ' '+adjustmentLineItemRecord.Apttus_Config2__IncentiveId__r.Apttus_Config2__IncentiveCode__c;
                //if (!UniqueStrings.contains(uniqueRecord)) {
                    UniqueStrings.add(uniqueRecord);
                //}
                //UniqueStrings.add();
            }

            if (UniqueStrings.size()>0) {


                Map<string, Translation__C> translationsMap = TranslationsSelector.getTranslationRecodrDetailsForIncentive(UniqueStrings);

                for (Apttus_Config2__AdjustmentLineItem__c adjustmentLineItemRecord : adjustmentLineItemNewList) {
                    currentRecordId=adjustmentLineItemRecord.Id;
                    //Added If and else if coz we have "Misc as Picklist value for LineType" in Proposal Line item

                    uniqueRecord = adjustmentLineItemRecord.APTS_Market__c + ' ' +  adjustmentLineItemRecord.APTS_Language__c+' '+adjustmentLineItemRecord.Apttus_Config2__IncentiveId__r.Apttus_Config2__IncentiveCode__c;
                    if (!translationsMap.containsKey(uniqueRecord)) {
                        //String[] defaultArrayString=Utility.splitString(Label.DefaultTranslation,'-');
                        if (defaultArrayString.size()>0 && defaultArrayString.size()>1) {
                            uniqueRecord=defaultArrayString[0]+' '+defaultArrayString[1]+ ' '+adjustmentLineItemRecord.Apttus_Config2__IncentiveId__r.Apttus_Config2__IncentiveCode__c;
                        }
                    }
                    system.debug('==uniqueRecord=='+uniqueRecord);
                    system.debug('==translationsMap=='+translationsMap);
                    if (translationsMap.containsKey(uniqueRecord)) {
                        system.debug('==uniqueRecord11=='+translationsMap.containsKey(uniqueRecord));
                        for (Schema.FieldSetMember f : SObjectType.Translation__c.FieldSets.ProductTranslationfieldSet.getFields()) {
                            adjustmentLineItemRecord.put(f.getFieldPath(), translationsMap.get(uniqueRecord).get(f.getFieldPath()));
                        }
                    }
                }
            }
        } catch (Exception ex) {
            ExceptionHandler.errorLogAsync(ex.getMessage(), ex.getStackTraceString(),
                    'AdjustmentLineItemHelper', 'updateAdjustmentLineItemFieldsBeforeInsert', currentRecordId);
        }

    }
}