force-app++/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Used for Exception handling</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Used to store a short message.</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>Used to store ID of the record from where exception is generated</description>
    <label>Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Used to store method names</description>
    <label>MethodName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Used to trace stack.</description>
    <label>StackTrace</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ExceptionHandler.cls
public class ExceptionHandler{
    public static void errorLog(String errMessage, String trace, String className, String methodName, Id id) {
        List<ErrorLog__c> errorLogs = new List<ErrorLog__c>();
        ErrorLog__c err = new ErrorLog__c(
                Id__c = id,
                Name = className,
                MethodName__c = methodName,
                Description__c = errMessage,
                StackTrace__c = trace
        );
        errorLogs.add(err);
        SObjectUnitOfWork.createBulkErrorLog(errorLogs);
    }

    @future
    public static void errorLogAsync(String errMessage, String trace, String className, String methodName, Id id) {
        errorLog(errMessage, trace, className, methodName, id);
    }
}