force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Used to accept bookings data from Poseidon</description>
    <!-- <externalSharingModel>ControlledByParent</externalSharingModel> -->
    <label>Booking</label>
    <nameField>
        <label>Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field gives the account information of the related Booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/BookingDate__c.field-meta.xml
<CustomField>
    <fullName>BookingDate__c</fullName>
    <description>Used to display the date when booking is created</description>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/MainSalesResponsible__c.field-meta.xml
<CustomField>
    <fullName>MainSalesResponsible__c</fullName>
    <description>Used to display the name of the person creating the booking</description>
    <label>Main Sales Responsible</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Booking__c/fields/PosBookingNumber__c.field-meta.xml
<CustomField>
     <fullName>PosBookingNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id, represents booking number in Poseidon system</description>
        <externalId>true</externalId>
        <label>PosBookingNumber</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Used to display the product of the booking</description>
    <label>Product</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Used to display the Program of the booking</description>
    <label>Program</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Used to display the Sales Office to which the booking belongs.</description>
    <label>Sales Office</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to display the status of the booking</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BKN</fullName>
                <label>Booking</label>
            </value>
            <value>
                <fullName>CAX</fullName>
            </value>
            <value>
                <fullName>ERR</fullName>
                <label>Error</label>
            </value>  
            <value>
                <fullName>PRE</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>STP</fullName>
                <label>Sent To Poseidon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingsSelector.cls
/**************************************************************************************
Apex Class Name    : BookingsSelector
Version            : 1.0
Created Date       : May 23 2018
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Arjun.Mohan                 23/05/2018              Original Version
*******************************************************************************/
public class BookingsSelector {

    public static Map<Id,List<Booking__c>> getBookingForAccountIds(Set<Id> AccountId)
    {
        Map<Id,List<Booking__c>> accountWithBookingMap = new Map<Id,List<Booking__c>>();
       List<Booking__c> bookingList=[SELECT Id, Name, CurrencyIsoCode, AccountId__c, BookingDate__c, Product__c, Program__c, SalesOffice__c, PosBookingNumber__c, Status__c, MainSalesResponsible__c FROM Booking__c where Status__c != 'CAX' and AccountId__c IN :AccountId];
        for(Booking__c bookingRec:bookingList)
        {
            if(!accountWithBookingMap.containsKey(bookingRec.AccountId__c))
            {
                accountWithBookingMap.put(bookingRec.AccountId__c, new List<Booking__c>());
            }
            List<Booking__c> temp=accountWithBookingMap.get(bookingRec.AccountId__c);
            temp.add(bookingRec);
            accountWithBookingMap.put(bookingRec.AccountId__c, temp);
        }
        return accountWithBookingMap;
    }
}