force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Used to accept bookings data from Poseidon</description>
    <!-- <externalSharingModel>ControlledByParent</externalSharingModel> -->
    <label>Booking</label>
    <nameField>
        <label>Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalServiceSettings__mdt/ExternalServiceSettings__mdt.object-meta.xml
<CustomObject>
    <description>Here we store all the external services details
Ex:End Point details,Env,Target System....</description>
    <label>ExternalServiceSetting</label>
    <pluralLabel>ExternalServiceSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExternalServiceSettings__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>All the End Points to different Environment's mentioned in this field</description>
    <label>EndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ShowBookingController.cls
public class ShowBookingController { 
    public String displayMessage{get;set;}
    public String BookingNumber{get;set;}
    public Booking__c BookingObject{get;set;}
    public String ServiceURL{get;set;}

    public ShowBookingController(ApexPages.StandardController controller) {
    this.displayMessage=system.label.ShowBookingDisplayMessage;
        if (controller.getRecord().getSObjectType()==Booking__c.getSObjectType()) {
            this.BookingObject = (Booking__c)controller.getRecord();
            BookingObject =  [SELECT ID,Name FROM Booking__c WHERE ID = :BookingObject.Id];
            BookingNumber=this.BookingObject.Name;
            ExternalServiceSettings__mdt serviceSettingRecord = ExternalRouter.getServiceURL('OpenBooking');
            if(serviceSettingRecord!=null && !String.IsEmpty(serviceSettingRecord.EndPoint__c))
            {
                this.ServiceURL = serviceSettingRecord.EndPoint__c;
            }
        }
        else
        {
            BookingNumber=null;
        }
    }
}