force-app/main/default/objects/LTCourseProgram__c/LTCourseProgram__c.object-meta.xml
<CustomObject>
    <label>LT Course Program</label>
    <nameField>
        <label>LT Course Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LT Course Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LTCourseProgram__c/fields/Apttus_Config2_ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2_ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to match LT course with our SalesForce Product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>LT Course Programs</relationshipLabel>
    <relationshipName>LT_Course_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LTCourseProgram__c/fields/BrochureSeason__c.field-meta.xml
<CustomField>
    <fullName>BrochureSeason__c</fullName>
    <description>This field is used to select Brochure with respect to the course season</description>
    <label>Brochure Season</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LTCourseProgram__c/fields/CourseStatus__c.field-meta.xml
<CustomField>
    <fullName>CourseStatus__c</fullName>
    <description>used for status of the LT</description>
    <label>Course Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LTCourseProgram__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Used for specifying the market</description>
    <label>Market</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LTCourseProgram__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Used for displaying in which year course is taking place</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LTCourseProgramsSelector.cls
/**
* Created by arjun.mohan on 1/23/2018.
*/

public  class LTCourseProgramsSelector {

    Public static Map<Id,LTCourseProgram__c> getLTCoursePrograms(String market,String year,String brochureSeason,String currencycode)
    {
        system.debug('market' +market);
        system.debug('Year__c' +year);
        system.debug('brochureSeason' +brochureSeason);
        system.debug('CurrencyIsoCode' +currencycode);
        Map<Id,LTCourseProgram__c> LtProgramMap=new Map<Id,LTCourseProgram__c>();
        String status='Active';
        List<LTCourseProgram__c> LTCourseProgramsList=new List<LTCourseProgram__c>();
        if (String.isNotBlank(market) && String.isNotBlank(year)  && String.isNotBlank(brochureSeason) && String.isNotBlank(currencycode)) {
            String query = 'SELECT ';
            for (Schema.FieldSetMember f : SObjectType.LTCourseProgram__c.FieldSets.LTCourseProgramFieldSet.getFields()) {
                query += f.getFieldPath() + ', ';
            }
            query += 'Id,Name,Apttus_Config2_ProductId__c from LTCourseProgram__c  ' ;
            query +=     ' where Market__c = : ' + 'market' + ' and  Year__c = : ' + 'year' + ' and BrochureSeason__c = : ' + ' brochureSeason' +  '  and  CurrencyIsoCode = : ' + 'currencycode' + ' and CourseStatus__c = : ' + 'status' + ' ' ;
            system.debug('query' +query);
            LTCourseProgramsList=Database.query(query);
            for (LTCourseProgram__c LtRecord:LTCourseProgramsList) {
                LtProgramMap.put(LtRecord.Id,LtRecord);

            }
            system.debug('LtProgramMap' +LtProgramMap);
        }
        return LtProgramMap;
    }

}