force-app/main/default/objects/Account/fields/AccountExternalId__c.field-meta.xml
<CustomField>
    <fullName>AccountExternalId__c</fullName>
    <description>This will store unique customer_id from Poseidon during Migration.</description>
    <externalId>true</externalId>
    <label>AccountExternalId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsSyncedToPoseidon__c.field-meta.xml
<CustomField>
    <fullName>IsSyncedToPoseidon__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by Integration to mark the check box while updating unique customer ID.</description>
    <label>Is Synced To Poseidon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PoseidonSyncStatus__c.field-meta.xml
<CustomField>
    <fullName>PoseidonSyncStatus__c</fullName>
    <description>Stores Sync status used to determine if record needs to be save to Poseidon</description>
    <label>Poseidon Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Todo</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TotalBooking__c.field-meta.xml
<CustomField>
    <fullName>TotalBooking__c</fullName>
    <description>This is used to know how many bookings we have under this account</description>
    <label>TotalBooking</label>
    <summaryForeignKey>Booking__c.AccountId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PoseidonAccountSyncBatch.cls
/**
 * Created by Arkadiusz Celej on 23.03.2018.
 */

public class PoseidonAccountSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, System.Schedulable{

    public static final String SCHEDULED_JOB_NAME = 'Poseidon Account Sync Batch';
    public static Boolean SYNC_IN_PROGRESS = false;

    public List<Account> start(Database.BatchableContext BC){
        return findRecords();
    }

    public void execute(Database.BatchableContext BC, List<Account> scope){
        SYNC_IN_PROGRESS = true;
        try {
            AccountsHelper.SyncAccountDetailsWrapper accountDetailsWrapper = AccountsHelper.retrieveDataToSync(new Map<Id, Account>(scope), null);
            if(accountDetailsWrapper != NULL) {
                ExternalRouter.updateAccountDetails(JSON.serialize(accountDetailsWrapper));
            }
        }catch (Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'PoseidonAccountSyncBatch', 'execute', null);
        }
        SYNC_IN_PROGRESS = false;
    }

    public void finish(Database.BatchableContext BC){}

    public void execute(SchedulableContext ctx){
        Database.executeBatch(new PoseidonAccountSyncBatch());
    }

    private List<Account> findRecords(){
        Set<String> toSyncStatuses = new Set<String>{PoseidonSyncService.SyncStatusTodo, PoseidonSyncService.SyncStatusFail};
        Set<String> fieldsToSelect=new Set<String>();

        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.UpdatePersonalInfo.getFields()) {
            fieldsToSelect.add(f.getFieldPath());
        }
        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.Address.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
            }

        }

        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.Customer.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
            }
        }
        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.CustomerMarketingPref.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
            }
        }
        fieldsToSelect.addAll('Name,Id,Market__c,CreatedById,LastModifiedById,Firstname,lastname,ParentEmail__c,Middlename,PersonMailingCity,PersonMailingPostalCode,PersonMailingCountryCode,PersonMailingState,ShippingCity,ShippingState,ShippingStreet,PersonOtherPostalCode,TotalBooking__c'.split(','));

        String query = 'SELECT '+String.join(new List<String>(fieldsToSelect), ',')+' FROM Account WHERE (TotalBooking__c > 0 OR (AccountExternalId__c <> null AND IsSyncedToPoseidon__c = TRUE)) AND PoseidonSyncStatus__c IN :toSyncStatuses';

        return Database.query(query);
    }

    public static void scheduleEvery30mins(){
        String appendix = Test.isRunningTest()? '_test' : '';
        PoseidonAccountSyncBatch.schedule('0 0 * ? * *', SCHEDULED_JOB_NAME+' - 00 minute of hour'+appendix);
        PoseidonAccountSyncBatch.schedule('0 33 * ? * *', SCHEDULED_JOB_NAME+' - 30 minute of hour'+appendix);
    }

    public static void schedule(String crone, String label){
        System.schedule(label, crone, new PoseidonAccountSyncBatch());
    }
}