force-app/main/default/objects/Account/fields/AccountExternalId__c.field-meta.xml
<CustomField>
    <fullName>AccountExternalId__c</fullName>
    <description>This will store unique customer_id from Poseidon during Migration.</description>
    <externalId>true</externalId>
    <label>AccountExternalId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsSyncedToPoseidon__c.field-meta.xml
<CustomField>
    <fullName>IsSyncedToPoseidon__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by Integration to mark the check box while updating unique customer ID.</description>
    <label>Is Synced To Poseidon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PoseidonSyncStatus__c.field-meta.xml
<CustomField>
    <fullName>PoseidonSyncStatus__c</fullName>
    <description>Stores Sync status used to determine if record needs to be save to Poseidon</description>
    <label>Poseidon Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Todo</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BypassTriggersValidation__c/BypassTriggersValidation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypassing triggers and validation rules for specific users/profiles</description>
    <label>Bypass Triggers Validation</label>
</CustomObject>

force-app++/main/default/objects/BypassTriggersValidation__c/fields/DisableTrigger__c.field-meta.xml
<CustomField>
    <fullName>DisableTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disabling Triggers</description>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BypassTriggersValidation__c/fields/DisableValidation__c.field-meta.xml
<CustomField>
    <fullName>DisableValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disabling Validation rules</description>
    <label>Disable Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BypassTriggersValidation__c/fields/TriggerObject__c.field-meta.xml
<CustomField>
    <fullName>TriggerObject__c</fullName>
    <description>Stores Trigger Objects like lead/Opportunity/Account/Task for which we need to bypass.</description>
    <label>Trigger Object</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PoseidonAccountSyncBatchTest.cls
/**
 * Created by Arkadiusz Celej on 26.03.2018.
 */

@IsTest
private class PoseidonAccountSyncBatchTest {

    @testSetup
    static void setupData(){
        User adminUser = TestDataFactory.createAdminUser(true);
        System.runAs(adminUser) {

            BypassTriggersValidation__c bpv = new BypassTriggersValidation__c();
            bpv.DisableTrigger__c = true;
            bpv.DisableValidation__c = true;
            bpv.SetupOwnerId = adminUser.Id;
            bpv.TriggerObject__c = SObjectType.Account.Name;

            insert bpv;

            TestDataFactory.OpportunityBuilder ob = new TestDataFactory.OpportunityBuilder();
            for(Integer i = 0; i < 10 ; i++){
                ob.withPersonAccount();
                Account acc = ob.getAccount();
                acc.PoseidonSyncStatus__c = PoseidonSyncService.SyncStatusTodo;
                acc.AccountExternalId__c = i;
                acc.PersonMailingCity = 'Test City';
                acc.IsSyncedToPoseidon__c = true;
                ob.withBooking();
                ob.save();
            }
        }

    }

    @isTest
    static void shouldScheduleBatchEvery30Mins() {
        Test.startTest();
        PoseidonAccountSyncBatch.scheduleEvery30mins();
        Test.stopTest();

        List<CronTrigger> ctList = [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE :PoseidonAccountSyncBatch.SCHEDULED_JOB_NAME+'%_test'];
        System.assertEquals(2, ctList.size());
        System.assert(ctList[0].CronJobDetail.Name.startsWith(PoseidonAccountSyncBatch.SCHEDULED_JOB_NAME));
        System.assert(ctList[1].CronJobDetail.Name.startsWith(PoseidonAccountSyncBatch.SCHEDULED_JOB_NAME));
    }

    @isTest
    static void shouldSyncAccountsWithPoseidonSyncStatusTodo(){
        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {
            //given
            //when
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new CalloutHandlerMocks.SuccessCalloutMock());
            PoseidonAccountSyncBatch psb = new PoseidonAccountSyncBatch();
            List<Account> scope = psb.start(null);
            psb.execute(null, scope);
            Test.stopTest();
            //then
            for(Account acc : [SELECT Id, PoseidonSyncStatus__c FROM Account]){
                System.assertEquals(PoseidonSyncService.SyncStatusSuccess, acc.PoseidonSyncStatus__c, 'Incorrect status');
            }
        }
    }

    @isTest
    static void onFailedCalloutShouldUpdateAccountsSyncStatusToFail(){
        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {
            //given
            //when
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new CalloutHandlerMocks.FailureCalloutMock());
            PoseidonAccountSyncBatch psb = new PoseidonAccountSyncBatch();
            List<Account> scope = psb.start(null);
            psb.execute(null, scope);
            Test.stopTest();
            //then
            for(Account acc : [SELECT Id, PoseidonSyncStatus__c FROM Account]){
                System.assertEquals(PoseidonSyncService.SyncStatusFail, acc.PoseidonSyncStatus__c, 'Incorrect status');
            }
        }
    }

    @isTest
    static void onInvalidCalloutShouldUpdateAccountsSyncStatusToFail(){
        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {
            //given
            //when
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new CalloutHandlerMocks.InvalidCalloutMock());
            PoseidonAccountSyncBatch psb = new PoseidonAccountSyncBatch();
            List<Account> scope = psb.start(null);
            psb.execute(null, scope);
            Test.stopTest();
            //then
            for(Account acc : [SELECT Id, PoseidonSyncStatus__c FROM Account]){
                System.assertEquals(PoseidonSyncService.SyncStatusFail, acc.PoseidonSyncStatus__c, 'Incorrect status');
            }
        }
    }
}