force-app/main/default/objects/Account/fields/ActiveOpportunities__c.field-meta.xml
<CustomField>
    <fullName>ActiveOpportunities__c</fullName>
    <description>This field counts the number of related Active opportunities.</description>
    <label>ActiveOpportunities</label>
    <summaryFilterItems>
        <field>Opportunity.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Closed Lost, Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HasHappyCallTask__c.field-meta.xml
<CustomField>
    <fullName>HasHappyCallTask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Happy Call Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LatestBooking__c.field-meta.xml
<CustomField>
    <fullName>LatestBooking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Latest Booking that is now in the past</description>
    <label>Latest Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MaxActiveBookingEndDate__c.field-meta.xml
<CustomField>
    <fullName>MaxActiveBookingEndDate__c</fullName>
    <description>The maximum end date of all Active Bookings related to this Account.</description>
    <label>Max Active Booking End Date</label>
    <summarizedField>Booking__c.MaxEndDate__c</summarizedField>
    <summaryFilterItems>
        <field>Booking__c.Status__c</field>
        <operation>equals</operation>
        <value>Booking, Pre Application</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.AccountId__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/ReadyForHappyCall__c.field-meta.xml
<CustomField>
    <fullName>ReadyForHappyCall__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate that we need to make a happy call with this Account</description>
    <label>Ready for Happy Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Used to accept bookings data from Poseidon</description>
    <!-- <externalSharingModel>ControlledByParent</externalSharingModel> -->
    <label>Booking</label>
    <nameField>
        <label>Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field gives the account information of the related Booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/MainSalesResponsible__c.field-meta.xml
<CustomField>
    <fullName>MainSalesResponsible__c</fullName>
    <description>Used to display the name of the person creating the booking</description>
    <label>Main Sales Responsible</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/MaxEndDate__c.field-meta.xml
<CustomField>
    <fullName>MaxEndDate__c</fullName>
    <description>Used to display the  maximum end date of all active courses in the booking</description>
    <label>Max End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Used to display the Program of the booking</description>
    <label>Program</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HCCTaskCreatorBatch.cls
/**************************************************************************************
Apex Class Name    : HCCTaskCreatorBatch
Version            : 1.0
Created Date       : March 26 2018
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Osiecki A                  26/03/2018              Original Version
*******************************************************************************/

public without sharing class HCCTaskCreatorBatch implements Database.Batchable<SObject>, Schedulable{

    public Id SystemCallTaskRecordTypeId =
            RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;
    public Integer numberOfDays = Integer.valueOf(Label.HCCTaskCreatorBatchNoOfDaysParameter);

    public Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator(
                'SELECT Id, MaxActiveBookingEndDate__c, (SELECT MainSalesResponsible__c, MaxEndDate__c, Program__c  FROM Bookings__r' +
                        ' WHERE MaxEndDate__c < TODAY AND MaxEndDate__c = LAST_N_DAYS:' + numberOfDays + ') '+
                        'FROM Account ' +
                        'WHERE MaxActiveBookingEndDate__c < TODAY' +
                        ' AND MaxActiveBookingEndDate__c = LAST_N_DAYS:' + numberOfDays +
                        ' AND ActiveOpportunities__c = 0' +
                        ' AND HasHappyCallTask__c = FALSE'
        );
    }

    public void execute(Database.BatchableContext context,List<Account> scope){

        List<Task> tasks = new List<Task>();
        Booking__c booking = new Booking__c();
        List<Account> accounts = new List<Account>();
        Account acc = new Account();

        for(Account account : scope){
            account.HasHappyCallTask__c = TRUE;
            account.ReadyForHappyCall__c = TRUE;
            accounts.add(account);
            booking = account.Bookings__r[0];
            account.LatestBooking__c = booking.Id;
            Task task = new Task(
                    RecordTypeId = SystemCallTaskRecordTypeId,
                    WhatId = account.Id,
                    NextCallType__c = Label.HCC_Next_Call_Type,
                    Type = Label.HCC_Task_Type,
                    ActivityDate = account.MaxActiveBookingEndDate__c + 1,
                    FollowUpDate__c = account.MaxActiveBookingEndDate__c + 1,
                    Status = Label.Not_Started,
                    Subject = Label.Happy_Call + ' ' + booking.Program__c,
                    OwnerId = booking.MainSalesResponsible__c,
                    Program__c = booking.Program__c
            );
            tasks.add(task);
        }
        try{
            insert tasks;
            update accounts;
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'HCCTaskCreatorBatch', 'execute', null);
        }
    }
    public void finish(Database.BatchableContext bc){
    }

    //Scheduling method
    public void execute(SchedulableContext sc){
        HCCTaskCreatorBatch tcb = new HCCTaskCreatorBatch();
        Database.executeBatch(tcb);
    }
}