force-app/main/default/objects/Account/fields/ActiveOpportunities__c.field-meta.xml
<CustomField>
    <fullName>ActiveOpportunities__c</fullName>
    <description>This field counts the number of related Active opportunities.</description>
    <label>ActiveOpportunities</label>
    <summaryFilterItems>
        <field>Opportunity.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Closed Lost, Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HasHappyCallTask__c.field-meta.xml
<CustomField>
    <fullName>HasHappyCallTask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Happy Call Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HCCTaskDeferrerBatch.cls
/**************************************************************************************
Apex Class Name    : HCCTaskDeferrerBatch
Version            : 1.0
Created Date       : April 11 2018
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Osiecki A                  11/04/2018              Original Version
*******************************************************************************/

public without sharing class HCCTaskDeferrerBatch implements Database.Batchable<SObject>, Schedulable{

    public Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator(
                'SELECT Id, Status, Account.HasHappyCallTask__c '+
                        'FROM Task ' +
                        'WHERE (Status != \'Deferred\' OR Status = \'Completed\')' +
                        ' AND Account.HasHappyCallTask__c = TRUE' +
                        ' AND Account.ActiveOpportunities__c > 0'
        );
    }

    public void execute(Database.BatchableContext context,List<Task> scope){

        List<Task> tasks = new List<Task>();
        for(Task task : scope){
            task.Status = Label.Task_Status_Deferred;
            tasks.add(task);
        }
        try{
            update tasks;
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'HCCTaskDeferrerBatch', 'execute', null);
        }
    }

    public void finish(Database.BatchableContext bc){
    }

    //Scheduling method
    public void execute(SchedulableContext sc){
        HCCTaskDeferrerBatch tdb = new HCCTaskDeferrerBatch();
        Database.executeBatch(tdb);
    }
}