force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Person Account Age</description>
    <formula>FLOOR((TODAY() -  PersonContact.Birthdate  )/365.2425)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BirthCountry__c.field-meta.xml
<CustomField>
    <fullName>BirthCountry__c</fullName>
    <description>This field is created to select the country of birth</description>
    <label>Country Of Birth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstNameEn__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEn__c</fullName>
    <description>This field will show the English translation of First Name.</description>
    <label>First Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceEmail__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmail__c</fullName>
    <description>This field is used to store the email-address to which invoices should be send.</description>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastNameEn__c.field-meta.xml
<CustomField>
    <fullName>LastNameEn__c</fullName>
    <description>This field will show the English translation of Last Name.</description>
    <label>Last Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OtherNationalities__c.field-meta.xml
<CustomField>
    <fullName>OtherNationalities__c</fullName>
    <description>It contains nationality of the customers.</description>
    <label>Other Nationalities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>PassportExpiryDate__c</fullName>
    <description>Option to enter the passport expiry date. This field would be a calendar control.</description>
    <label>Passport Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportIssueDate__c.field-meta.xml
<CustomField>
    <fullName>PassportIssueDate__c</fullName>
    <description>Option to enter the passport issue date. This field would be a calendar control.</description>
    <label>Passport Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <description>Option to enter passport number of the Account.</description>
    <label>Passport Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportType__c.field-meta.xml
<CustomField>
    <fullName>PassportType__c</fullName>
    <description>This field is a dropdown and the values are based on the passport types.</description>
    <label>Passport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentino</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>BNO</fullName>
            </value>
            <value>
                <fullName>Brazilian Passport</fullName>
            </value>
            <value>
                <fullName>Canadian</fullName>
            </value>
            <value>
                <fullName>China Travel card</fullName>
            </value>
            <value>
                <fullName>Chinese Passport</fullName>
            </value>
            <value>
                <fullName>Diplomatic</fullName>
            </value>
            <value>
                <fullName>European Passport</fullName>
            </value>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Greek ID</fullName>
            </value>
            <value>
                <fullName>Greek Passport</fullName>
            </value>
            <value>
                <fullName>HKSAR</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Macau SAR</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>National ID Card</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Ordinary</fullName>
            </value>
            <value>
                <fullName>Philippine</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
            <value>
                <fullName>Taiwanese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PersonalID__c.field-meta.xml
<CustomField>
    <fullName>PersonalID__c</fullName>
    <description>Option to enter the ID number of the Account.</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>This field is used to display the PA Age on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>Account.Age__c</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is used in order to display the PA Email2 on the Opp PL.
Note: To be deleted as soon as the PA component on OPP PL is functional.</description>
    <formula>Account.Email2__c</formula>
    <label>Email2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is used to display the Account Gender on the Opportunity Page Layout.
Note: To be deleted as soon as the Person Account Component on the Opportunity Page Layout is functional.</description>
    <formula>TEXT(   Account.Gender__c  )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>This field is used to display the PA Nationality on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>TEXT( Account.Nationality__c )</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>This field is used to display the PA Nickname on the Opp PL.
Note: To be removed as soon as the the PA component on Opp PL is functional.</description>
    <formula>Account.Nickname__c</formula>
    <label>Nickname</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CreateBookingController.cls
/**
 * Created by arjun.mohan on 3/9/2018.
 */

public class CreateBookingController {

    @AuraEnabled
    public static IntermediateScreenWrapper dataBind(String recordId) {
        System.debug('Opportunity is ' + recordId);
        try {
            if (!String.isEmpty(recordId) && Id.valueOf(recordId).getSobjectType() == Opportunity.getSObjectType()) {
                List<Account> fetchAccount = new List<Account>();
                IntermediateScreenWrapper bindData = new IntermediateScreenWrapper();
                List<Opportunity> fetchopp = new List<Opportunity>();
                fetchopp = [
                        select id,SalesOffice__c,Market__c,Program__c,AccountId,IsActive__c
                        from Opportunity
                        where ID = :Id.valueOf(recordId) AND IsActive__c = TRUE
                        LIMIT 1
                ];
                System.debug('Opportunity is ' + fetchopp);
                bindData.opp = fetchopp[0];
                bindData.SalesOfficePickList = GetSalesOffice();
                if (fetchopp.size() > 0) {
                    fetchAccount = [
                            select id,Salutation,FirstName,MiddleName,LastName,PersonBirthdate,PersonOtherCity,PersonOtherState,
                                    PersonOtherPostalCode,PersonOtherStreet,PersonEmail,PersonHomePhone,PersonMobilePhone,PersonOtherPhone,
                                    FirstNameEn__c,LastNameEn__c,Age__c,ParentEmail__c,PersonalID__c,PassportNumber__c,PassportType__c,OtherNationalities__c,
                                    PassportIssueDate__c,PassportExpiryDate__c,Nationality__c,NickName__c,Gender__c,BirthCountry__c,
                                    Email2__c,PersonMailingStreet,PersonMailingPostalCode,PersonMailingCity,PersonMailingCountry,InvoiceEmail__c,
                                    PersonMailingState
                            from Account
                            where ID = :bindData.opp.AccountId
                            LIMIT 1
                    ];
                    bindData.personAcc = fetchAccount[0];
                    System.debug('Account is ' + fetchAccount[0]);
                    bindData.age = fetchAccount[0].Age__c;
                    bindData.GenderPickList = GetGender();
                    bindData.NationalityPickList = GetNationality();
                    bindData.OtherNationalityPickList = GetOtherNationality();
                    bindData.PassportPickList = GetPassportType();
                    bindData.MailingCountryPickList = GetMailingCountry();
                    bindData.BirthCountryPickList = GetBirthCountry();
                    return bindData;
                } else {
                    throw new AuraHandledException('Label.NoActiveOpportunity');
                }
            } else {
                throw new AuraHandledException('InValid Record for create Booking');
            }
        } catch (Exception ex) {
            ExceptionHandler.errorLogAsync(ex.getMessage(), ex.getStackTraceString(),
                    'CreatePriceQuoteController', 'openPoseidonToCreateQuote', null);
            throw new AuraHandledException(ex.getMessage());
        }

    }

    @AuraEnabled
    public static String updateAccountDetails(String wrapperData) {
        String retValue = '';
        System.debug('Sending data ' + wrapperData);
        Id currentrecord;
        IntermediateScreenWrapper BindWrapper = (IntermediateScreenWrapper) JSON.deserialize(wrapperData, IntermediateScreenWrapper.class);
        try {
            update BindWrapper.personAcc;
            retValue = SyncToPoseidonController.SyncComplicatedBookingToPoseidon(String.ValueOf(BindWrapper.personAcc.Id), true);
        } catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'CreateBookingController', 'updateAccountDetails', currentrecord);
            System.debug('Dml exception :' + ex.getMessage());
        }
        return retValue;
    }

/*    @AuraEnabled
    public static String CreateBookingInPoseidon(String AccountId) {
        return SyncToPoseidonController.SyncComplicatedBookingToPoseidon(AccountId);
    }*/

    public static Map<String, String> GetGender() {
        return FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'Gender__c');
        //return JSON.serialize(genderMap);
    }

    public static Map<String, String> GetSalesOffice() {
        return FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'SalesOffice__c');
        //return JSON.serialize(genderMap);
    }

    public static Map<String, String> GetNationality() {
        return FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'Nationality__c');
        //return JSON.serialize(NationalityMap);
    }

    public static Map<String, String> GetOtherNationality() {
        return FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'OtherNationalities__c');
        // return JSON.serialize(OtherNationalityMap);
    }

    public static Map<String, String> GetPassportType() {
        return FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'PassportType__c');
        // return JSON.serialize(PassportMap);
    }

    public static Map<String, String> GetBirthCountry() {
        return FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'BirthCountry__c');
        // return JSON.serialize(PassportMap);
    }

    public static Map<String, String> GetMailingCountry() {
        return FieldUtilityClass.getPickListValues(Contact.getSObjectType(), 'MailingCountryCode');
        // return JSON.serialize(PassportMap);
    }


    Public class IntermediateScreenWrapper {
        @AuraEnabled
        public Account personAcc { get; set; }
        @AuraEnabled
        public Opportunity opp { get; set; }
        @AuraEnabled
        public Decimal age { get; set; }
        @AuraEnabled
        public Map<String, String> GenderPickList { get; set; }
        @AuraEnabled
        public Map<String, String> MailingCountryPickList { get; set; }
        @AuraEnabled
        public Map<String, String> NationalityPickList { get; set; }
        @AuraEnabled
        public Map<String, String> OtherNationalityPickList { get; set; }
        @AuraEnabled
        public Map<String, String> PassportPickList { get; set; }
        @AuraEnabled
        public Map<String, String> SalesOfficePickList { get; set; }
        @AuraEnabled
        public Map<String, String> BirthCountryPickList { get; set; }

    }


}