force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Person Account Age</description>
    <formula>FLOOR((TODAY() -  PersonContact.Birthdate  )/365.2425)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstNameEn__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEn__c</fullName>
    <description>This field will show the English translation of First Name.</description>
    <label>First Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <!--<defaultValue>$User.TF_Default_Language__c</defaultValue>-->
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LastNameEn__c.field-meta.xml
<CustomField>
    <fullName>LastNameEn__c</fullName>
    <description>This field will show the English translation of Last Name.</description>
    <label>Last Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>PassportExpiryDate__c</fullName>
    <description>Option to enter the passport expiry date. This field would be a calendar control.</description>
    <label>Passport Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportIssueDate__c.field-meta.xml
<CustomField>
    <fullName>PassportIssueDate__c</fullName>
    <description>Option to enter the passport issue date. This field would be a calendar control.</description>
    <label>Passport Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <description>Option to enter passport number of the Account.</description>
    <label>Passport Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportType__c.field-meta.xml
<CustomField>
    <fullName>PassportType__c</fullName>
    <description>This field is a dropdown and the values are based on the passport types.</description>
    <label>Passport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentino</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>BNO</fullName>
            </value>
            <value>
                <fullName>Brazilian Passport</fullName>
            </value>
            <value>
                <fullName>Canadian</fullName>
            </value>
            <value>
                <fullName>China Travel card</fullName>
            </value>
            <value>
                <fullName>Chinese Passport</fullName>
            </value>
            <value>
                <fullName>Diplomatic</fullName>
            </value>
            <value>
                <fullName>European Passport</fullName>
            </value>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Greek ID</fullName>
            </value>
            <value>
                <fullName>Greek Passport</fullName>
            </value>
            <value>
                <fullName>HKSAR</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Macau SAR</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>National ID Card</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Ordinary</fullName>
            </value>
            <value>
                <fullName>Philippine</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
            <value>
                <fullName>Taiwanese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PersonalID__c.field-meta.xml
<CustomField>
    <fullName>PersonalID__c</fullName>
    <description>Option to enter the ID number of the Account.</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>Please enter the Version of the Brochure.</description>
    <label>Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
            </value>
            <value>
                <fullName>V2</fullName>
            </value>
            <value>
                <fullName>V3</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Please enter the Year of the Brochure.</description>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apts_Price_List__c.field-meta.xml
<CustomField>
    <fullName>Apts_Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EF Price List</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Market__c</field>
            <operation>equals</operation>
            <valueField>Apttus_Config2__PriceList__c.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>Apttus_Config2__PriceList__c.Program__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CurrencyIsoCode</field>
            <operation>equals</operation>
            <valueField>Apttus_Config2__PriceList__c.CurrencyIsoCode</valueField>
        </filterItems>
        <filterItems>
            <field>Apttus_Config2__PriceList__c.Apttus_Config2__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
    <relationshipLabel>Proposals (Price List)</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/BookingChannel__c.field-meta.xml
<CustomField>
    <fullName>BookingChannel__c</fullName>
    <description>This field specifies from which channel the booking has been initiated.</description>
    <label>Booking Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>ExhibitionFair</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/BookingType__c.field-meta.xml
<CustomField>
    <fullName>BookingType__c</fullName>
    <description>This field displays the Booking type for sending data to Poseidon through Quote to Booking.</description>
    <label>Booking Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BKN</fullName>
            </value>
            <value>
                <fullName>PRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/SalesMadeby__c.field-meta.xml
<CustomField>
    <fullName>SalesMadeby__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the user name, which can be changed at the time of Booking in Booking Summary Component</description>
    <label>Sales Made by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>This field is used to display the PA Age on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>Account.Age__c</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is used in order to display the PA Email2 on the Opp PL.
Note: To be deleted as soon as the PA component on OPP PL is functional.</description>
    <formula>Account.Email2__c</formula>
    <label>Email2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is used to display the Account Gender on the Opportunity Page Layout.
Note: To be deleted as soon as the Person Account Component on the Opportunity Page Layout is functional.</description>
    <formula>TEXT(   Account.Gender__c  )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>This field is used to display the PA Language on the Opportunity PL.
Note: To be removed as soon as the PA component on Opportunity is functional.</description>
    <formula>TEXT( Account.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>This field is used to display the PA Nationality on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>TEXT( Account.Nationality__c )</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>This field is used to display the PA Nickname on the Opp PL.
Note: To be removed as soon as the the PA component on Opp PL is functional.</description>
    <formula>Account.Nickname__c</formula>
    <label>Nickname</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BindSobject.cls
public class BindSobject {
    //Create list of wrapper to grab all sobject records
    //@AuraEnabled
    //Public List<SobjectBindWrapper> bindbedSobjectsToBeInserted;
    @AuraEnabled
    public static SobjectBindWrapper dataBind(String QuoteId){
        Id currentrecord;
        System.debug('&&&&&&&&&&&QuoteId&&&&&&&&&'+QuoteId);
        SobjectBindWrapper bindData = new SobjectBindWrapper();
        try{
        
        Apttus_Proposal__Proposal__c fetchQuote = new Apttus_Proposal__Proposal__c();
        fetchQuote = [select id,Apts_Price_List__c,Apts_Price_List__r.Name,CurrencyIsoCode,Apttus_QPConfig__PriceListId__c,Apttus_QPConfig__PriceListId__r.year__c,                     
                     Apttus_QPConfig__PriceListId__r.Version__C,BookingType__c,BookingChannel__c ,SalesMadeby__c,SalesMadeby__r.name,
                     Apttus_Proposal__Account__c,Apttus_Proposal__Opportunity__c
                     from Apttus_Proposal__Proposal__c where id=:QuoteId];
        bindData.Quote =   fetchQuote;
        System.debug('&&&&&&&&&&&Quote&&&&&&&&&'+bindData.Quote);
    
        Account fetchAccount = new Account();
        /*Id prsnRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        System.debug('*******************'+prsnRecordTypeId);*/
        fetchAccount = [select id,Name,Salutation,RecordTypeID,RecordType.Name,FirstName,MiddleName,LastName,PersonBirthdate,PersonOtherCity,PersonOtherState,
                        PersonOtherPostalCode,PersonOtherStreet,PersonEmail,PersonHomePhone,PersonMobilePhone,PersonOtherPhone,
                        FirstNameEn__c,LastNameEn__c,Language__C,Age__c,ParentEmail__c,PersonalID__c,PassportNumber__c,PassportType__c,
                PassportIssueDate__c,PassportExpiryDate__c,Nationality__c,NickName__c,Gender__c,
                Email2__c,PersonMailingStreet,PersonMailingPostalCode,PersonMailingCity,PersonMailingCountry,
                        PersonMailingState from Account where ID =:fetchQuote.Apttus_Proposal__Account__c LIMIT 1];
            System.debug('^^^^^^^^^^^^^^^'+fetchAccount);
            bindData.personAcc = fetchAccount;
            bindData.age = fetchAccount.Age__c;
            System.debug('^^^^^^^^ bindData.personAcc^^^^^^^'+ bindData.personAcc);
 
        Opportunity fetchopp = new Opportunity();
        fetchopp = [select id,Name,StageName,AccountID,SalesOffice__c,OwnerId,Owner.Name,CloseDate
                    from Opportunity where AccountID =: fetchAccount.Id];
        bindData.opp =   fetchopp;
        
        Apttus_Config2__PriceList__c fetchPrice = new Apttus_Config2__PriceList__c();
            fetchPrice = [select id,Year__c,Apttus_Config2__AccountId__c,Version__c from Apttus_Config2__PriceList__c 
                          where id=:fetchQuote.Apttus_QPConfig__PriceListId__c];
            bindData.PriceList =   fetchPrice;
            System.debug('^^^^^^^^ bindData.PriceList^^^^^^^'+ bindData.PriceList);

        
        
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'dataBind', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
        }
        return bindData;
    }
    
    @AuraEnabled
    public static String GetSalesOffice() {
        Map<String, String> SalesOffice = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'SalesOffice__c');
        return JSON.serialize(SalesOffice.keySet());
    }
    
    @AuraEnabled
    public static String GetGender() {
        Map<String, String> Gender = FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'Gender__c');
        return JSON.serialize(Gender.keySet());
    }

    @AuraEnabled
    public static String GetBookingType() {
        Map<String, String> BookingType = FieldUtilityClass.getPickListValues(Apttus_Proposal__Proposal__c.getSObjectType(), 'BookingType__c');
        return JSON.serialize(BookingType.keySet());
    }


   /* @AuraEnabled
    public static String GetBookingType() {
        Map<String, String> BookingType = FieldUtilityClass.getPickListValues(Apttus_Proposal__Proposal__c.getSObjectType(), 'BookingType__c');

        Schema.SObjectField F = BookingType.get(Apttus_Proposal__Proposal__c.BookingType__c); //where fieldAPIName is API name of field
        Schema.DescribeFieldResult R = F.getDescribe();
        String fieldLabel=R.getLabel();
        return fieldLabel;
    }
    
        /*@AuraEnabled

	public static List<SelectOption> GetBookingType() {

        List<SelectOption> options = new List<SelectOption>();

        Schema.SObjectField F = fieldNameMap.get(fieldAPIName); //where fieldAPIName is API name of field
Schema.DescribeFieldResult R = F.getDescribe();
String fieldLabel=R.getLabel();
return fieldLabel;
    
        Schema.DescribeFieldResult fieldResult = Apttus_Proposal__Proposal__c.BookingType__c.getDescribe();
    
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry f: ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return options;
		
		}*/

    @AuraEnabled
    public static String GetBookingChannel() {
        Map<String, String> BookingChannel = FieldUtilityClass.getPickListValues(Apttus_Proposal__Proposal__c.getSObjectType(), 'BookingChannel__c');
        return JSON.serialize(BookingChannel.keySet());
    }
    
    
    @AuraEnabled
    public static String GetCurrency() {
        Map<String, String> CurrencyVal = FieldUtilityClass.getPickListValues(Apttus_Proposal__Proposal__c.getSObjectType(), 'CurrencyIsoCode');
        return JSON.serialize(CurrencyVal.keySet());
    }
    
    @AuraEnabled
    public static String GetNationality() {
        Map<String, String> Nationality = FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'Nationality__c');
        return JSON.serialize(Nationality.keySet());
    }
    @AuraEnabled
    public static String GetPassportType() {
        Map<String, String> PassportType = FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'PassportType__c');
        return JSON.serialize(PassportType.keySet());
    }
    
    @AuraEnabled
    public static String GetCountryValues() {
        Map<String, String> maillingCountry = FieldUtilityClass.getCountryPickListValues();
        system.debug('return=====>' +JSON.serialize(maillingCountry.keySet()));
        return JSON.serialize(maillingCountry.keySet());
        
    }
    
     @AuraEnabled
    public static String GetStateValues() {
        Map<String, String> maillingState = FieldUtilityClass.getStatePickListValues();
        system.debug('return=====>' +JSON.serialize(maillingState.keySet()));
        return JSON.serialize(maillingState.keySet());
        
    }  

    @AuraEnabled
    public static boolean createRecord(String wrapperData,Boolean isFinishBooking){
        Id currentrecord;
        
        System.debug('*************'+isFinishBooking);
        System.debug('*************'+wrapperData);

        SobjectBindWrapper listToSave = (SobjectBindWrapper)JSON.deserialize(wrapperData, SobjectBindWrapper.class);
        System.debug('*************'+listToSave);
        
        Account AccountUpdate = new Account();
        AccountUpdate.id = listToSave.personAcc.Id;
        AccountUpdate.FirstNameEn__c = listToSave.personAcc.FirstNameEn__c;
        AccountUpdate.LastNameEn__c = listToSave.personAcc.LastNameEn__c;
        AccountUpdate.PersonOtherPostalCode = listToSave.personAcc.PersonOtherPostalCode;
        AccountUpdate.PersonOtherCity = listToSave.personAcc.PersonOtherCity;
        //AccountUpdate.PersonOtherState = listToSave.personAcc.PersonOtherState;
        AccountUpdate.PersonOtherStreet = listToSave.personAcc.PersonOtherStreet;
        AccountUpdate.FirstName = listToSave.personAcc.FirstName;
        System.debug('Before Update MiddleName=============> ' +AccountUpdate.MiddleName);
        AccountUpdate.MiddleName = listToSave.personAcc.MiddleName;
        System.debug('Updated MiddleName=============> ' +listToSave.personAcc.MiddleName);
        System.debug('After Update MiddleName=============> ' +AccountUpdate.MiddleName);
        AccountUpdate.LastName = listToSave.personAcc.LastName;
        AccountUpdate.Salutation = listToSave.personAcc.Salutation;

        if(listToSave.personAcc.FirstName <> null){
            AccountUpdate.FirstName = listToSave.personAcc.FirstName;
        }
        if(listToSave.personAcc.MiddleName <> null){
            AccountUpdate.MiddleName = listToSave.personAcc.MiddleName;
        }
        if(listToSave.personAcc.LastName <> null){
            AccountUpdate.LastName = listToSave.personAcc.LastName;
        }
        AccountUpdate.PersonBirthdate = listToSave.personAcc.PersonBirthdate;
        AccountUpdate.PersonHomePhone = listToSave.personAcc.PersonHomePhone;
        AccountUpdate.Language__C = listToSave.personAcc.Language__C;
        AccountUpdate.PersonMobilePhone = listToSave.personAcc.PersonMobilePhone;
        AccountUpdate.PersonOtherPhone = listToSave.personAcc.PersonOtherPhone;
        if(listToSave.personAcc.Salutation <> null){
            AccountUpdate.Salutation = listToSave.personAcc.Salutation;
        }
        AccountUpdate.Nationality__c = listToSave.personAcc.Nationality__c;
        AccountUpdate.FirstName = listToSave.personAcc.FirstName;
        AccountUpdate.MiddleName = listToSave.personAcc.MiddleName;
        AccountUpdate.LastName = listToSave.personAcc.LastName;
        AccountUpdate.Gender__c = listToSave.personAcc.Gender__c;
       // AccountUpdate.Age__c = listToSave.personAcc.Age__c;
        AccountUpdate.NickName__c = listToSave.personAcc.NickName__c;
        AccountUpdate.PersonMailingCountry = listToSave.personAcc.PersonMailingCountry;
        AccountUpdate.PersonMailingCity = listToSave.personAcc.PersonMailingCity;
        AccountUpdate.PersonMailingState = listToSave.personAcc.PersonMailingState;
        AccountUpdate.PersonMailingStreet = listToSave.personAcc.PersonMailingStreet;
       // AccountUpdate.BirthCountry__pc = listToSave.personAcc.BirthCountry__pc;
        AccountUpdate.PersonEmail = listToSave.personAcc.PersonEmail;
        AccountUpdate.Email2__c = listToSave.personAcc.Email2__c;
        AccountUpdate.ParentEmail__c = listToSave.personAcc.ParentEmail__c;
        AccountUpdate.PersonalID__c = listToSave.personAcc.PersonalID__c;
        AccountUpdate.PassportNumber__c = listToSave.personAcc.PassportNumber__c;
        AccountUpdate.PassportType__c = listToSave.personAcc.PassportType__c;
        AccountUpdate.PassportIssueDate__c = listToSave.personAcc.PassportIssueDate__c;
        AccountUpdate.PassportExpiryDate__c = listToSave.personAcc.PassportExpiryDate__c;
        try{
            update AccountUpdate;
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'createRecord', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
        }
                
        Opportunity oppUpdate = new Opportunity();
        oppUpdate.Id = listToSave.opp.ID;
        oppUpdate.SalesOffice__c = listToSave.opp.SalesOffice__c;
        // oppUpdate.OwnerId = listToSave.opp.OwnerId;
        oppUpdate.IntegrationStatus__c = 'Sent To Poseidon';
        oppUpdate.BookingCreationTime__c = System.now();
        try{
            update oppUpdate;
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'createRecord', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
        }

        Apttus_Config2__PriceList__c PLUpdate = new Apttus_Config2__PriceList__c();
        //PLUpdate.Id = listToSave.PriceList.ID;
        PLUpdate.Version__c = listToSave.PriceList.Version__c;
        PLUpdate.Year__c = listToSave.PriceList.Year__c;
            if(listToSave.PriceList <> null){
                PLUpdate.Id = listToSave.PriceList.ID;
                 PLUpdate.Version__c = listToSave.PriceList.Version__c;
            }
             if(listToSave.PriceList.Version__c <> null){
                PLUpdate.Version__c = listToSave.PriceList.Version__c;
             }
        if(PLUpdate.Id == null){
                    PLUpdate.Id = listToSave.PriceList.ID;
        }
                try{
                    update PLUpdate;
                    System.debug('^^^^^^^^  Updated PriceList^^^^^^^'+ PLUpdate);

                }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'createRecord', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
                }
        
        Apttus_Proposal__Proposal__c QuoUpdate = new Apttus_Proposal__Proposal__c();
        QuoUpdate.Id = listToSave.Quote.ID;
        system.debug('Null here '+listToSave.Quote.Apttus_QPConfig__PriceListId__r.Version__c );
        /*if(listToSave.Quote.Apttus_QPConfig__PriceListId__r.Version__c != null){
         QuoUpdate.Apttus_QPConfig__PriceListId__r.Version__c = listToSave.Quote.Apttus_QPConfig__PriceListId__r.Version__c;
        }*/

        QuoUpdate.CurrencyIsoCode = listToSave.Quote.CurrencyIsoCode; 
        QuoUpdate.BookingType__c = listToSave.Quote.BookingType__c;
        QuoUpdate.BookingChannel__c = listToSave.Quote.BookingChannel__c;
                system.debug('Sales user ' +listToSave.Quote.SalesMadeby__c);
        QuoUpdate.SalesMadeby__c = listToSave.Quote.SalesMadeby__c;
                system.debug('QuoUpdate.SalesMadeby__c  ' +QuoUpdate.SalesMadeby__c);

        system.debug('Null here ' +isFinishBooking);

        QuoUpdate.IntegrationStatus__c =(isFinishBooking)? 'Sent To Poseidon':'';
        system.debug('Null here '+listToSave.Quote.IntegrationStatus__c );


        try{
            update QuoUpdate;
        }
        catch(Exception ex){
					ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'createRecord', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
        }
        
            
        try{
             return true;
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'createRecord', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
            return false;
        }
    }
    //Wrapper for binding all sobject to reduce multiple DML transaction and to avoid Mixed DML 
        Public class SobjectBindWrapper{
            @AuraEnabled
            public Account personAcc {get;set;}
            @AuraEnabled
            public Opportunity opp {get;set;}
            @AuraEnabled
            public Apttus_Config2__PriceList__c PriceList {get;set;}
            @AuraEnabled
            public Apttus_Proposal__Proposal__c Quote {get;set;}
            @AuraEnabled
            public Decimal age {get;set;}
           
        }
    
    // For returning List in Aura Enable	
		public class SelectOption {
    public SelectOption(String value, String label) {
        this.value = value;
        this.label = label;
        this.disabled = false;
        this.escapeItem = false;
    }

    public SelectOption(String value, String label, Boolean isDisabled) {
        this.value = value;
        this.label = label;
        this.disabled = isDisabled;
        this.escapeItem = false;
    }

    @AuraEnabled
    public String label { get;set; }
    @AuraEnabled
    public String value { get;set; }
    @AuraEnabled
    public Boolean disabled { get;set; }
    @AuraEnabled
    public Boolean escapeItem { get;set; }

}
    
}