force-app/main/default/objects/Account/fields/DoNotCall__c.field-meta.xml
<CustomField>
    <fullName>DoNotCall__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify when the customer should not be called.</description>
    <inlineHelpText>Check this field if we explicitly do not want to call this customer again or if the customer has requested not to be contacted by phone.</inlineHelpText>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/HasBooking__c.field-meta.xml
<CustomField>
    <fullName>HasBooking__c</fullName>
    <description>This field is used to indicate if this Account has a booking linked to it in status 'BKN'</description>
    <formula>BookingsinstatusBKN__c  &lt;> 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceEmail__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmail__c</fullName>
    <description>This field is used to store the email-address to which invoices should be send.</description>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfUnreachedHappyCalls__c.field-meta.xml
<CustomField>
    <fullName>NumberOfUnreachedHappyCalls__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Store number of unreached happy calls</description>
    <label>Number Of Unreached Happy Calls</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecalculateRanking__c.field-meta.xml
<CustomField>
    <fullName>RecalculateRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for recalculating the ranking once a new activity for the existing customer is imported</description>
    <label>Recalculate Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountsSelector.cls
/**************************************************************************************
Apex Class Name    : AccountsSelector
Version            : 1.0
Created Date       : July 16 2017
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * shravan.boddula                 07/12/2017              Original Version
*******************************************************************************/
public class AccountsSelector {

    public static Account getAccountOnId(Id accountId) { 
        return [
                select id,Name,FirstName,LastName,PersonMailingCity,PersonMailingCountry,PersonMailingPostalCode,
                        PersonMailingStreet, RecalculateRanking__c, PersonEmail,Email2__c,PersonHomePhone,PersonMobilePhone,
                        PersonOtherPhone,PersonBirthdate,Market__c,Region__c,
                        HasBooking__c, NumberOfUnreachedHappyCalls__c,CurrencyIsoCode,DoNotCall__c
                from Account
                where Id = :accountId
                limit 1
        ];
    }


    public static List<Account> getAccountsWithOpportunitiesByContactIds(Set<Id> contactIds) {
        return [
                SELECT Id, Name, Market__c, PersonContactId, (SELECT Id FROM Opportunities WHERE IsActive__c = TRUE)
                FROM Account
                WHERE PersonContactId IN :contactIds
        ];
    }

    public static map<Id, Account> getAccountDetailsbasedonAccountId(Set<Id> accountIdSet) {
        List<String> accountMissingFields = new List<String>{
                'Name', 'Id', 'Market__c', 'CreatedById', 'LastModifiedById', 'firstname', 'lastname', 'ParentEmail__c', 'middlename', 'PersonMailingCity', 'PersonMailingPostalCode', 'PersonMailingCountryCode', 'PersonMailingState', 'ShippingCity', 'ShippingState', 'ShippingStreet', 'PersonOtherPostalCode'
        };
        List<Account> accList = new List<Account>();
        Map<Id, Account> accountMap = new Map<Id, Account>();
        Set<String> fieldsToSelect = new Set<String>();
        String query = 'SELECT ';
        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.UpdatePersonalInfo.getFields()) {
            fieldsToSelect.add(f.getFieldPath());
            query += f.getFieldPath() + ', ';
        }
        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.Address.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
                query += f.getFieldPath() + ', ';
            }
        }

        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.Customer.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
                query += f.getFieldPath() + ', ';
            }
        }
        for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.CustomerMarketingPref.getFields()) {
            if (!fieldsToSelect.contains(f.getFieldPath())) {
                fieldsToSelect.add(f.getFieldPath());
                query += f.getFieldPath() + ', ';
            }
        }
        for (String accountField : accountMissingFields) {
            if (!fieldsToSelect.contains(accountField)) {
                fieldsToSelect.add(accountField);
                query += accountField + ', ';
            }
        }
        if (query.endsWith(', ')) {
            query = query.substringBeforeLast(',');
        }
        query += ' from Account Where Id in   : ' + 'accountIdSet' + ' ' ;
        System.debug('Dynamic Query :' + query);
        accList = Database.query(query);
        for (Account accRecord : accList) {
            accountMap.put(accRecord.Id, accRecord);
        }
        return accountMap;
    }

    public static Map<ID,Account> getAccountsWithActiveOpportunitiesByIds(Set<Id> accountIds){
        Map<ID,Account> accountWithActiveOpportunities = new Map<ID,Account>([
                SELECT Id, Name, Market__c, PersonContactId, (SELECT Id FROM Opportunities WHERE IsActive__c = TRUE limit 1)
                FROM Account
                WHERE id IN :accountIds]);
        return accountWithActiveOpportunities;
    }
    
    public static map<Id, Account> getAccountBasedonAccountId(Set<Id> accountIds) {
        Map<ID,Account> accountMap = new Map<ID,Account>([
                SELECT Id,IsPseudonymised__pc, Email2__c, hasBooking__c,FirstName, InvoiceEmail__c, LastName,ParentEmail__c,PersonEmail,PersonHomePhone,
                        PersonMailingCity,PersonMailingCountry,PersonMailingCountryCode, PersonMailingPostalCode,
                        PersonMailingState, PersonMailingStateCode,PersonMailingStreet,PersonMobilePhone,PersonOtherPhone,Gender__c
                FROM Account
                WHERE id IN :accountIds]);
        return accountMap;
    }
}