force-app/main/default/objects/Account/fields/DoNotCall__c.field-meta.xml
<CustomField>
    <fullName>DoNotCall__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify when the customer should not be called.</description>
    <inlineHelpText>Check this field if we explicitly do not want to call this customer again or if the customer has requested not to be contacted by phone.</inlineHelpText>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfUnreachedHappyCalls__c.field-meta.xml
<CustomField>
    <fullName>NumberOfUnreachedHappyCalls__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Store number of unreached happy calls</description>
    <label>Number Of Unreached Happy Calls</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ReadyForHappyCall__c.field-meta.xml
<CustomField>
    <fullName>ReadyForHappyCall__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate that we need to make a happy call with this Account</description>
    <label>Ready for Happy Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity/fields/CallNotReachedType__c.field-meta.xml
<CustomField>
    <fullName>CallNotReachedType__c</fullName>
    <description>Select Sub Action if call not reached.</description>
    <label>Call Not Reached Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesAction__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Busy can’t talk</fullName>
            </value>
            <value>
                <fullName>Missing Number</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>Not at Home</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <label>Close Main Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Had intention and money, but chose to do something else</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had intention and money, but chose to do something else (soft no, we can try next year)</fullName>
                <isActive>false</isActive>
                <label>Had intention and money, but chose to do something else (soft no, we can try next year)</label>
            </value>
            <value>
                <fullName>Had no intention (ordered by mistake, didn't understand what it was for at all)</fullName>
                <isActive>false</isActive>
                <label>Had no intention (ordered by mistake, didn't understand what it was for at all)</label>
            </value>
            <value>
                <fullName>Lost to competitor (definitely try again)</fullName>
                <isActive>false</isActive>
                <label>Lost to competitor (definitely try again)</label>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/FollowUpDate__c.field-meta.xml
<CustomField>
    <fullName>FollowUpDate__c</fullName>
    <label>Follow-Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/NextCallType__c.field-meta.xml
<CustomField>
    <fullName>NextCallType__c</fullName>
    <description>Used to select the Next calltype of the task</description>
    <label>Next Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FUA</fullName>
                <label>Appointment</label>
            </value>
            <value>
                <fullName>Call</fullName>
                <isActive>false</isActive>
                <label>Call</label>
            </value>
            <value>
                <fullName>TCC</fullName>
                <label>Contact Customer</label>
            </value>
            <value>
                <fullName>FUP</fullName>
                <label>Follow-up</label>
            </value>
            <value>
                <fullName>MCR</fullName>
                <isActive>false</isActive>
                <label>MCR</label>
            </value>
            <value>
                <fullName>Meeting</fullName>
                <isActive>false</isActive>
                <label>Meeting</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PTS</fullName>
                <isActive>false</isActive>
                <label>PTS</label>
            </value>
            <value>
                <fullName>SBR</fullName>
                <isActive>false</isActive>
                <label>SBR</label>
            </value>
            <value>
                <fullName>SPQ</fullName>
                <isActive>false</isActive>
                <label>SPQ</label>
            </value>
            <value>
                <fullName>UCC</fullName>
                <label>Unreached Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Field is used to map program from lead to a customer request.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HappyCallRules__c/HappyCallRules__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Happy Call Rules</label>
</CustomObject>

force-app/main/default/objects/HappyCallRules__c/fields/MinUnreachedCallAttempts__c.field-meta.xml
<CustomField>
    <fullName>MinUnreachedCallAttempts__c</fullName>
    <defaultValue>2</defaultValue>
    <description>Minimal unreached call attempts to close Happy Call without reaching customer</description>
    <label>Min Unreached Call Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <description>Indicates the reason for closing the Opportunity</description>
    <inlineHelpText>Indicates the reason for closing the Opportunity</inlineHelpText>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chose to do something else</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Not able to contact customer</fullName>
            </value>
            <value>
                <fullName>Wrongly Imported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FollowupDateTime__c.field-meta.xml
<CustomField>
    <fullName>FollowupDateTime__c</fullName>
    <label>Follow-Up Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture the Source during the manual creation of the Opportunity</description>
    <label>Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Source__c.IsGlobal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Source__c.Market__c</field>
            <operation>equals</operation>
            <valueField>$Source.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>Source__c.AvailableforManualEntry__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Source is the way we track information about how the customers came to EF</description>
    <label>Source</label>
    <nameField>
        <label>Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app++/main/default/objects/Source__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Displays the code of the Source</description>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True then the source is active</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Displays the Market to which the Source belongs; ALL in case of global Source</description>
    <label>Market</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Displays the name of the Code</description>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/SystemCallTask.recordType-meta.xml
<RecordType>
    <fullName>SystemCallTask</fullName>
    <active>true</active>
    <description>Referred for Automatic creation of Call Task</description>
    <label>System Call Task</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountLogACallControllerTest.cls
/**
 * Created by britenet-patrykzak on 16/04/2018.
 */

@IsTest
private class AccountLogACallControllerTest {


    @testSetup static void setup() {
        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
    }

    @IsTest
    static void When_getInitialData_Expect_ReturnAccountFieldValues() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();
            accPerson.PersonMobilePhone = '+48888888881';
            accPerson.PersonOtherPhone = '+48888888882';
            accPerson.PersonHomePhone = '+48888888883';
            accPerson.DoNotCall__c = false;
            update accPerson;

            Test.startTest();

            Account accInitialData = AccountLogACallController.getInitialData(accPerson.Id);

            Test.stopTest();

            System.assertEquals(accInitialData.PersonMobilePhone,accPerson.PersonMobilePhone,'Successfully passed required data');
            System.assertEquals(accInitialData.PersonOtherPhone,accPerson.PersonOtherPhone,'Successfully passed required data');
            System.assertEquals(accInitialData.PersonHomePhone,accPerson.PersonHomePhone,'Successfully passed required data');
            System.assertEquals(accInitialData.DoNotCall__c,accPerson.DoNotCall__c,'Successfully passed required data');

        }
    }
    
    @IsTest
    static void When_getExPaxSourceAndItExists_Expect_ReturnExPaxSourceId() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            Source__c src = new Source__c();
            src.Name = Label.ExPaxExENQ;
            src.Code__c = Label.ExPaxSourceCode;
            src.Market__c = 'ALL';
            insert src;

            Test.startTest();

            Id exPaxSourceId = AccountLogACallController.getExPaxSource();

            Test.stopTest();

            System.assertEquals(exPaxSourceId,src.Id,'Successfully retrieved ExPax Source Id');

        }
    }
    
    @IsTest
    static void When_getExPaxSourceAndItDoesNotExist_Expect_ThrowException() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            Test.startTest();

            try {
                Id exPaxSourceId = AccountLogACallController.getExPaxSource();
            } catch (Exception e){
                Boolean expectedExceptionThrown =  true;
                System.AssertEquals(expectedExceptionThrown, true, 'Exception thrown cannot find Source with such code');
            }

            Test.stopTest();
        }
    }
    
    @IsTest
    static void When_getSalesActions_Expect_ReturnOnlyCallReachedAndCallNotReachedValues() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            Test.startTest();

            List<String> salesActionsValues = AccountLogACallController.getSalesActions();

            Test.stopTest();

            System.assert(salesActionsValues.contains(Label.CallReached));
            System.assert(salesActionsValues.contains(Label.CallNotReached));
            System.assertEquals(2,salesActionsValues.size(),'Only 2 values shall be returned');

        }
    }
    
    @IsTest
    static void When_getSubActions_Expect_ReturnAllSubActionValues() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            Test.startTest();

            List<String> subActionsValues = AccountLogACallController.getSubActions();

            Test.stopTest();

            System.assert(subActionsValues.size()>0,'Cannot predict how many values, but it shall always return some values');

        }
    }
    
    @IsTest
    static void When_getCallResultsAndUnreachedHappyCallsLessThanMinRequiredValue_Expect_ReturnCallBackOnly() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            HappyCallRules__c hcr = new HappyCallRules__c();
            hcr.Name = Label.HCC;
            hcr.MinUnreachedCallAttempts__c=2;
            insert hcr;

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            String callAction = Label.CallNotReached;

            Test.startTest();

            List<String> callResultsValues = AccountLogACallController.getCallResults(callAction,accPerson.Id);

            Test.stopTest();

            System.assert(callResultsValues.contains(Label.CallBack));
            System.assertEquals(1,callResultsValues.size(),'Only Call Back returned');
        }
    }
    
    @IsTest
    static void When_getCallResultsAndUnreachedHappyCallsEqualMinRequiredValue_Expect_ReturnCallBackAndClose() {

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            HappyCallRules__c hcr = new HappyCallRules__c();
            hcr.Name = Label.HCC;
            hcr.MinUnreachedCallAttempts__c=2;
            insert hcr;

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();
            accPerson.ReadyForHappyCall__c = true;
            accPerson.NumberOfUnreachedHappyCalls__c = 2;
            update accPerson;

            String callAction = Label.CallNotReached;

            Test.startTest();

            List<String> callResultsValues = AccountLogACallController.getCallResults(callAction,accPerson.Id);

            Test.stopTest();

            System.assert(callResultsValues.contains(Label.CallBack));
            System.assert(callResultsValues.contains(Label.Close));
            System.assertEquals(2,callResultsValues.size(),'Call back and Close are returned');
        }
    }
    
    @IsTest
    static void When_saveDataWithCallReachedClose_Expect_ExpectedBehavior(){

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            TestDataFactory.OpportunityBuilder opportunityBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity testOpportunity = (Opportunity)opportunityBuilder.getRecord();
            testOpportunity.IsActive__c = true;
            testOpportunity.AccountId = accPerson.Id;
            testOpportunity.Market__c = 'NOO';
            testOpportunity.Program__c = 'AY';
            insert testOpportunity;

            Datetime futureDatetime = System.today();

            Id SystemCallTaskRecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;

            Task task = new Task(
                    RecordTypeId = SystemCallTaskRecordTypeId,
                    WhatId = accPerson.Id,
                    NextCallType__c = Label.HCC_Next_Call_Type,
                    Type = Label.Call,
                    ActivityDate = Date.today(),
                    FollowUpDate__c = Date.today(),
                    Status = Label.Not_Started
            );
            insert task;

            String comments = 'comment';
            String callAction = Label.CallReached;
            String subAction = Label.Close;
            String closeReason = 'Has no means';
            String callResult = Label.Close;
            String actionDate = string.valueOfGmt(futureDatetime);

            Test.startTest();

            AccountLogACallController.saveData(accPerson.id,comments,callAction,subAction,callResult,actionDate);

            Test.stopTest();

            List<Task> happyCallTasks = [SELECT Id, status, FollowUpDate__c FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.HCC];
            List<Task> systemCallTasks = [SELECT Id, status FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.Call];

            System.assertEquals(1,happyCallTasks.size());
            System.assertEquals(Label.LAC_Closed,systemCallTasks[0].status);

        }
    }
    
    @IsTest
    static void When_saveDataWithCallNotReachedCallBack_Expect_ExpectedBehavior(){

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            TestDataFactory.OpportunityBuilder opportunityBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity testOpportunity = (Opportunity)opportunityBuilder.getRecord();
            testOpportunity.IsActive__c = true;
            testOpportunity.AccountId = accPerson.Id;
            testOpportunity.Market__c = 'NOO';
            testOpportunity.Program__c = 'AY';
            insert testOpportunity;

            Datetime futureDatetime = System.today();

            Id SystemCallTaskRecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;

            Task task = new Task(
                    RecordTypeId = SystemCallTaskRecordTypeId,
                    WhatId = accPerson.Id,
                    NextCallType__c = Label.HCC_Next_Call_Type,
                    Type = Label.Call,
                    ActivityDate = Date.today(),
                    FollowUpDate__c = Date.today(),
                    Status = Label.Not_Started
            );
            insert task;

            String comments = 'comment';
            String callAction = Label.CallNotReached;
            String subAction = 'No Answer';
            String closeReason = 'Has no means';
            String callResult = Label.CallBack;
            String actionDate = string.valueOfGmt(futureDatetime);

            Test.startTest();

            AccountLogACallController.saveData(accPerson.id,comments,callAction,subAction,callResult,actionDate);

            Test.stopTest();

            List<Task> happyCallTasks = [SELECT Id, status, CallNotReachedType__c FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.HCC];
            List<Task> systemCallTasks = [SELECT Id, status,FollowUpDate__c FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.Call];

            System.assertEquals(1,happyCallTasks.size());
            System.assertEquals(subAction,happyCallTasks[0].CallNotReachedType__c);
            System.assertEquals(Label.Not_Started,systemCallTasks[0].status);
        }
    }
    
    @IsTest
    static void When_saveDataWithCallNotReachedClose_Expect_ExpectedBehavior(){

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            TestDataFactory.OpportunityBuilder opportunityBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity testOpportunity = (Opportunity)opportunityBuilder.getRecord();
            testOpportunity.IsActive__c = true;
            testOpportunity.AccountId = accPerson.Id;
            testOpportunity.Market__c = 'NOO';
            testOpportunity.Program__c = 'AY';
            insert testOpportunity;

            Datetime futureDatetime = System.today();

            Id SystemCallTaskRecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;

            Task task = new Task(
                    RecordTypeId = SystemCallTaskRecordTypeId,
                    WhatId = accPerson.Id,
                    NextCallType__c = Label.HCC_Next_Call_Type,
                    Type = Label.Call,
                    ActivityDate = Date.today(),
                    FollowUpDate__c = Date.today(),
                    Status = Label.Not_Started
            );
            insert task;

            String comments = 'comment';
            String callAction = Label.CallNotReached;
            String subAction = 'No Answer';
            String closeReason = Label.NotAbleToContactCustomer;
            String callResult = Label.Close;
            String actionDate = string.valueOfGmt(futureDatetime);

            Test.startTest();

            AccountLogACallController.saveData(accPerson.id,comments,callAction,subAction,callResult,actionDate);

            Test.stopTest();

            List<Task> happyCallTasks = [SELECT Id, status, CallNotReachedType__c,CloseMainReason__c FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.HCC];
            List<Task> systemCallTasks = [SELECT Id, status,FollowUpDate__c FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.Call];

            System.assertEquals(1,happyCallTasks.size());
            System.assertEquals(subAction,happyCallTasks[0].CallNotReachedType__c);
            System.assertEquals(closeReason,happyCallTasks[0].CloseMainReason__c);
        }
    }
    
    @IsTest
    static void When_createTaskOnOpp_Expect_ExpectedBehavior(){

        User adminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        System.runAs(adminUser) {

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            TestDataFactory.OpportunityBuilder opportunityBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity testOpportunity = (Opportunity)opportunityBuilder.getRecord();
            testOpportunity.IsActive__c = true;
            testOpportunity.AccountId = accPerson.Id;
            testOpportunity.Market__c = 'NOO';
            testOpportunity.Program__c = 'AY';
            insert testOpportunity;

            Datetime futureDatetime = System.today()+1;

            Id SystemCallTaskRecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;
            String comments = 'comment';
            String callAction = Label.CallReached;
            String closeReason = 'Has no means';
            String callResult = Label.CallBack;
            String actionDate = string.valueOfGmt(futureDatetime);

            Task systemCallTask = new Task(
                    RecordTypeId = SystemCallTaskRecordTypeId,
                    WhatId = accPerson.Id,
                    NextCallType__c = Label.HCC_Next_Call_Type,
                    Type = Label.Call,
                    ActivityDate = Date.today(),
                    FollowUpDate__c = Date.today(),
                    Status = Label.Not_Started
            );
            insert systemCallTask;

            Test.startTest();

            AccountLogACallController.createTaskOnOpp(accPerson.id,testOpportunity.Id,comments,callAction,callResult,actionDate);

            Test.stopTest();

            List<Task> happyCallTasksOnAccount = [SELECT Id, Status, FollowUpDate__c FROM Task WHERE AccountId =:accPerson.Id AND WhatId =:testOpportunity.Id AND Type =:Label.HCC];
            List<Task> happyCallTasksOnOpportunity = [SELECT Id, Status, FollowUpDate__c, Description FROM Task WHERE WhatId =:testOpportunity.Id AND Type =:Label.HCC];
            List<Task> systemCallTasks = [SELECT Id, Status, IsClosed, ActivityDate FROM Task WHERE WhatId =: accPerson.Id AND Type =:Label.Call];
            Opportunity newOpportunityFromLogAnAction = [SELECT Name, FollowupDateTime__c FROM Opportunity WHERE Id =:testOpportunity.Id];

            System.assertEquals(1,happyCallTasksOnOpportunity.size(),'1 HappyCall Task shall be created on Opportunity');
            System.assertEquals(1,happyCallTasksOnAccount.size(),'HappyCall Task created on Opportunity shall be related to Account that was created from');
            System.assertEquals(true,systemCallTasks[0].isClosed,'The System Call Task should be Closed');
            System.assertEquals(Label.LAC_Closed,systemCallTasks[0].status,'The System Call Task status value should be Closed');
            System.assertEquals(Date.valueOf(actionDate),systemCallTasks[0].ActivityDate,'The System Call Task Activity Date shall be set');
            System.assertEquals(comments,happyCallTasksOnOpportunity[0].Description,'The System Call Task comments shall be passed to Description');
        }
    }
}