force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/HasBooking__c.field-meta.xml
<CustomField>
    <fullName>HasBooking__c</fullName>
    <description>This field is used to indicate if this Account has a booking linked to it in status 'BKN'</description>
    <formula>BookingsinstatusBKN__c  &lt;> 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RecalculateRanking__c.field-meta.xml
<CustomField>
    <fullName>RecalculateRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for recalculating the ranking once a new activity for the existing customer is imported</description>
    <label>Recalculate Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ActivityDateTime__c.field-meta.xml
<CustomField>
    <fullName>ActivityDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>ActivityDateTime</description>
    <inlineHelpText>ActivityDateTime</inlineHelpText>
    <label>ActivityDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is created for the secondary email and is replacing student email fields</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is used in order to display the PA Email2 on the Opp PL.
Note: To be deleted as soon as the PA component on OPP PL is functional.</description>
    <formula>Account.Email2__c</formula>
    <label>Email2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecalculateRanking__c.field-meta.xml
<CustomField>
    <fullName>RecalculateRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for recalculating the ranking once a new activity for the existing customer is imported</description>
    <label>Recalculate Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is used to display the PA Region on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>Account.Region__c</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/SPQTask.recordType-meta.xml
<RecordType>
    <fullName>SPQTask</fullName>
    <active>true</active>
    <description>Reffered for SPQ Task</description>
    <label>SPQ Task</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CreatePriceQuoteControllerTest.cls
@isTest
public class CreatePriceQuoteControllerTest {
    public static String market = 'DEB';

    @testSetup
    static void testDataSetup() {
        Profile SystemAdminProfile = TestDataFactory.getProfile('System Administrator', true);
        User tAdminUser = TestDataFactory.createAdminUser(True);
        system.runAs(tAdminUser) {
            Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
            Map<String, String> personAccountFieldValues = new Map<String, String>{
                    'Market__c' => market
            };
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName',
                    recordTypeId, personAccountFieldValues, True);
            Map<String, String> oppData = new Map<String, String>();
            oppData.put('Market__c', market);
            oppData.put('StageName', 'Booking');
            oppData.put('CloseDate', String.valueOf(System.today().addDays(365)));
            Opportunity opp = TestDataFactory.createOpportunityForAccount(newAccount.Id,
                    'TestOpportunityforAccount', oppData, true);
        }
    }

    static testMethod void openPoseidonToCreateQuoteTest() {
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{
                tAdminUser.Id
        }, true, false);
        system.runAs(tAdminUser) {
            Test.startTest();
            List<Opportunity> listOpp = new List<Opportunity>();
            Opportunity Oppo1 = new Opportunity();
            Oppo1.Name = 'Test';
            Oppo1.StageName = 'Booking';
            Oppo1.CloseDate = Date.valueOf('2017-01-01');
            listOpp.add(Oppo1);
            insert listOpp;
            List<Account> AccountList = [
                    select id, FirstName,LastName,PersonMailingCity,PersonMailingCountry,PersonMailingPostalCode,
                            PersonMailingStreet, RecalculateRanking__c, PersonEmail,Email2__c,PersonHomePhone,PersonMobilePhone,
                            PersonOtherPhone,PersonBirthdate,Market__c,Region__c,
                            HasBooking__c
                    from Account
                    limit 1
            ];
            Account accountRecord = new Account();
            Lead leadRecord = new Lead();
            CreatePriceQuoteController objOppClass = new CreatePriceQuoteController(new ApexPages.StandardController(Oppo1));
            Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([select id,StageName,Name,CloseDate from Opportunity limit 1]);
            objOppClass.returnvalue = 'None';
            objOppClass.RecordId = string.valueOf(AccountList[0].Id);
            system.assertEquals('None', objOppClass.returnvalue);
            objOppClass.openPoseidonToCreateQuote();
            Set<Id> recordIdSet = new Set<Id>();
            Id OppId = Id.valueOf(objOppClass.RecordId);
            recordIdSet.add(OppId);
            List<Task> objTaskList = TasksSelector.getSPQTasksByTaskId(recordIdSet, system.label.SPQTask);
            Id recordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(system.label.SPQTask).getRecordTypeId();
            Task newTask = new Task();
            newTask.WhatId = Oppo1.Id;
            newTask.Program__c = 'ILS';
            newTask.FollowUpDate__c = Datetime.now();
            system.debug('followup>>>>' + newTask.FollowUpDate__c);
            newTask.ActivityDate = Datetime.now().Date();
            system.debug('ActivityDate>>>>' + newTask.ActivityDate);
            newTask.ActivityDateTime__c = Datetime.now();
            newTask.recordtypeid = recordTypeId;
            newTask.Status = 'Open';
            newTask.Type = 'Call';
            insert newTask;
            System.debug('newTask after' + newTask);
            Test.stopTest();
            Map<Id, Account> accMap = new Map<Id, Account>();
            system.assertEquals(1, AccountList.size());
            for (Account a : AccountList) {
                accMap.put(a.Id, a);
            }
            CreatePriceQuoteController.AccountfieldsForPriceQuote(accountRecord);
            CreatePriceQuoteController.LeadfieldsForPriceQuote(leadRecord);
        }
    }

    static testMethod void createSPQTaskTest() {
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{
                tAdminUser.Id
        }, true, false);
        system.runAs(tAdminUser) {
            Test.startTest();
            Opportunity Oppo1 = new Opportunity();
            Oppo1.Name = 'Test';
            Oppo1.StageName = 'Booking';
            Oppo1.CloseDate = Date.valueOf('2017-01-01');
            insert Oppo1;

            List<Task> TaskList = new List<Task>();
            Task newTask = new Task();
            newTask.WhatId = Oppo1.Id;
            newTask.FollowUpDate__c = Datetime.now();
            system.debug('followup>>>>' + newTask.FollowUpDate__c);
            newTask.ActivityDate = Datetime.now().Date();
            system.debug('ActivityDate>>>>' + newTask.ActivityDate);
            newTask.ActivityDateTime__c = Datetime.now();
            Id recordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(system.label.SPQTask).getRecordTypeId();
            newTask.recordtypeid = recordTypeId;
            newTask.Program__c = 'AY';
            newTask.Type = 'SPQ';
            insert newTask;
            system.debug('newTask>>>' + newTask);
            Test.stopTest();
            CreatePriceQuoteController objTaskClass = new CreatePriceQuoteController(new ApexPages.StandardController(newTask));
            objTaskClass.openPoseidonToCreateQuote();
        } 
    }
}