force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceEmail__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmail__c</fullName>
    <description>This field is used to store the email-address to which invoices should be send.</description>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is created for the secondary email and is replacing student email fields</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field is used to store the Parent Email in case this has been provided on EF.com</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SandboxEmailInvalidatorSandboxPostCopy.cls
/**
 * Created by britenet-patrykzak on 28/05/2018.
 */

public with sharing class SandboxEmailInvalidatorSandboxPostCopy implements SandboxPostCopy{

    public void runApexClass(SandboxContext context){
        List<String> leadEmailFieldsToInvalidate = new List<String>{'Email','Email2__c','ParentEmail__c'};
        List<String> AccountEmailFieldsToInvalidate = new List<String>{'PersonEmail','InvoiceEmail__c','Email2__c','ParentEmail__c'};

        SandboxEmailInvalidatorBatch LeadInvalidator = new SandboxEmailInvalidatorBatch(leadEmailFieldsToInvalidate,'Lead');
        SandboxEmailInvalidatorBatch AccountInvalidator = new SandboxEmailInvalidatorBatch(AccountEmailFieldsToInvalidate,'Account');

        Database.executeBatch(LeadInvalidator);
        Database.executeBatch(AccountInvalidator);
    }

}