force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/InvoiceEmail__c.field-meta.xml
<CustomField>
    <fullName>InvoiceEmail__c</fullName>
    <description>This field is used to store the email-address to which invoices should be send.</description>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is created for the secondary email and is replacing student email fields</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field is used to store the Parent Email in case this has been provided on EF.com</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SandboxEmailInvalidatorTest.cls
/**
 * Created by britenet-patrykzak on 28/05/2018.
 */

@IsTest
private class SandboxEmailInvalidatorTest {
    @isTest
    static void When_SandboxEmailInvalidatorSandboxPost_Expect_InvalidateEmailAdresses() {
        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
        System.runAs(adminUser) {

            String testEmail = 'test@gmail.pl';
            String instanceNameFromUserInfo = UserInfo.getUserName().substringAfterLast('.');

            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            Lead lead = (Lead)leadBuilder.getRecord();
            lead.Email = testEmail;
            lead.ParentEmail__c = testEmail;
            insert lead;

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account acc = (Account)pab.getRecord();
            acc.PersonEmail = testEmail;
            acc.InvoiceEmail__c = testEmail;
            acc.ParentEmail__c = testEmail;
            insert acc;

            Test.startTest();

            Test.testSandboxPostCopyScript(
                new SandboxEmailInvalidatorSandboxPostCopy(),
                UserInfo.getOrganizationId(),
                UserInfo.getOrganizationId(),
                UserInfo.getOrganizationName()
            );

            Test.stopTest();

            List<Lead> leadsList = [SELECT id,Email,Email2__c,ParentEmail__c From Lead];
            List<Account> accountsList = [SELECT id,PersonEmail,InvoiceEmail__c,Email2__c,ParentEmail__c From Account WHERE IsPersonAccount = True];

            System.assert(leadsList.size()>0);
            System.assert(accountsList.size()>0);
            System.assert(leadsList[0].Email == testEmail + '.' + instanceNameFromUserInfo);
            System.assert(leadsList[0].Email2__c == null);
            System.assert(accountsList[0].PersonEmail == testEmail + '.' + instanceNameFromUserInfo);
            System.assert(accountsList[0].Email2__c == null);
        }
    }
}