force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is created for the secondary email and is replacing student email fields</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FormSubmissionId__c.field-meta.xml
<CustomField>
    <fullName>FormSubmissionId__c</fullName>
    <description>S-8 created for mapping with the posiden fields for Lead Imports</description>
    <externalId>true</externalId>
    <label>FormSubmission ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field is used to store the Parent Email in case this has been provided on EF.com</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is used in order to display the PA Email2 on the Opp PL.
Note: To be deleted as soon as the PA component on OPP PL is functional.</description>
    <formula>Account.Email2__c</formula>
    <label>Email2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is used to display the Account Gender on the Opportunity Page Layout.
Note: To be deleted as soon as the Person Account Component on the Opportunity Page Layout is functional.</description>
    <formula>TEXT(   Account.Gender__c  )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/SPQTask.recordType-meta.xml
<RecordType>
    <fullName>SPQTask</fullName>
    <active>true</active>
    <description>Reffered for SPQ Task</description>
    <label>SPQ Task</label>
</RecordType>

force-app/main/default/globalValueSets/Gender.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Gender of customer.</description>
    <masterLabel>Gender</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CreatePriceQuoteController.cls
/**
 * Created by arjun.mohan on 3/8/2018. new change
 */

public class CreatePriceQuoteController {

    public Opportunity oppObj { get; set; }
    public Task taskObj { get; set; }
    public String PQParamJson { get; set; }
    public String RecordId { get; set; }
    public String returnvalue { get; set; }
    public String displayMessage { get; set; }
    public String PriceQuoteURL { get; set; }

    public CreatePriceQuoteController(ApexPages.StandardController controller) {

        this.displayMessage = System.label.CreateBookinDisplayMessage;
        if (controller.getRecord().getSObjectType() == Opportunity.getSObjectType()) {
            this.oppObj = (Opportunity) controller.getRecord();
            RecordId = String.ValueOf(this.oppObj.Id);
        } else if (controller.getRecord().getSObjectType() == Task.getSObjectType()) {
            taskObj = (Task) controller.getRecord();
            RecordId = String.ValueOf(this.taskObj.Id);
        } else {
            RecordId = null;
        }
        this.PriceQuoteURL = ExternalRouter.getServiceURL('OpenPriceQuote');
        this.returnvalue = openPoseidonToCreateQuote();
        if (!String.isEmpty(this.returnvalue)) {
            this.displayMessage = this.returnvalue;
        }
    }

    public String openPoseidonToCreateQuote() {

        try {
            Id OppId = Id.valueOf(this.RecordId);
            Set<Id> recordIdSet = new Set<Id>();
            recordIdSet.add(OppId);
            Set<Id> accountSet = new Set<Id>();

            Map<String, String> createPQFieldvalues = new Map<String, String>();
            Map<Id, Opportunity> opportunityMap = NULL;
            if (!String.isEmpty(this.RecordId) && Id.valueOf(this.RecordId).getSobjectType() == Opportunity.getSObjectType()) {
                OppId = Id.valueOf(this.RecordId);
                opportunityMap = OpportunitiesSelector.getActiveOpportunitiesforPQ(recordIdSet);
            } else if (!String.isEmpty(this.RecordId) && Id.valueOf(this.RecordId).getSobjectType() == Task.getSObjectType()) {
                recordIdSet.add(Id.valueOf(this.RecordId));
                List<Task> objTaskList = TasksSelector.getSPQTasksByTaskId(recordIdSet, system.label.SPQTask);
                if (objTaskList != null && objTaskList.size() > 0) {
                    recordIdSet.clear();
                    OppId = objTaskList[0].WhatId;
                    recordIdSet.add(OppId);
                    opportunityMap = OpportunitiesSelector.getActiveOpportunitiesforPQ(recordIdSet);
                } else {
                    this.returnvalue = 'Price Quotes can Be created for Non Completed Tasks and Active Opportunities only!!';
                }
            } else {
                this.returnvalue = 'Invalid Record to create Price Quote!!';
            }

            System.debug('opportunityMap ' + opportunityMap);
            if (opportunityMap != null && opportunityMap.containsKey(Id.valueOf(OppId)) && String.isEmpty(this.returnvalue)) {

                for (Schema.FieldSetMember f : SObjectType.Opportunity.FieldSets.CreatePriceQuote.getFields()) {
                    if (!String.isEmpty(String.ValueOf(opportunityMap.get(Id.valueOf(OppId)).get(f.getFieldPath())))) {
                        createPQFieldvalues.put(f.getFieldPath(),
                                String.ValueOf(opportunityMap.get(Id.valueOf(OppId)).get(f.getFieldPath())));
                    } else if (f.getFieldPath() != 'Email2__c' && f.getFieldPath() != 'Gender__c') {
                       
                        this.returnvalue = (!String.isEmpty(this.returnvalue)) ? this.returnvalue : ' ' + Schema.getGlobalDescribe().get('Opportunity').getDescribe().fields.getMap().get(f.getFieldPath()).getDescribe().getLabel() + ' ,';
                    }
                }
                System.debug('this.returnvalue ' + this.returnvalue);
                if (String.isEmpty(this.returnvalue)) {
                    accountSet.add(opportunityMap.get(Id.valueOf(OppId)).accountId);
                    map<Id, Account> accountMap = AccountsSelector.getAccountDetailsbasedonAccountId(accountSet);
                    Map<String, String> accountFieldsMap = AccountfieldsForPriceQuote(accountMap.get(opportunityMap.get(Id.valueOf(OppId)).accountId));
                    createPQFieldvalues.putAll(accountFieldsMap);
                    Map<Id, Lead> oppLeadMap = LeadsSelector.getLeadByConvertedOpportunityId(recordIdSet);
                    System.debug('this.oppLeadMap ' + oppLeadMap);
                    if (oppLeadMap.containsKey(Id.valueOf(OppId))) {
                        Map<String, String> leadFieldvalues = LeadfieldsForPriceQuote(oppLeadMap.get(Id.valueOf(OppId)));
                        createPQFieldvalues.putAll(leadFieldvalues);
                    }
                    createPQFieldvalues.put('Environment', (ExternalRouter.getOrganizationDetails().IsSandbox) ? 'QA' : 'LIVE');
                    String JSONValue = JSON.serialize(createPQFieldvalues);
                    this.PQParamJson = JSONValue;
                    System.debug('Before Opening Pos JOSN is ' + this.PQParamJson);
                    return '';
                } else {
                    return returnvalue.substringBeforeLast(',');
                }
            } else {
                System.debug('In Last Else Loop ' + this.returnvalue);
                return this.returnvalue;
            }
        } catch (Exception ex) {
            Id recID = Id.valueOf(this.RecordId);
            ExceptionHandler.errorLogAsync(ex.getMessage(), ex.getStackTraceString(),
                    'CreatePriceQuoteController', 'openPoseidonToCreateQuote', null);
            throw new AuraHandledException(ex.getMessage());
        }
    }

    public static Map<String, String> AccountfieldsForPriceQuote(Account accountRecord) {
        Map<String, String> accountFieldvalues = new Map<String, String>();
        accountFieldvalues.put('ParentEmail__c', String.ValueOf(accountRecord.get('ParentEmail__c')));
        accountFieldvalues.put('firstname', String.ValueOf(accountRecord.get('firstname')));
        accountFieldvalues.put('lastname', String.ValueOf(accountRecord.get('lastname')));
        return accountFieldvalues;
    }

    public static Map<String, String> LeadfieldsForPriceQuote(Lead leadRecord) {
        Map<String, String> leadFieldvalues = new Map<String, String>();
        leadFieldvalues.put('FormSubmissionId__c', String.ValueOf(leadRecord.get('FormSubmissionId__c')));
        return leadFieldvalues;
    }

}