force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>this field is for the secondary email and replacing student email 2 field</description>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstNameEn__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEn__c</fullName>
    <description>This field will show the English translation of First Name.</description>
    <label>First Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastNameEn__c.field-meta.xml
<CustomField>
    <fullName>LastNameEn__c</fullName>
    <description>This field will show the English translation of Last Name.</description>
    <label>Last Name En</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ParentEmail__c.field-meta.xml
<CustomField>
    <fullName>ParentEmail__c</fullName>
    <description>This field would be pre-populated if the parent email is entered during parents creation.</description>
    <label>Parent Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>PassportExpiryDate__c</fullName>
    <description>Option to enter the passport expiry date. This field would be a calendar control.</description>
    <label>Passport Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportIssueDate__c.field-meta.xml
<CustomField>
    <fullName>PassportIssueDate__c</fullName>
    <description>Option to enter the passport issue date. This field would be a calendar control.</description>
    <label>Passport Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <description>Option to enter passport number of the Account.</description>
    <label>Passport Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PassportType__c.field-meta.xml
<CustomField>
    <fullName>PassportType__c</fullName>
    <description>This field is a dropdown and the values are based on the passport types.</description>
    <label>Passport Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentino</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>BNO</fullName>
            </value>
            <value>
                <fullName>Brazilian Passport</fullName>
            </value>
            <value>
                <fullName>Canadian</fullName>
            </value>
            <value>
                <fullName>China Travel card</fullName>
            </value>
            <value>
                <fullName>Chinese Passport</fullName>
            </value>
            <value>
                <fullName>Diplomatic</fullName>
            </value>
            <value>
                <fullName>European Passport</fullName>
            </value>
            <value>
                <fullName>Europeo</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Greek ID</fullName>
            </value>
            <value>
                <fullName>Greek Passport</fullName>
            </value>
            <value>
                <fullName>HKSAR</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Macau SAR</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>National ID Card</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Ordinary</fullName>
            </value>
            <value>
                <fullName>Philippine</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>PRC</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
            <value>
                <fullName>Taiwanese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PersonalID__c.field-meta.xml
<CustomField>
    <fullName>PersonalID__c</fullName>
    <description>Option to enter the ID number of the Account.</description>
    <label>National ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>Please enter the Version of the Brochure.</description>
    <label>Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
            </value>
            <value>
                <fullName>V2</fullName>
            </value>
            <value>
                <fullName>V3</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Please enter the Year of the Brochure.</description>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>This field is used in order to display the PA Email2 on the Opp PL.
Note: To be deleted as soon as the PA component on OPP PL is functional.</description>
    <formula>Account.Email2__c</formula>
    <label>Email2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is used to display the Account Gender on the Opportunity Page Layout.
Note: To be deleted as soon as the Person Account Component on the Opportunity Page Layout is functional.</description>
    <formula>TEXT(   Account.Gender__c  )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>This field is used to display the PA Nationality on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>TEXT( Account.Nationality__c )</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>This field is used to display the PA Nickname on the Opp PL.
Note: To be removed as soon as the the PA component on Opp PL is functional.</description>
    <formula>Account.Nickname__c</formula>
    <label>Nickname</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>LSP</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>LS</fullName>
        <isActive>false</isActive>
        <label>LS</label>
    </customValue>
    <customValue>
        <fullName>HSY</fullName>
        <isActive>false</isActive>
        <label>HSY</label>
    </customValue>
    <masterLabel>Product</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/BindSobjectTest.cls
@isTest
public class BindSobjectTest {
	public static String market = 'DEB';
    public static String salesOffice1 = 'DEB';
    public static final String testOpportunityName = 'TestOpportunityRecord';
    
    @testSetup	
    static void testDataSetup(){
        Test.startTest();
        //get system admin profile
        Profile SystemAdminProfile = TestDataFactory.getProfile('System Administrator', true);
        //insert User
        User tAdminUser = TestDataFactory.createAdminUser(True);
        //TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        system.runAs(tAdminUser) {
            
            
            Map<String, String> markets = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Market__c');
            List<String> products = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Product__c').values();
            List<String> salesOffices = FieldUtilityClass.getFieldDependencies('Opportunity', 'Market__c', 'SalesOffice__c').get(markets.values()[0]);
            List<String> Programs = FieldUtilityClass.getFieldDependencies('Opportunity', 'Market__c', 'Program__c').get(markets.values()[0]);
            Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;

            Map<String, String> personAccountFieldValues = new Map<String, String>{
                    'Market__c' => market
            };
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, True);
			string dateValue = string.valueof(System.today());
            Map<String, String> opportunityFieldValues = new Map<String, String>{
                    'Market__c' => Market,
                    'Product__c' => products[0],
                    'SalesOffice__c' =>salesOffice1,
                    'Program__c' => programs[0],
                    'StageName' => 'Open',
                    'Closedate' => dateValue
            };
            Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(newAccount.id, testOpportunityName, opportunityFieldValues, True);
            
            //create price list
            string priceListMarketCode = SObjectType.Apttus_Config2__PriceList__c.Fields.Market__c.PicklistValues[0].getValue();
            string programCode = SObjectType.Apttus_Config2__PriceList__c.Fields.Program__c.PicklistValues[0].getValue();
            string priceListCurrencyCode = SObjectType.Apttus_Config2__PriceList__c.Fields.CurrencyIsoCode.PicklistValues[0].getValue();
            Apttus_Config2__PriceList__c priceList = APTS_TestDataUtility.createPriceList('APTPS TST PriceList 1', true, 'V0', '2017', priceListMarketCode, programCode, priceListCurrencyCode);
 			
          
            //insert Proposal
            Apttus_Proposal__Proposal__c TestProp = APTS_TestDataUtility.createProposal('TestProposal', newOpportunityPersonAccount.Id, 'EUR', newAccount.Id,'Proposal',priceList.id);
            TestProp.Apttus_Proposal__Primary__c=true;
            TestProp.Apttus_Proposal__Approval_Stage__c='None';           
    
        }
    }
    
    @isTest 
    static void dataBindTest() {
        Id currentrecord;
        Test.startTest();
        List<Apttus_Proposal__Proposal__c> proposalListQuery = [SELECT Id,Name FROM Apttus_Proposal__Proposal__c];
        List<Account> AccountListQuery = [SELECT Id,Name FROM Account];
        List<Opportunity> OpportunityListQuery = [SELECT Id,Name FROM Opportunity];
        List<Apttus_Config2__PriceList__c> PriceListQuery = [SELECT Id,Name FROM Apttus_Config2__PriceList__c];
        system.assertEquals(1, proposalListQuery.size());
        //BindSobject bindobj = new BindSobject();
        try{
        BindSobject.dataBind(proposalListQuery[0].id);
        BindSobject.dataBind(null);
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'BindSobject', 'dataBind', currentrecord);
            System.debug('Dml exception :'  +ex.getMessage());
        }
        // BindSobject.createRecordTest(wrapperData);
        Test.stopTest();
    }
    
    @isTest
    static void createRecordTest(){
        Test.startTest();
        BindSobject.SobjectBindWrapper	bso	=	new BindSobject.SobjectBindWrapper();
        bso.personAcc	=	[SELECT FirstName, MiddleName, LastName,PersonBirthdate, Gender__c, Nickname__c, PersonMailingStreet,
                             PersonMailingPostalCode, PersonMailingState, PersonMailingCountry, FirstNameEn__c, LastNameEn__c, ShippingPostalCode,
                             ShippingCity, ShippingState, ShippingStreet, Nationality__c, PersonEmail, Email2__c, ParentEmail__c, PersonHomePhone,
                             PersonMobilePhone, PersonOtherPhone, PersonalID__c, PassportType__c, PassportNumber__c, PassportIssueDate__c,
               				 PassportExpiryDate__c
                             FROM Account][0];
        bso.opp				=	[SELECT SalesOffice__c, Owner.Name FROM Opportunity][0];
        bso.PriceList		=	[SELECT Year__c, Version__c FROM Apttus_Config2__PriceList__c][0];
        bso.Quote			=	[SELECT CurrencyIsoCode FROM Apttus_Proposal__Proposal__c][0];
        bso.age				=	2.8;
        
        //String	jsonString	=	JSON.stringify(bso);
        String	jsonString		=	JSON.serialize(bso);
        system.debug('the json'+jsonString);
        BindSobject.createRecord(jsonString,true,bso.Quote.id);
        BindSobject.GetSalesOffice();
        BindSobject.GetGender();
        BindSobject.GetBookingType();
        BindSobject.GetBookingChannel();
        BindSobject.GetNationality();
        BindSobject.GetPassportType();
       // BindSobject.GetStateValues();
        BindSobject.GetCurrency();
        Account accAssert = [select id, firstname from account][0];
        opportunity oppAssert =	[SELECT SalesOffice__c, Owner.Name FROM Opportunity][0];
        Apttus_Config2__PriceList__c PLAssert =	[SELECT Year__c, Version__c FROM Apttus_Config2__PriceList__c][0];
        Apttus_Proposal__Proposal__c QuoAssert = [SELECT CurrencyIsoCode FROM Apttus_Proposal__Proposal__c][0];
        system.assertEquals(accAssert.firstname, bso.personAcc.firstname);
        system.assertEquals(oppAssert.SalesOffice__c, bso.opp.SalesOffice__c);
        system.assertEquals(PLAssert.Version__c, bso.PriceList.Version__c);
        system.assertEquals(QuoAssert.CurrencyIsoCode, bso.Quote.CurrencyIsoCode);
        //test.setMock(BindSobject.SobjectBindWrapper.class, jsonString);
        //test.setMock(HttpCalloutMock.class, jsonString);
        Test.stopTest();
    }
    
     @isTest
    static void failureRecordTest(){
         Test.startTest();
        BindSobject.SobjectBindWrapper	bso	=	new BindSobject.SobjectBindWrapper();
        bso.personAcc	=	[SELECT FirstName, MiddleName, LastName,PersonBirthdate, Gender__c, Nickname__c, PersonMailingStreet,
                             PersonMailingPostalCode, PersonMailingState, PersonMailingCountry, FirstNameEn__c, LastNameEn__c, ShippingPostalCode,
                             ShippingCity, ShippingState, ShippingStreet, Nationality__c, PersonEmail, Email2__c, ParentEmail__c, PersonHomePhone,
                             PersonMobilePhone, PersonOtherPhone, PersonalID__c, PassportType__c, PassportNumber__c, PassportIssueDate__c,
                PassportExpiryDate__c
                             FROM Account][0];
        bso.opp				=	[SELECT SalesOffice__c, Owner.Name FROM Opportunity][0];
        bso.PriceList		=	[SELECT Year__c, Version__c FROM Apttus_Config2__PriceList__c][0];
        bso.Quote			=	[SELECT CurrencyIsoCode FROM Apttus_Proposal__Proposal__c][0];
        bso.age				=	2.8;
        
        bso.personAcc.Email2__c = 'testemail';
        bso.opp.SalesOffice__c = 'testPicklist';
        bso.PriceList.Version__c = '';
        bso.PriceList.Year__c = '';
       // update bso.PriceList;
        bso.Quote.CurrencyIsoCode	= 'test';
        
        //String	jsonString	=	JSON.stringify(bso);
        String	jsonString		=	JSON.serialize(bso);
        system.debug('the json'+jsonString);
        BindSobject.createRecord(jsonString,true,bso.Quote.id);
        BindSobject.GetSalesOffice();
        BindSobject.GetGender();
        BindSobject.GetBookingType();
        BindSobject.GetBookingChannel();
        BindSobject.GetNationality();
        BindSobject.GetPassportType();
       // BindSobject.GetCountryValues();
        //BindSobject.GetStateValues();
        BindSobject.GetCurrency();
        opportunity oppAssert =	[SELECT SalesOffice__c, Owner.Name FROM Opportunity][0];
        Apttus_Config2__PriceList__c PLAssert =	[SELECT Year__c, Version__c FROM Apttus_Config2__PriceList__c][0];
        Apttus_Proposal__Proposal__c QuoAssert = [SELECT CurrencyIsoCode FROM Apttus_Proposal__Proposal__c][0];
        system.assertNotEquals(oppAssert.SalesOffice__c, bso.opp.SalesOffice__c);
        system.assertNotEquals(PLAssert.Version__c, bso.PriceList.Version__c);
        system.assertNotEquals(QuoAssert.CurrencyIsoCode, bso.Quote.CurrencyIsoCode);
        //test.setMock(BindSobject.SobjectBindWrapper.class, jsonString);
        //test.setMock(HttpCalloutMock.class, jsonString);
        Test.stopTest();
    }
   
}