force-app/main/default/objects/Account/fields/HasBooking__c.field-meta.xml
<CustomField>
    <fullName>HasBooking__c</fullName>
    <description>This field is used to indicate if this Account has a booking linked to it in status 'BKN'</description>
    <formula>BookingsinstatusBKN__c  &lt;> 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <label>Close Main Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Had intention and money, but chose to do something else</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had intention and money, but chose to do something else (soft no, we can try next year)</fullName>
                <isActive>false</isActive>
                <label>Had intention and money, but chose to do something else (soft no, we can try next year)</label>
            </value>
            <value>
                <fullName>Had no intention (ordered by mistake, didn't understand what it was for at all)</fullName>
                <isActive>false</isActive>
                <label>Had no intention (ordered by mistake, didn't understand what it was for at all)</label>
            </value>
            <value>
                <fullName>Lost to competitor (definitely try again)</fullName>
                <isActive>false</isActive>
                <label>Lost to competitor (definitely try again)</label>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/MergeReason__c.field-meta.xml
<CustomField>
    <fullName>MergeReason__c</fullName>
    <label>Merge Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Field is used to map program from lead to a customer request.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <description>Indicated the close Reason on the Lead</description>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Chose to do something else</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Not able to contact customer</fullName>
            </value>
            <value>
                <fullName>Wrongly Imported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/fields/IsDupe__c.field-meta.xml
<CustomField>
    <fullName>IsDupe__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once it is identified as Dupe, this flag will be set for further processing</description>
    <label>Is Dupe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product to which lead belongs</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ReadyForRanking__c.field-meta.xml
<CustomField>
    <fullName>ReadyForRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the dupe check process is completed, this flag will be set</description>
    <label>Ready For Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <description>Indicates the reason for closing the Opportunity</description>
    <inlineHelpText>Indicates the reason for closing the Opportunity</inlineHelpText>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chose to do something else</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Not able to contact customer</fullName>
            </value>
            <value>
                <fullName>Wrongly Imported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FollowupDateTime__c.field-meta.xml
<CustomField>
    <fullName>FollowupDateTime__c</fullName>
    <label>Follow-Up Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created. The value is set through imports and is mapped with the value on Lead.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>LSP</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>LS</fullName>
        <isActive>false</isActive>
        <label>LS</label>
    </customValue>
    <customValue>
        <fullName>HSY</fullName>
        <isActive>false</isActive>
        <label>HSY</label>
    </customValue>
    <masterLabel>Product</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/RequestType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CBR</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
    </customValue>
    <customValue>
        <fullName>CU</fullName>
    </customValue>
    <customValue>
        <fullName>IM</fullName>
    </customValue>
    <customValue>
        <fullName>PQ</fullName>
    </customValue>
    <customValue>
        <fullName>REQ</fullName>
    </customValue>
    <customValue>
        <fullName>RES</fullName>
    </customValue>
    <customValue>
        <fullName>IR</fullName>
    </customValue>
    <customValue>
        <fullName>WI</fullName>
        <isActive>false</isActive>
        <label>WI</label>
    </customValue>
    <customValue>
        <fullName>MCR</fullName>
        <isActive>false</isActive>
        <label>MCR</label>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
        <isActive>false</isActive>
        <label>EXC</label>
    </customValue>
    <customValue>
        <fullName>CNT</fullName>
        <isActive>false</isActive>
        <label>CNT</label>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
        <isActive>false</isActive>
        <label>WV</label>
    </customValue>
    <customValue>
        <fullName>VST</fullName>
        <isActive>false</isActive>
        <label>VST</label>
    </customValue>
    <customValue>
        <fullName>TRV</fullName>
        <isActive>false</isActive>
        <label>TRV</label>
    </customValue>
    <customValue>
        <fullName>TRR</fullName>
        <isActive>false</isActive>
        <label>TRR</label>
    </customValue>
    <customValue>
        <fullName>TRM</fullName>
        <isActive>false</isActive>
        <label>TRM</label>
    </customValue>
    <customValue>
        <fullName>PST</fullName>
        <isActive>false</isActive>
        <label>PST</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <isActive>false</isActive>
        <label>TR</label>
    </customValue>
    <masterLabel>RequestType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/DCMergeHelper.cls
/**
 * Created by aditi.sharma on 7/25/2017.
 */
/*
Apex Class Name    : DCMergeHelper
Version            : 1.0
Created Date       : 7/25/2017
------------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
* Aditi Sharma                7/25/2017            This class helps in implementing business scenarios on opportunities and task after account merge
*******************************************************************************/
public without sharing class DCMergeHelper{
    public class CustomException extends Exception {}
    //************************************** DCMergePlugin Codes here ***********************************
    //This function is invoked when there is a manual merge of objects using DC (Lead to Lead or Account to Account)
    public static void OnManualMerge(String objectPrefix, Sobject masterRecord, Set < id > mergedRecordIds)
    {

        if (objectPrefix == System.Label.AccountPrefix) //001P
        {
            List<Opportunity> opps=OpportunitiesSelector.getOpportunitiesOnAccountId(masterRecord.Id);
            Account masterAccount=AccountsSelector.GetAccountOnId(masterRecord.Id);
            
            List<Opportunity> freezableOpps=OpportunityStageUpdateOnMergeAccount(masterAccount,opps);
            if (freezableOpps != null && freezableOpps.size() > 0) {
                for (Opportunity freezableOpp : freezableOpps) {
                    freezableOpp.isactive__c = false;
                    freezableOpp.StageName=label.OppStageClosedLost;
                    freezableOpp.CloseMainReason__c = 'Closed by System';
                    freezableOpp.closedate = system.today();
                }
                SObjectUnitOfWork.ExecuteUpdateOpportunities(freezableOpps);
            }

          
        }
        else if (objectPrefix == System.Label.LeadPrefix ) // "00Q"
        {
            list<Lead> retainedLeadList = new list<Lead>();
            Lead retainedLead=(Lead)masterRecord;
            retainedLead.ReadyForRanking__c=true;
            retainedLead.IsDupe__c=false;  //Reset the flag to "Fasle" when we do the Automerge.
            retainedLeadList.add(retainedLead);
            SObjectUnitOfWork.executeUpdateLeads(retainedLeadList);

        }

    }
    //This function decides what to be done with the opportunities when multiple person accounts are merged
  /*
Apex method Name    : OpportunityStageUpdateOnMergeAccount
Version    Method   : 7/25/2017
------------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
* Aditi Sharma                7/25/2017            This Method updates the opportunity Stage according to the business scenarios
*******************************************************************************/
    public static List<Opportunity> OpportunityStageUpdateOnMergeAccount(Account masterAccount,List<Opportunity> mergedOpps)
    {
        List<Opportunity> freezOpportunityList = new List<Opportunity>();
        Boolean isFound = true;
        Set<String> stageNameSet = new Set<String>();

        List<Opportunity> wonOpportuntyList = opportunitiesselector.getlstOfOpportunityByCreatedDateDesc(masterAccount);

        //collect opportunity stages
        for(Opportunity opp : mergedOpps) {
            stageNameSet.add(opp.stageName);

        }
        //Won opportunity
        //please do not add any if block inside this. It has been followed as per the order
        if(stageNameSet.contains(System.Label.OpportunityBookingStage)) {
            for (Opportunity opp : wonOpportuntyList) {
                if (opp.StageName == Label.OpportunityBookingStage && isFound) {
                    isFound = false;
                    continue;
                }
                freezOpportunityList.add(opp);
            }
        }
        
        //Followup  opportunity
        else if(stageNameSet.contains(System.Label.LeadStageFollowup)) {
            list<opportunity> opportunityFollowUpList = new list<opportunity>();
            opportunityFollowUpList = opportunitiesselector.getLstOfFollowupOpportunity(mergedOpps);

            for (Opportunity opp : mergedOpps) {

                if(opportunityFollowUpList.size()>1){
                    if (opp.stageName == System.Label.LeadStageFollowup && opp.FollowupDateTime__c >= system.today() && isFound) {
                        isFound = false;
                        continue;
                }
                }
                else{
                    if (opp.stageName == System.Label.LeadStageFollowup && isFound) {

                        isFound = false;
                        continue;
                      }

                }
                freezOpportunityList.add(opp);
            }
        }
        //TBC

        else if(stageNameSet.contains(System.Label.LeadStageTBC)) {
            mergedOpps = opportunitiesselector.getLstOpportunityOrderByCrtdDateASC(mergedOpps);
            for (Opportunity opp : mergedOpps) {
                if (opp.stageName == System.Label.LeadStageTBC && isFound) {
                    isFound = false;
                    continue;
                }
                freezOpportunityList.add(opp);
            }
        }
        else if(stageNameSet.contains(System.Label.salesclosed)) {
            mergedOpps = opportunitiesselector.getLstOpportunityOrderByCrtdDateASC(mergedOpps);
            for (Opportunity opp : mergedOpps) {
                if (opp.stageName == System.Label.salesclosed && isFound) {
                    isFound = false;
                    continue;
                }
                freezOpportunityList.add(opp);
            }
        }
        else {
            //other stagename
            for (Opportunity opp : mergedOpps) {
                if (opp.FollowupDateTime__c >= system.today() && isFound) {
                    isFound = false;
                    continue;
                }
                freezOpportunityList.add(opp);
            }
        }
        return freezOpportunityList;
    }
    public static void taskMergeReasonUpdateonMergeLead(String objectPrefix, Sobject masterRecord, List < sobject > mergedRecordList){
        if (objectPrefix == System.Label.LeadPrefix)  // =="00Q"
        {
            List<Id> mergedIds = new List<Id>();
            Lead retainedLead = (Lead) masterRecord;
            for (sobject sObj : mergedRecordList) {
                mergedIds.add(sObj.Id);
            }
            List<event> mergedEvent = Eventsselector.GetEventsOnWhoIds(mergedIds);
            for (event mergedTask : mergedEvent ) {
                mergedTask.MergeReason__c = System.Label.MergeReasonManual;
            }
             SObjectUnitOfWork.executeUpdateEvents(mergedEvent);
        }
    }

    public static void ChangeProgramOrStatusForMasterREcord(String objectPrefix, Sobject masterRecord ,list<sobject> mergedRecordList) {
        List<Id> mergedIds = new List<Id>();
        for (sobject sObj : mergedRecordList) {
            mergedIds.add(sObj.Id);
        }
        //When Leads are Merged Manually
        if (objectPrefix == System.Label.LeadPrefix)  // =="00Q"
        {
            Lead retainedLead = (Lead) masterRecord;
            retainedLead =
                [select id,program__c,product__c,status,RequestType__c , createddate from lead where id=:retainedLead.id];
            lead latestobjlead =
                [select id,program__C,product__c,status,RequestType__c, createddate from lead where id in:mergedIds
                    order by createddate desc limit 1];

            if(retainedLead.createddate > latestobjlead.createddate)
            {
                latestobjlead = retainedLead;
            }
            //If the retained Lead is in closed status change the status to open and get the program from the latest activity
            if(!(retainedLead.status=='open')){
                retainedLead.status='open';
                retainedLead.program__c = latestobjlead.program__c;
            }
            // If the latest activity is RES or the retained program is multi change the program to the latest activity
            else if(latestobjlead.RequestType__c == 'RES' || retainedLead.program__c=='MULTI'){
                  retainedLead.program__c=latestobjlead.program__c;
            }
            update retainedLead;
        }

    }
    public static void changeProgramOnOpportunityForPersonAccountMerge(String objectPrefix, Sobject masterRecord ,set<id> mergedRecordList){
        if(masterRecord.getSObjectType() == account.getSObjectType()){
            Account retainedAccount = (account) masterRecord;
            retainedAccount = [Select PersonContactId From Account Where Id = :retainedAccount.id];
            opportunity ActiveOpportunity = [select id,program__c,stagename,createddate from opportunity where accountid=:retainedAccount.id and isactive__c=true limit 1];
             List<Event> CustomerRequestActivityList = [select id,program__c,type from event where whoid=:retainedAccount.PersonContactId order by createddate desc limit 2];
            If(!(ActiveOpportunity.stageName == label.OpportunityBookingStage) && CustomerRequestActivityList.size()>0 && CustomerRequestActivityList[0].type == 'RES'){
                ActiveOpportunity.Program__c = CustomerRequestActivityList[0].program__c;
            }
             If(ActiveOpportunity.Program__c == 'MULTI')
            {
                if(CustomerRequestActivityList.size()>0 && CustomerRequestActivityList[0].Program__c != 'MULTI'){
                    ActiveOpportunity.Program__c = CustomerRequestActivityList[0].Program__c;
                }else{
                    ActiveOpportunity.Program__c = CustomerRequestActivityList.size()>1?CustomerRequestActivityList[1].Program__c:ActiveOpportunity.Program__c;
                }
            }
            update ActiveOpportunity;
        }
    }
        public static void validationForHasBookingAccountMerge(String objectPrefix, Sobject masterRecord ,list<sobject> mergedRecordList){
            List<Id> mergedIds = new List<Id>();
            integer i=0;
            integer j=0;
            for (sobject sObj : mergedRecordList) {
                mergedIds.add(sObj.Id);
            }            
            if(masterRecord.getSObjectType() == account.getSObjectType()){
                boolean hasBooking = false;
                Account retainedAccount = (account) masterRecord;
                retainedAccount = [select id,HasBooking__c from account where id=:retainedAccount.id];
                lIST<Account>  LatestmergedAccount = [select id,HasBooking__c from account where id in:mergedIds];
                FOR(account objAccount: LatestmergedAccount){
                    if(objAccount.HasBooking__c){
                       j=j+1;
                    }
                }
                i= retainedAccount.HasBooking__c?1:0;
                if(i+j>=2){
                    throw new CustomException('Customers with Bookings are not allowed to merge. Please contact Poseidon support to help you with this case');
                }
            }
        }



    }