force-app/main/default/objects/Account/fields/HasHappyCallTask__c.field-meta.xml
<CustomField>
    <fullName>HasHappyCallTask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Happy Call Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Used to accept bookings data from Poseidon</description>
    <!-- <externalSharingModel>ControlledByParent</externalSharingModel> -->
    <label>Booking</label>
    <nameField>
        <label>Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field gives the account information of the related Booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/MainSalesResponsible__c.field-meta.xml
<CustomField>
    <fullName>MainSalesResponsible__c</fullName>
    <description>Used to display the name of the person creating the booking</description>
    <label>Main Sales Responsible</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/MaxEndDate__c.field-meta.xml
<CustomField>
    <fullName>MaxEndDate__c</fullName>
    <description>Used to display the  maximum end date of all active courses in the booking</description>
    <label>Max End Date</label>
    <type>Date</type>
</CustomField>

force-app++/main/default/objects/Booking__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field would refer to the Opportunity ID from Opportunity Object</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Used to display the Program of the booking</description>
    <label>Program</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to display the status of the booking</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BKN</fullName>
                <label>Booking</label>
            </value>
            <value>
                <fullName>CAX</fullName>
            </value>
            <value>
                <fullName>ERR</fullName>
                <label>Error</label>
            </value>  
            <value>
                <fullName>PRE</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>STP</fullName>
                <label>Sent To Poseidon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/HCCTaskCreatorBatchTest.cls
/**************************************************************************************
Apex Class Name    : HCCTaskCreatorBatchTest
Version            : 1.0
Created Date       : March 26 2018
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Osiecki A                  22/03/2018              Original Version
*******************************************************************************/

@IsTest
private class HCCTaskCreatorBatchTest{

    Static Id SystemCallTaskRecordTypeId =
            RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get(Label.SystemCallTaskRecordTypeDeveloperName).Id;

    static testMethod void When_BookingMaxEndDateIsPast_Expect_CreatingATask(){

        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
        System.runAs(adminUser){

            TestDataFactory.PersonAccountBuilder pab = new TestDataFactory.PersonAccountBuilder();
            Account accPerson = (Account)pab.build().save().getRecord();

            TestDataFactory.OpportunityBuilder opportunityBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity testOpportunity = (Opportunity)opportunityBuilder.getRecord();
            testOpportunity.IsActive__c = true;
            testOpportunity.AccountId = accPerson.Id;
            testOpportunity.Market__c = 'ARB';
            testOpportunity.Program__c = 'AY';
            insert testOpportunity;

            Booking__c book = new Booking__c(
                    AccountId__c = accPerson.Id,
                    OpportunityId__c = testOpportunity.Id,
                    MaxEndDate__c = Date.today().addDays(-1),
                    Status__c = 'BKN',
                    MainSalesResponsible__c = adminUser.Id,
                    Program__c = 'AY'
            );
            insert book;

            testOpportunity.StageName = 'Closed Won';
            update testOpportunity;
        }
        Test.startTest();
        HCCTaskCreatorBatch tcb = new HCCTaskCreatorBatch();
        Id batchId = Database.executeBatch(tcb);
        Test.stopTest();

        Task createdTask =[
                SELECT Id, WhatId, RecordTypeId, NextCallType__c, ActivityDate, FollowUpDate__c, Subject, OwnerId
                FROM Task
                LIMIT 1
        ];
        Account account =[
                SELECT Id, HasHappyCallTask__c
                FROM Account
                LIMIT 1
        ];

        Booking__c booking =[
                SELECT Id, MainSalesResponsible__c
                FROM Booking__c
                LIMIT 1
        ];

        System.assertEquals(1,[SELECT Count() FROM Task]);
        System.assertEquals(account.Id,createdTask.WhatId);
        System.assert(account.HasHappyCallTask__c);
        System.assertEquals(SystemCallTaskRecordTypeId,createdTask.RecordTypeId);
        System.assertEquals(Label.HCC_Next_Call_Type,createdTask.NextCallType__c);
        System.assertEquals(Date.today(),createdTask.ActivityDate);
        System.assertEquals(Date.today(),createdTask.FollowUpDate__c);
        System.assertEquals('Happy Call - AY',createdTask.Subject);
        System.assertEquals(booking.MainSalesResponsible__c,createdTask.OwnerId);
    }

    static testMethod void When_MultipleBookingsMaxEndDateIsPast_Expect_CreatingATasks(){

        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
        System.runAs(adminUser){

            Integer numberOfRecords = 3;
            Account[] accounts = new Account[]{};
            Opportunity[] opportunities = new Opportunity[]{};
            List<Booking__c> bookings = new List<Booking__c>();

            TestDataFactory.OpportunityBuilder oppBuilder = new TestDataFactory.OpportunityBuilder();
            for(Integer i = 0; i<numberOfRecords; i++){

                Opportunity opp = new Opportunity();
                opp = (Opportunity)oppBuilder.withPersonAccount().getRecord();
                opp.IsActive__c = true;
                opp.Market__c = 'ARB';
                opp.Program__c = 'AY';
                opportunities.add(opp);
                accounts.add(oppBuilder.getAccount());
                oppBuilder.build();
            }
            insert accounts;

            for(Integer i = 0; i<numberOfRecords; i++){
                opportunities[i].AccountId = accounts[i].Id;
            }
            insert opportunities;

            for(Opportunity opportunity : opportunities){
                Booking__c book = new Booking__c(
                        AccountId__c = opportunity.AccountId,
                        OpportunityId__c = opportunity.Id,
                        MaxEndDate__c = Date.today().addDays(-1),
                        Status__c = 'BKN',
                        MainSalesResponsible__c = adminUser.Id,
                        Program__c = 'AY'
                );
                bookings.add(book);
            }
            insert bookings;

            for(Opportunity opportunity : opportunities){
                opportunity.StageName = 'Closed Won';
            }
            update opportunities;

            Test.startTest();
            HCCTaskCreatorBatch tcb = new HCCTaskCreatorBatch();
            Id batchId = Database.executeBatch(tcb);
            Test.stopTest();

            for(List<Task> tasks :[
                    SELECT Id, RecordTypeId, NextCallType__c, ActivityDate, FollowUpDate__c, Subject, OwnerId
                    FROM Task])
            {
                for(Task task : tasks){
                    System.assertEquals(SystemCallTaskRecordTypeId, task.RecordTypeId);
                    System.assertEquals(Label.HCC_Next_Call_Type, task.NextCallType__c);
                    System.assertEquals(Date.today(), task.ActivityDate);
                    System.assertEquals(Date.today(), task.FollowUpDate__c);
                    System.assertEquals('Happy Call - AY', task.Subject);
                }
            }
        }
    }
}