force-app/main/default/objects/Account/fields/InvalidEmail__c.field-meta.xml
<CustomField>
    <fullName>InvalidEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If primary email is invalid</description>
    <label>Invalid Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <!--<defaultValue>$User.TF_Default_Language__c</defaultValue>-->
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Used to accept bookings data from Poseidon</description>
    <!-- <externalSharingModel>ControlledByParent</externalSharingModel> -->
    <label>Booking</label>
    <nameField>
        <label>Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field gives the account information of the related Booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app++/main/default/objects/Booking__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field would refer to the Opportunity ID from Opportunity Object</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Used to display the product of the booking</description>
    <label>Product</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Used to display the Program of the booking</description>
    <label>Program</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>Used to display the Sales Office to which the booking belongs.</description>
    <label>Sales Office</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/InvalidEmail__c.field-meta.xml
<CustomField>
    <fullName>InvalidEmail__c</fullName>
    <description>This field is used to display the PA Invalid Email on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>Account.InvalidEmail__c</formula>
    <label>Invalid Email</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Label</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Label does not belong to same market as Opportunity</errorMessage>
        <filterItems>
            <field>APXTConga4__Conga_Template__c.APXTConga4__Template_Type__c</field>
            <operation>equals</operation>
            <value>Label</value>
        </filterItems>
        <filterItems>
            <field>$Source.Market__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notContain</operation>
            <value>Integration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipLabel>Opportunities (Label)</relationshipLabel>
    <relationshipName>LabelOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>This field is used to display the PA Language on the Opportunity PL.
Note: To be removed as soon as the PA component on Opportunity is functional.</description>
    <formula>TEXT( Account.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Letter template selected for Opportunity</description>
    <label>Letter</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Letter does not belong to same market as Opportunity</errorMessage>
        <filterItems>
            <field>APXTConga4__Conga_Template__c.APXTConga4__Template_Type__c</field>
            <operation>equals</operation>
            <value>Letter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Market__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app++/main/default/objects/TemplateSetting__c/TemplateSetting__c.object-meta.xml
<CustomObject>
    <description>Used to define the template settings for each combination required</description>
    <label>Template Setting</label>
    <nameField>
        <label>Template Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateSetting__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is to define if a setting is active or not.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TemplateSetting__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This should be filtered list of all the active label templates available for Market and Program.</description>
    <label>Label</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>There are no Labels available for this Market and program combination!!</errorMessage>
        <filterItems>
            <field>APXTConga4__Conga_Template__c.APXTConga4__Template_Type__c</field>
            <operation>equals</operation>
            <value>Label</value>
        </filterItems>
        <filterItems>
            <field>$Source.Market__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Program__c</valueField>
        </filterItems>
        <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipName>Template_Settings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateSetting__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TemplateSetting__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This should be filtered list of all the active letter templates available for Market and Program.</description>
    <label>Letter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>There are no Letters available for this Market and program combination!!</errorMessage>
        <filterItems>
            <field>APXTConga4__Conga_Template__c.APXTConga4__Template_Type__c</field>
            <operation>equals</operation>
            <value>Letter</value>
        </filterItems>
        <filterItems>
            <field>$Source.Market__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>APXTConga4__Conga_Template__c.Program__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>APXTConga4__Conga_Template__c</referenceTo>
    <relationshipName>Template_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateSetting__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TemplateSetting__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The user shall select the program for which he/she would like to add a setting.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>LSP</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>LS</fullName>
        <isActive>false</isActive>
        <label>LS</label>
    </customValue>
    <customValue>
        <fullName>HSY</fullName>
        <isActive>false</isActive>
        <label>HSY</label>
    </customValue>
    <masterLabel>Product</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerTest.cls
/**
 * Created by Arkadiusz Celej on 04.01.2018.
 */

@IsTest
private class AccountTriggerTest {

    private static TestDataFactory.DefaultPicklistValuesHelper picklistValuesHelper = new TestDataFactory.DefaultPicklistValuesHelper();

    @isTest
    static void whenDateOfBirthOrLanguageChangeResetLetterAndLabelOnOpportunity() {
        User adminUser = TestDataFactory.createAdminUser(true);
        System.runAs(adminUser) {
            TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id}, true, true);
            //given
            TestDataFactory.TemplateSettingBuilder templateSettingBuilder = new TestDataFactory.TemplateSettingBuilder();
            TemplateSetting__c ts = (TemplateSetting__c) templateSettingBuilder.getRecord();
            ts.Market__c = picklistValuesHelper.market;
            ts.Program__c = picklistValuesHelper.program;
            ts.Language__c = picklistValuesHelper.language;
            templateSettingBuilder.withAge(10);
            templateSettingBuilder.withLetter();
            templateSettingBuilder.withLabel();
            templateSettingBuilder.save();
            TestDataFactory.OpportunityBuilder oppBuilder = new TestDataFactory.OpportunityBuilder();
            Opportunity opp = (Opportunity) oppBuilder.getRecord();
            opp.Market__c = picklistValuesHelper.market;
            opp.SalesOffice__c = picklistValuesHelper.salesOffice;
            opp.Program__c = picklistValuesHelper.program;
            opp.Product__c = picklistValuesHelper.product;
            oppBuilder.withPersonAccount();
            oppBuilder.getAccount().Language__c = picklistValuesHelper.language;
            oppBuilder.save();

            Account personAccount = oppBuilder.getAccount();
            TestDataFactory.TaskBuilder sbrTaskBuilder = new TestDataFactory.TaskBuilder();
            sbrTaskBuilder.withRecordType(TasksHelper.SBR_TASK_DEVELOPER_NAME);
            sbrTaskBuilder.setWhat(oppBuilder.getRecord().Id);
            sbrTaskBuilder.save();
            //when
            Test.startTest();
            personAccount.PersonBirthdate = System.today().addYears(-10);

            update personAccount;
            Test.stopTest();
            //then

            opp = [SELECT Id, Letter__c, Label__c FROM Opportunity WHERE Id = :oppBuilder.getRecord().Id];
            System.assertEquals(templateSettingBuilder.templateLetter.Id, opp.Letter__c, 'Invalid Letter');
            System.assertEquals(templateSettingBuilder.templateLabel.Id, opp.Label__c, 'Invalid Label');
        }
    }

    @isTest
    static void whenAccountHasInactiveOpportunityThenSkipSaveToPoseidonCall(){
        User adminUser = TestDataFactory.createAdminUser(true);
        System.runAs(adminUser) {
            TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id}, true, true);
            TestDataFactory.OpportunityBuilder ob = new TestDataFactory.OpportunityBuilder();
            ob.withPersonAccount();
            ob.setField('IsActive__c', false);
            ob.save();
            Account personAccount = ob.getAccount();

            Test.startTest();
            try {
                Booking__c book = new Booking__c(AccountId__c = personAccount.Id, OpportunityId__c = ob.getRecord().Id);
                insert book;
                personAccount.FirstName = personAccount.FirstName + 'ChangedName';
                update personAccount;
                System.assert(false);
            }catch (Exception ex){
                String message = ex.getMessage();
                System.assert(message.contains(Label.NoActiveOpportunity));
            }
            Test.stopTest();
        }
    }

    @isTest
    static void whenAccountHasActiveOpportunityThenCallSaveToPoseidon(){
        User adminUser = TestDataFactory.createAdminUser(true);
        System.runAs(adminUser) {
            TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id}, true, true);
            Test.setMock(HttpCalloutMock.class, new ExternalRouterMock());
            TestDataFactory.OpportunityBuilder ob = new TestDataFactory.OpportunityBuilder();
            ob.withPersonAccount().save();
            Account personAccount = ob.getAccount();
            Booking__c book = new Booking__c(AccountId__c = personAccount.Id, OpportunityId__c = ob.getRecord().Id);
            insert book;

            Test.startTest();
            personAccount.FirstName = personAccount.FirstName+'ChangedName';
            personAccount.PersonMailingStreet = 'NewStreet';
            personAccount.InvalidEmail__c = true;
            update personAccount;
            Test.stopTest();
        }
    }
}