force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <!--<defaultValue>$User.TF_Default_Language__c</defaultValue>-->
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <description>Indicated the close Reason on the Lead</description>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Chose to do something else</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Not able to contact customer</fullName>
            </value>
            <value>
                <fullName>Wrongly Imported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CloseMainReason__c.field-meta.xml
<CustomField>
    <fullName>CloseMainReason__c</fullName>
    <description>Indicates the reason for closing the Opportunity</description>
    <inlineHelpText>Indicates the reason for closing the Opportunity</inlineHelpText>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chose to do something else</fullName>
            </value>
            <value>
                <fullName>Finds EF offer too expensive</fullName>
            </value>
            <value>
                <fullName>Had no intention</fullName>
            </value>
            <value>
                <fullName>Has no means</fullName>
            </value>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Not able to contact customer</fullName>
            </value>
            <value>
                <fullName>Wrongly Imported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>This field is used to display the PA Language on the Opportunity PL.
Note: To be removed as soon as the PA component on Opportunity is functional.</description>
    <formula>TEXT( Account.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/SystemCallTask.recordType-meta.xml
<RecordType>
    <fullName>SystemCallTask</fullName>
    <active>true</active>
    <description>Referred for Automatic creation of Call Task</description>
    <label>System Call Task</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app++/main/default/classes/LogACallHelperTest.cls
@isTest
private class LogACallHelperTest{
    @testSetup static void setup(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        system.runAs(tAdminUser) {
            LogACallHelper obj01 = new LogACallHelper();
            LogACallHelper.allReachedItems = new Set<String>();
            LogACallHelper.allNotReachedItems = new Set<String>();
            LogACallHelper.callTypes = new Set<String>();
            LogACallHelper.emailTypes = new Set<String>();
            LogACallHelper.taskTypes = new Set<String>();
            List<String> oppMarkets = new List<String>(FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Market__c').keySet());
            List<String> accMarkets = new List<String>(FieldUtilityClass.getPickListValues(Account.getSObjectType(), 'Market__c').keySet());
            List<String> accLanguages = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Account.getSObjectType().getDescribe().getName(), 'Market__c', 'Language__c').get(accMarkets[0]).keySet());
            Map<String, String> accFieldMap = new Map<String, String>{
                    'Market__c' => accMarkets[0],
                    'Language__c' => accLanguages[0]
            };
            Account acc = TestDataFactory.createAccount('Sample Acc', accFieldMap, true);
            Map<String, String> oppFieldMap = new Map<String, String>{
                    'Market__c' => oppMarkets[0],
                    'StageName' => 'To Contact',
                    'CloseDate' => String.valueOf(Date.today())
            };
            TestDataFactory.createOpportunityForAccount(acc.Id, 'Sample Opp', oppFieldMap, true);
            List<String> leadMarkets = new List<String>(FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Market__c').keySet());
            Map<String, String> leadFieldValues = new Map<String,String>{
                    'Market__c'=>leadMarkets[0]
            };
            Lead lead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);
        }
    }

    static testMethod void testGetTaskSubType(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            LogACallHelper.getTaskSubType(Label.CallReached.toUpperCase());
            LogACallHelper.getTaskSubType(Label.SentEmail.toUpperCase());
            LogACallHelper.getTaskSubType(Label.SocialMediaSent.toUpperCase());
        }
        Test.stopTest();
    }
  static testMethod void testHandleLogAnActionForCallBack(){
      User tAdminUser = TestDataFactory.createAdminUser(True);
      TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
      Test.startTest();
      system.runAs(tAdminUser) {
          Opportunity opportunity = [SELECT Id,Market__c,OwnerId,Program__c FROM Opportunity LIMIT 1];
          List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(), 'Market__c', 'Program__c').get(opportunity.Market__c).keyset());
          Map<String, String> taskFieldMap = new Map<String, String>();
          taskFieldMap.put('SalesAction__c', Label.CallReached);
          taskFieldMap.put('ResultType__c', Label.CallBack);
          taskFieldMap.put('Program__c', programs[0]);
          taskFieldMap.put('CloseMainReason__c', '');
          taskFieldMap.put('FollowUpDate__c', String.valueOf(DateTime.now().addDays(2)));
          Task newTask = TestDataFactory.createTaskForSobject(opportunity.Id, taskFieldMap, false);
          Task systemCallTask = OpportunitiesHelper.createSystemCallTaskRecordForOpportunity(opportunity);
          insert systemCallTask;
          LogACallHelper.handleLogAnAction(opportunity.Id, newTask, DateTime.now(), programs[0]);
      }
      Test.stopTest();
  }
    static testMethod void testHandleLogAnActionForCallBackOnLead(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Lead lead = [SELECT Id,Market__c,OwnerId,Program__c FROM Lead LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Lead.getSObjectType().getDescribe().getName(), 'Market__c', 'Program__c').get(lead.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c', Label.CallReached);
            taskFieldMap.put('ResultType__c', Label.CallBack);
            taskFieldMap.put('Program__c', programs[0]);
            taskFieldMap.put('CloseMainReason__c', '');
            taskFieldMap.put('FollowUpDate__c', String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(lead.Id, taskFieldMap, false);
            //Task systemCallTask = LeadsHelper.createSystemCallTaskRecordForLead(lead);
            //insert systemCallTask;
            LogACallHelper.handleLogAnAction(lead.Id, newTask, DateTime.now(), programs[0]);
        }
        Test.stopTest();
    }
    static testMethod void testHandleLogAnActionForCallAppointment(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Opportunity opportunity = [SELECT Id,Market__c FROM Opportunity LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(), 'Market__c', 'Program__c').get(opportunity.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c', Label.CallReached);
            taskFieldMap.put('ResultType__c', Label.CallAppointment);
            taskFieldMap.put('Program__c', programs[0]);
            taskFieldMap.put('CloseMainReason__c', '');
            taskFieldMap.put('FollowUpDate__c', String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(opportunity.Id, taskFieldMap, false);
            LogACallHelper.handleLogAnAction(opportunity.Id, newTask, DateTime.now(), programs[0]);
        }
        Test.stopTest();
    }
    
    static testMethod void testHandleLogAnActionForVisit(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
             Opportunity opportunity = [SELECT Id,Market__c FROM Opportunity LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(),'Market__c','Program__c').get(opportunity.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c',Label.CallReached);
            taskFieldMap.put('ResultType__c',Label.Visit);
            taskFieldMap.put('Program__c',programs[0]);
            taskFieldMap.put('CloseMainReason__c','');
            taskFieldMap.put('FollowUpDate__c',String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(opportunity.Id,taskFieldMap,false);
            LogACallHelper.handleLogAnAction(opportunity.Id,newTask,DateTime.now(),programs[0]);
        }
        Test.stopTest();
    }

    static testMethod void testHandleLogAnActionForVisitOnLead(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Lead lead = [SELECT Id,Market__c,OwnerId,Program__c FROM Lead LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(),'Market__c','Program__c').get(lead.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c',Label.CallReached);
            taskFieldMap.put('ResultType__c',Label.Visit);
            taskFieldMap.put('Program__c',programs[0]);
            taskFieldMap.put('CloseMainReason__c','');
            taskFieldMap.put('FollowUpDate__c',String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(lead.Id,taskFieldMap,false);
            LogACallHelper.handleLogAnAction(lead.Id,newTask,DateTime.now(),programs[0]);
        }
        Test.stopTest();
    }
    
    static testMethod void testHandleLogAnActionForClose(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Opportunity opportunity = [SELECT Id,Market__c FROM Opportunity LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(), 'Market__c', 'Program__c').get(opportunity.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c', Label.CallReached);
            taskFieldMap.put('ResultType__c', Label.CloseOpp);
            taskFieldMap.put('Program__c', programs[0]);
            taskFieldMap.put('CloseMainReason__c', '');
            taskFieldMap.put('FollowUpDate__c', String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(opportunity.Id, taskFieldMap, false);
            LogACallHelper.handleLogAnAction(opportunity.Id, newTask, DateTime.now(), programs[0]);
        }
        Test.stopTest();
    }
    
    static testMethod void testHandleLogAnActionForChangeProgram(){
        User tAdminUser = TestDataFactory.createAdminUser(True);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id}, true, false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Opportunity opportunity = [SELECT Id,Market__c FROM Opportunity LIMIT 1];
            List<String> programs = new List<String>(FieldUtilityClass.getFieldDependenciesMap(Opportunity.getSObjectType().getDescribe().getName(),'Market__c','Program__c').get(opportunity.Market__c).keyset());
            Map<String, String> taskFieldMap = new Map<String, String>();
            taskFieldMap.put('SalesAction__c',Label.CallReached);
            taskFieldMap.put('ResultType__c',Label.ChangeProgram);
            taskFieldMap.put('Program__c',programs[0]);
            taskFieldMap.put('CloseMainReason__c','');
            taskFieldMap.put('FollowUpDate__c',String.valueOf(DateTime.now().addDays(2)));
            Task newTask = TestDataFactory.createTaskForSobject(opportunity.Id,taskFieldMap,false);
            LogACallHelper.handleLogAnAction(opportunity.Id,newTask,DateTime.now(),programs[0]);
        }
        Test.stopTest();
    }
}