force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <!--<defaultValue>$User.TF_Default_Language__c</defaultValue>-->
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Destination__c/Destination__c.object-meta.xml
<CustomObject>
    <description>This Object will store all the destination details for integration as well as for APTTUS</description>
    <label>Destination</label>
    <nameField>
        <label>Destination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Destinations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Destination__c/fields/GroupedLTDestinationName__c.field-meta.xml
<CustomField>
    <fullName>GroupedLTDestinationName__c</fullName>
    <description>Is used to identify the grouped destination name for LT destinations and use it in the "Preferrred Destinations" field.</description>
    <label>Grouped LT Destination Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Destination__c/fields/IsLT__c.field-meta.xml
<CustomField>
    <fullName>IsLT__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify LT destinations.</description>
    <label>IsLT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Destination__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Basically we will store English/Non English  values in this field</description>
    <label>Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CreationMethod__c.field-meta.xml
<CustomField>
    <fullName>CreationMethod__c</fullName>
    <label>Creation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enteredbyuser</fullName>
                <label>Entered By User</label>
            </value>
            <value>
                <fullName>Excel Import</fullName>
            </value>
            <value>
                <fullName>Ef.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of customer</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>Customers Nationality</description>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product to which lead belongs</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CreationMethod__c.field-meta.xml
<CustomField>
    <fullName>CreationMethod__c</fullName>
    <label>Creation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ef.com</fullName>
            </value>
            <value>
                <fullName>EnteredByUser</fullName>
                <label>Entered By User</label>
            </value>
            <value>
                <fullName>Excel Import</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is used to display the Account Gender on the Opportunity Page Layout.
Note: To be deleted as soon as the Person Account Component on the Opportunity Page Layout is functional.</description>
    <formula>TEXT(   Account.Gender__c  )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>This field is used to display the PA Language on the Opportunity PL.
Note: To be removed as soon as the PA component on Opportunity is functional.</description>
    <formula>TEXT( Account.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>This field is used to display the PA Nationality on the Opp PL.
Note: To be removed as soon as the PA component on the Opp PL is functional.</description>
    <formula>TEXT( Account.Nationality__c )</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/globalValueSets/Gender.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Gender of customer.</description>
    <masterLabel>Gender</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>LSP</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>LS</fullName>
        <isActive>false</isActive>
        <label>LS</label>
    </customValue>
    <customValue>
        <fullName>HSY</fullName>
        <isActive>false</isActive>
        <label>HSY</label>
    </customValue>
    <masterLabel>Product</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LogACallControllerTest.cls
/**
 * Created by aditi.sharma on 12/27/2017.
 */
@IsTest(seealldata=false)
private class LogACallControllerTest {
    private static String market = 'DEB';
    private static String salesOffice1 = 'DEB';
    private static String gender = 'Male';
    private static String language='DE';
    private static String nationality ='DE';
    private static String creationMethod='EnteredByUser';
    private static String openStage='Open';
    private static String salesClosedStage='Sales Closed';
    private static List<String> likelihoodToBookOptions;
    private static List<String> hearAboutUsOptions;
    private static List<String> destinations;
    private static List<String> preferredDurations;
    private static List<String> closeReasons;
    private static List<String> programs;
    private static List<String> salesActions;
    private static List<String> callResults;
    private static List<string> subActions;

    public static final String testOpportunityName = 'TestOpportunityRecord';
    public static List<LogACallTestInput> logACallTestInputs ;
    @testsetup static void setup(){
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        system.runAs(currentUser) {
            User tAdminUser = TestDataFactory.createAdminUser(True);
            Lead lead = createLeadRecord();
            Opportunity opp1 = createOpportunityRecord(openStage);
            Opportunity opp2 = createOpportunityRecord(salesClosedStage);
            Destination__c destination1 = new Destination__c();
            destination1.IsLT__c = true;
            destination1.GroupedLTDestinationName__c = 'Destination1';
            insert destination1;
            Destination__c destination2 = new Destination__c();
            destination2.IsLT__c = false;
            destination2.GroupedLTDestinationName__c = 'Destination2';
            insert destination2;
        }
    }
    public static void setupPicklistValues(Id recordId){
        LogACallController.getInitialData(recordid);
        likelihoodToBookOptions = (List<String>)JSON.deserialize(LogACallController.getLikelihoodToBookOptions(recordid),List<String>.class);
        hearAboutUsOptions = (List<String>)JSON.deserialize(LogACallController.getHearAboutUsOptions(recordid),List<String>.class);
        destinations = LogACallController.getDestinations(recordid);
        programs = LogACallController.getProgramsForChange(recordid);
        preferredDurations = LogACallController.getDurations(recordid,'');
        closeReasons = (List<String>)JSON.deserialize(LogACallController.getCloseReasons(recordid),List<String>.class);
        LogACallController.isCustomerReached(recordid);
        subActions = (List<String>)JSON.deserialize(LogACallController.getSubActions(),List<String>.class);
        salesActions = (List<String>)JSON.deserialize(LogACallController.getSalesActions(),List<String>.class);
        callResults =  (List<String>)JSON.deserialize(LogACallController.getCallResults(Label.CallNotReached,recordId),List<String>.class);
        logACallTestInputs  = new List<LogACallTestInput>
        {
                new LogACallTestInput(Label.CallReached,'','comments', Label.CallBack,system.now(),closeReasons[0],recordId,programs[0],system.now(),likelihoodToBookOptions[0],hearAboutUsOptions[0],'','','','',system.now())
        };
    }

    public static lead createLeadRecord(){
        Map<String, String> markets = FieldUtilityClass.getPickListValues(Lead.getSObjectType(), 'Market__c');
        List<String> Programs = FieldUtilityClass.getFieldDependencies('Lead', 'Market__c', 'Program__c').get(markets.values()[0]);
        Map<String, String> leadFieldValues = new Map<String,String>{
                    'Market__c'=>market,
                    'Program__c'=>Programs[0],
                    'SalesOffice__c' =>salesOffice1,
                    'Gender__c'=>gender,
                    'Language__c'=>language,
                    'Nationality__c'=>nationality,
                    'CreationMethod__c'=>creationMethod
                };
        return TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);
    }
    public static opportunity createOpportunityRecord(String stageName){
        Map<String, String> markets = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Market__c');
        List<String> products = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'Product__c').values();
        List<String> salesOffices = FieldUtilityClass.getFieldDependencies('Opportunity', 'Market__c', 'SalesOffice__c').get(markets.values()[0]);
        List<String> Programs = FieldUtilityClass.getFieldDependencies('Opportunity', 'Market__c', 'Program__c').get(markets.values()[0]);
        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;

        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => market
        };
        Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, True);

        string dateValue = string.valueof(System.today());
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => Market,
                'Product__c' => products[0],
                'SalesOffice__c' =>salesOffice1,
                'Program__c' => programs[0],
                'StageName' => stageName,
                'Closedate' => dateValue
        };
        Opportunity opp =  TestDataFactory.createOpportunityForAccount(newAccount.id, testOpportunityName, opportunityFieldValues, True);
        return opp;
    }

    static testMethod void testSaveDataForOpportunity(){
        User tAdminUser = [SELECT Id,Name FROM User WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Opportunity opp = [Select Id FROM Opportunity WHERE StageName = 'Open' LIMIT 1];
            Map<String, String> stages = FieldUtilityClass.getPickListValues(Opportunity.getSObjectType(), 'StageName');
            opp.StageName = stages.values()[0];
            update opp;
            setupPicklistValues(opp.Id);
            for(LogACallTestInput input : logACallTestInputs){
                LogACallController.saveData(
                        input.CallAction,
                        input.SubAction,
                        input.Comments,
                        input.CallResult,
                        input.ActionDateTime,
                        input.CloseReason,
                        opp.Id,
                        input.Program,
                        input.VisitDatetime,
                        input.LikelihoodToBook,
                        input.HearAboutUs,
                        input.Destination,
                        input.Duration,
                        input.WhenYear,
                        input.WhenMonth,
                        input.BookOn);
            }
        }
        Test.stopTest();
    }
    static testMethod void testSaveDataForClosedOpportunity(){
        User tAdminUser = [SELECT Id,Name FROM User  WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Opportunity opp = [Select Id FROM Opportunity WHERE StageName = 'Sales Closed' LIMIT 1];
            setupPicklistValues(opp.Id);
            for(LogACallTestInput input : logACallTestInputs){
                LogACallController.saveData(
                        input.CallAction,
                        input.SubAction,
                        input.Comments,
                        input.CallResult,
                        input.ActionDateTime,
                        input.CloseReason,
                        opp.Id,
                        input.Program,
                        input.VisitDatetime,
                        input.LikelihoodToBook,
                        input.HearAboutUs,
                        input.Destination,
                        input.Duration,
                        input.WhenYear,
                        input.WhenMonth,
                        input.BookOn);
            }
        }
        Test.stopTest();
    }

    static testMethod void testSaveDataForLead(){
        User tAdminUser = [SELECT Id,Name FROM User  WHERE alias = 'admnTU' LIMIT 1];
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{tAdminUser.Id},true,false);
        Test.startTest();
        system.runAs(tAdminUser) {
            Lead lead = [Select Id FROM Lead LIMIT 1];
            setupPicklistValues(lead.Id);
            for(LogACallTestInput input : logACallTestInputs){
                LogACallController.saveData(
                        input.CallAction,
                        input.SubAction,
                        input.Comments,
                        input.CallResult,
                        input.ActionDateTime,
                        input.CloseReason,
                        lead.Id,
                        input.Program,
                        input.VisitDatetime,
                        input.LikelihoodToBook,
                        input.HearAboutUs,
                        input.Destination,
                        input.Duration,
                        input.WhenYear,
                        input.WhenMonth,
                        input.BookOn);
            }
        }
        Test.stopTest();
    }

    static testMethod  void testForInvalidIdForLikelihoodToBook(){
        try {
            LogACallController.getLikelihoodToBookOptions(NULL);
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForHearAboutUsOptions(){
        try {
            LogACallController.getHearAboutUsOptions(NULL);
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForGetDestinations(){
        try {
            LogACallController.getDestinations(NULL);
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForGetDurations(){
        try {
            LogACallController.getDurations(NULL,'');
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForGetProgramsForChange(){
        try {
            LogACallController.getProgramsForChange(NULL);
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForGetCloseReasons(){
        try {
            LogACallController.getCloseReasons(NULL);
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod  void testForInvalidIdForGetCallResults(){
        try {
            LogACallController.getCallResults(NULL,'');
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('System.NullPointerException: null input to JSON parser') ? true : false;
        }
    }

    static testMethod void testLogACallData(){
        LogACallData logACallData = new LogACallData(null,Date.today(),'','','','','','',True,0.0,'');
    }
}