force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IsByConversion__c.field-meta.xml
<CustomField>
    <fullName>IsByConversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to track if the record is migrated/converted from Poseidon.</description>
    <label>Is By Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/IsCAMOnly__c.field-meta.xml
<CustomField>
    <fullName>IsCAMOnly__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is to track if the request type is only CAM</description>
    <inlineHelpText></inlineHelpText>
    <label>IsCAMOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/IsDupe__c.field-meta.xml
<CustomField>
    <fullName>IsDupe__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once it is identified as Dupe, this flag will be set for further processing</description>
    <label>Is Dupe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsDupeProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsDupeProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be default false and after this record is run through dupe check then this should be set as true</description>
    <label>Is Dupe Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>this is to capture the active opportunity</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsByConversion__c.field-meta.xml
<CustomField>
    <fullName>IsByConversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this account is created a a result of lead conversion. False otherwise</description>
    <label>Is By Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadConversionBatch.cls
//This batch is for Lead Conversion
global class LeadConversionBatch implements Database.Batchable<SObject>{
    
    //properties
    global String strQuery;   
           
    //constructor
    global LeadConversionBatch(){    
        this.strQuery = 'SELECT Id,FirstName,LastName FROM Lead WHERE IsByConversion__c = False AND IsDupeProcessed__c = True AND IsCAMOnly__c = False AND Ranking__c != Null AND Market__c = \'NOO\' AND IsConverted = False AND IsDupe__c = False'; 
    	System.debug('this.strQuery' +this.strQuery);
    }
  
    //start method
    global Database.QueryLocator start(Database.BatchableContext context){    
        return Database.getQueryLocator(this.strQuery); 
    }
  
    //execute method
    global void execute(Database.BatchableContext context, List<SObject> Scope){ 
        try{   
			map<id,id> Contentnoteidmap = new map<id,id>();
            Set<Id> LeadID = new Set<Id>();
            List<Lead> LeadUpdate = new List<Lead>();
            for (Lead IdLead : (List<Lead>)Scope){
                LeadID.add(IdLead.Id);
			}
            System.debug('LeadID' +LeadID.size());
			list<ContentDocumentLink> listOfContentDocumentLink=[select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId in:LeadID];
			list<ContentDocumentLink> listOfContentDocumentLinkToUpdate = new List<ContentDocumentLink>();
			system.debug('Contentdocumentlink>>>>'+listOfContentDocumentLink.size());
			for(ContentDocumentLink objlistOfContentDocumentLink :listOfContentDocumentLink){
				Contentnoteidmap.put(objlistOfContentDocumentLink.LinkedEntityId,objlistOfContentDocumentLink.ContentDocumentId);
			}
			delete listOfContentDocumentLink;
			for(Lead objLead : (List<Lead>)Scope){
				objLead.iscamonly__c=false;
                LeadUpdate.add(objLead);
			}
			update LeadUpdate;
            system.debug('LeadUpdate'+LeadUpdate.size());
			map<id,lead> LeadMap = new map<id,lead>([select id,convertedaccountid,convertedopportunityid from lead where id in:LeadID and (convertedaccountid!=null OR convertedopportunityid!=null)]);
            if(LeadMap.size() < LeadUpdate.size())
            {
                system.debug('Failed to convert');
                SObjectException e=new SObjectException();
                e.setMessage('Convertion failed for lead');
                throw e;
            }
			//map<id,account> accountAndOppMap = new Map<id,Account>([select id,(select id from opportunity where isactive__c=true) from account ]);
			for(id objid:LeadMap.keyset()){
				system.debug('objid>>'+objid);
				system.debug('Contentnoteidmap>>'+Contentnoteidmap);   
                system.debug('after account'+LeadMap.get(objid).convertedaccountid);
				if(LeadMap.get(objid).convertedaccountid!=null){
				  ContentDocumentLink ContentDocumentLinkFirstUpdate = new ContentDocumentLink();
				system.debug('after get'+Contentnoteidmap.get(objid));
							ContentDocumentLinkFirstUpdate.ContentDocumentId = Contentnoteidmap.get(objid);
							ContentDocumentLinkFirstUpdate.LinkedEntityId = LeadMap.get(objid).convertedaccountid;
							ContentDocumentLinkFirstUpdate.ShareType = 'V';
							ContentDocumentLinkFirstUpdate.Visibility = 'AllUsers';
							listOfContentDocumentLinkToUpdate.add(ContentDocumentLinkFirstUpdate);
							ContentDocumentLink ContentDocumentLinkSecondUpdate = new ContentDocumentLink();
							ContentDocumentLinkSecondUpdate.ContentDocumentId = Contentnoteidmap.get(objid);
							ContentDocumentLinkSecondUpdate.LinkedEntityId = LeadMap.get(objid).convertedopportunityid;
							ContentDocumentLinkSecondUpdate.ShareType = 'V';
							ContentDocumentLinkSecondUpdate.Visibility = 'AllUsers';
							listOfContentDocumentLinkToUpdate.add(ContentDocumentLinkSecondUpdate);
                    system.debug('ContentDocumentLinkFirstUpdate'+ContentDocumentLinkFirstUpdate);
                    system.debug('ContentDocumentLinkSecondUpdate'+ContentDocumentLinkSecondUpdate);
			}
	}
				insert listOfContentDocumentLinkToUpdate; 
        }
        catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                   'LeadConversionBatch', 'execute', null);
        } 
    }
   
    //finish method
    global void finish(Database.BatchableContext context){    
    }
}