force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Models the quotes sent to the customers</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>The related opportunity Market</description>
    <formula>TEXT(Opportunity__r.Market__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity this quote is related to</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The Quote program</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Quote__c/fields/QuoteCreatedBy__c.field-meta.xml
<CustomField>
    <fullName>QuoteCreatedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app++/main/default/objects/Quote__c/fields/QuotePDF__c.field-meta.xml
<CustomField>
    <fullName>QuotePDF__c</fullName>
    <description>The url to retrieve the Quote PDF</description>
    <label>Quote PDF</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SentByEmail__c.field-meta.xml
<CustomField>
    <fullName>SentByEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates whether the quote has been sent via Email</description>
    <label>Sent by Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/SPQTask.recordType-meta.xml
<RecordType>
    <fullName>SPQTask</fullName>
    <active>true</active>
    <description>Reffered for SPQ Task</description>
    <label>SPQ Task</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerTest.cls
/**
 * Created by thejasvi.a on 3/19/2018.
 */
@IsTest
public class QuoteTriggerTest {
    public static String market = 'DEB';
    public static String salesOffice = 'DEB';
    public static String program = 'AY';

        static testMethod void createQuoteWithEmailSent() {
        List<Quote__c> quoteList = new List<Quote__c>();
        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Id recordTypeSPQId = RecordTypesSelector.getActiveRecTypesByDevName(Task.SObjectType).get('SPQTask').Id;

        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => 'DEB'
        };
        Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, True);
        string dateValue = string.valueof(System.today());
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => market,
                'SalesOffice__c' => salesOffice,
                'Program__c' => program,
                'StageName' => 'Open',
                'Closedate' => dateValue
        }; 
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(newAccount.id, 'testOpportunityName', opportunityFieldValues, True);

        Map<String, String> taskValues = new Map<String, String>{
                'Program__c' =>  program,
                'Type' => 'SPQ',
                'Subject' => 'SPQ Record',
                'RecordTypeId' => recordTypeSPQId
        };
        task newTask = TestDataFactory.createTaskForSobject(newOpportunityPersonAccount.Id, taskValues, TRUE);
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Quote__c quoteRec = new quote__c();
        quoteRec.Opportunity__c = newOpportunityPersonAccount.id;
        quoteRec.program__c = 'AY';
        quoterec.SentByEmail__c=TRUE;
        quoterec.QuotePDF__c='description';
        quoterec.QuoteCreatedBy__c=currentUser.Id;
        insert quoteRec;
        QuotesHelper.closeSPQTasksAndCreateNewTaskOnOpportunity(new List<Quote__c>{quoteRec});
    }

}