force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should be able to select a date only greater than or equal to today and the time.</description>
    <label>Date From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The user should not be allowed to select a date different from that entered in "Date From".</description>
    <label>Date To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/IsUP__c.field-meta.xml
<CustomField>
    <fullName>IsUP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is editable only if selected program is AY or AYP.</description>
    <label>Is UP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingCity__c.field-meta.xml
<CustomField 
   >
    <fullName>MeetingCity__c</fullName>
    <description>Displays a list of cities in the market.</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A domicile</fullName>
            </value>
            <value>
                <fullName>Aachen</fullName>
            </value>
            <value>
                <fullName>Aalborg</fullName>
            </value>
            <value>
                <fullName>Aalst</fullName>
            </value>
            <value>
                <fullName>Aarau</fullName>
            </value>
            <value>
                <fullName>Abbotsford, BC</fullName>
            </value>
            <value>
                <fullName>Åbent hus</fullName>
            </value>
            <value>
                <fullName>Åbo</fullName>
            </value>
            <value>
                <fullName>Abrantes</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Acapulco</fullName>
            </value>
            <value>
                <fullName>Adana</fullName>
            </value>
            <value>
                <fullName>Adecco</fullName>
            </value>
            <value>
                <fullName>Admont</fullName>
            </value>
            <value>
                <fullName>Adrar</fullName>
                <label>Adrar </label>
            </value>
            <value>
                <fullName>Agen</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Agropoli</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Ahwaz</fullName>
            </value>
            <value>
                <fullName>Aïn Defla</fullName>
                <label>Aïn Defla </label>
            </value>
            <value>
                <fullName>Aïn Témouchent</fullName>
                <label>Aïn Témouchent </label>
            </value>
            <value>
                <fullName>Aix en Provence</fullName>
            </value>
            <value>
                <fullName>Aix-Marseille</fullName>
            </value>
            <value>
                <fullName>Ajaccio</fullName>
            </value>
            <value>
                <fullName>Aksay</fullName>
            </value>
            <value>
                <fullName>Aktau</fullName>
            </value>
            <value>
                <fullName>Aktobe</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Alajuela</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingSize__c.field-meta.xml
<CustomField>
    <fullName>MeetingSize__c</fullName>
    <description>Indicates the total capacity for the meeting.</description>
    <label>Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/MeetingType__c.field-meta.xml
<CustomField>
    <fullName>MeetingType__c</fullName>
    <description>Type of meeting</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info Meeting - Offline</fullName>
            </value>
            <value>
                <fullName>Info Meeting - Online</fullName>
            </value>
            <value>
                <fullName>Open House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program of campaign</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <description>Returns Meeting Start date from connected Campaign record</description>
    <formula>Campaign.DateFrom__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <description>Returns Meeting End date from connected Campaign record</description>
    <formula>Campaign.DateTo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/MeetingType__c.field-meta.xml
<CustomField>
    <fullName>MeetingType__c</fullName>
    <description>Returns the Meeting type of the related Campaign</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MeetingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>This field is used to display the Campaign Program on Opportunity level.</description>
    <formula>Text(Campaign.Program__c )</formula>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsUp__c.field-meta.xml
<CustomField>
    <fullName>IsUp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether the Opportunity is for a University Preparation course.</description>
    <label>Is UP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Opportunity belongs.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MeetingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INF</fullName>
        <label>Info Meeting - Offline</label>
    </customValue>
    <customValue>
        <fullName>ONM</fullName>
        <label>Info Meeting - Online</label>
    </customValue>
    <customValue>
        <fullName>OHO</fullName>
        <label>Open House</label>
    </customValue>
    <customValue>
        <fullName>PDP</fullName>
        <label>Pre Departure</label>
    </customValue>
    <description>Type of infomeeting used on Campaign and Campaingn Member</description>
    <masterLabel>Meeting Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/InviteToCampaign.cls
public with sharing class InviteToCampaign {

    @AuraEnabled
    public static Map<String,String> getMeetingTypes() {
        try {
            return FieldUtilityClass.getPickListValues(Campaign.getSObjectType(), 'MeetingType__c');
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getMeetingTypes', null);
        }
        return null;
    }

    @AuraEnabled
    public static Map<String,String> getMeetingCity(Id recordId) {
        try {
            Map<String, Map<String, String>> meetingCity = FieldUtilityClass.getFieldDependenciesMap(Campaign.getSObjectType().getDescribe().getName(), 'Market__c', 'MeetingCity__c');
            Opportunity opp = OpportunitiesSelector.getOpportunityrecord(recordId);
            return meetingCity.get(opp.Market__c);
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getMeetingCity', null);
        }
        return null;
    }

    @AuraEnabled
    public static Map<String,String> getProgram(Id recordId) {
        try {
            Map<String, Map<String, String>> marketProgram = FieldUtilityClass.getFieldDependenciesMap(Campaign.getSObjectType().getDescribe().getName(), 'Market__c', 'Program__c');
            Opportunity opp = OpportunitiesSelector.getOpportunityRecord(recordId);
            return marketProgram.get(opp.Market__c);
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getProgram', null);
        }
        return null;
    }

    @AuraEnabled
    public static Map<String,String> getSalesOffice(Id recordId) {
        try {
            Map<String, Map<String, String>> salesOffice = FieldUtilityClass.getFieldDependenciesMap(Campaign.getSObjectType().getDescribe().getName(), 'Market__c', 'SalesOffice__c');
            Opportunity opp = OpportunitiesSelector.getOpportunityRecord(recordId);
            return salesOffice.get(opp.Market__c);
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getSalesOffice', null);
        }
        return null;
    }

    @AuraEnabled
    public static List<Campaign> getCampaigns() {
        try {
            List<campaign> campaignRecords = CampaignsSelector.getActiveFutureCampaignRecords();
            return campaignRecords;
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getCampaigns', null);
        }
        return null;
    }

    @AuraEnabled
    public static list<CampaignWrapper> getCampaignsWithFilter(String recordId, string salesOffice, string program, string meetingType, string meetingCity, datetime dateFrom, datetime dateTo) {
        try {
            String market = '';
            List<string> lstOfProgram = new List<string>();
            if (recordId != null && recordId != '') {
                Opportunity opp = OpportunitiesSelector.getOpportunityRecord(recordId);
                market = opp.Market__c;
            }

            list<string> lstOfSalesOffice = new List<string>();
            if (salesoffice != null && salesoffice != '') {
                lstOfSalesOffice = (list<string>) JSON.deserialize(salesoffice, list<string>.class);
            }

            if (program != null && program != '') {
                lstOfProgram = (list<string>) JSON.deserialize(program, list<string>.class);
            }

            list<string> lstOfMeetingType = new List<string>();
            if (meetingType != null && meetingType != '') {
                lstOfMeetingType = (list<string>) JSON.deserialize(meetingType, list<string>.class);
            }

            list<string> lstOfMeetingCity = new List<string>();
            if (meetingCity != null && meetingCity != '') {
                lstOfMeetingCity = (list<string>) JSON.deserialize(meetingCity, list<string>.class);
            }

            string query = 'Select Id, SalesOffice__c, Program__c, MeetingType__c, MeetingCity__c, DateFrom__c, DateTo__c, IsUP__c, MeetingSize__c, Name from Campaign ';
            string statusValue = 'Active';

            List<String> whereConditions = new List<String>();

            whereConditions.add('Status = :statusValue');

            if (String.isNotEmpty(market)) {
                whereConditions.add('Market__c = :market');
            }

            if (lstOfSalesOffice.size() > 0) {
                whereConditions.add('SalesOffice__c in :lstOfsalesoffice');
            }

            if (lstOfProgram.size() > 0) {
                whereConditions.add('Program__c in :lstOfprogram');
            }

            if (lstOfMeetingType.size() > 0) {
                whereConditions.add('MeetingType__c in :lstOfmeetingType');
            }

            if (lstOfMeetingCity.size() > 0) {
                whereConditions.add('MeetingCity__c in :lstOfmeetingCity');
            }

            if (datefrom != null) {
                whereConditions.add('DateFrom__c >= :datefrom');
            }

            if (dateto != null) {
                whereConditions.add('DateTo__c <= :dateto');
            }

            query += ' WHERE ' + String.join(whereConditions, ' AND ') + ' ORDER BY LastModifiedDate DESC LIMIT 100';

            System.debug('Query :' + query);
            System.debug('Sales Offices :' + lstOfSalesOffice);
            System.debug('Programs :' + lstOfProgram);
            System.debug('Meeting Types :' + lstOfMeetingType);
            System.debug('Meeting Cities :' + lstOfMeetingCity);
            List<campaign> campaignRecords = new List<campaign>();
            campaignRecords = Database.query(query);
            CampaignWrapper wrapperClassInitialise = new CampaignWrapper();
            list<CampaignWrapper> lstOfWrappers = new list<CampaignWrapper>();

            Map<Id, Integer> invitedMembersCount = new Map<Id, Integer>();
            invitedMembersCount = CampaignMembersSelector.getCampaignMemberCount(campaignRecords);

            if ((campaignRecords.size() > 0)) {
                for (campaign objCampaign : campaignRecords) {
                    CampaignWrapper initializeWrapperClass = new CampaignWrapper();
                    initializeWrapperClass.objWrapperCampaign = objCampaign;
                    integer value = invitedMembersCount.get(objCampaign.id);
                    initializeWrapperClass.InvitedCount = value;
                    lstOfWrappers.add(initializeWrapperClass);
                }
            }
            return lstOfWrappers;
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getCampaignsWithFilter', null);
        }
        return null;
    }
    
    @AuraEnabled
    public static list<CampaignWrapper> getInitialCampaignData(String recordId,  datetime datefrom) {
        try {
            String market = '';
            String program = '';
            if (recordId != null && recordId != '') {
                Opportunity opp = OpportunitiesSelector.getOpportunityRecord(recordId);
                market = opp.Market__c;
                program = opp.Program__c;
            }

            string query = 'Select Id, Name, SalesOffice__c, Program__c, MeetingType__c, MeetingCity__c, DateFrom__c, DateTo__c, IsUP__c, MeetingSize__c from Campaign ';
            string statusValue = 'Active';

            List<String> whereConditions = new List<String>();

            whereConditions.add('Status = :statusValue');

            if (String.isNotEmpty(market)) {
                whereConditions.add('Market__c = :market');
            }

            if (String.IsNotEmpty(program)) {
                whereConditions.add('Program__c = :program');
            }

            if (datefrom != null) {
                whereConditions.add('DateFrom__c >= :datefrom');
            }

            query += ' WHERE ' + String.join(whereConditions, ' AND ') + ' ORDER BY LastModifiedDate DESC LIMIT 100';

            List<Campaign> campaignRecords = new List<campaign>();
            campaignRecords = Database.query(query);
            CampaignWrapper wrapperClassInitialise = new CampaignWrapper();
            list<CampaignWrapper> lstOfWrappers = new list<CampaignWrapper>();

            Map<Id, Integer> invitedMembersCount = new Map<Id, Integer>();
            invitedMembersCount = CampaignMembersSelector.getCampaignMemberCount(campaignRecords);

            if ((campaignRecords.size() > 0)) {
                for (campaign objCampaign : campaignRecords) {
                    CampaignWrapper initializeWrapperClass = new CampaignWrapper();
                    initializeWrapperClass.objWrapperCampaign = objCampaign;
                    integer value = invitedMembersCount.get(objCampaign.id);
                    initializeWrapperClass.InvitedCount = value;
                    lstOfWrappers.add(initializeWrapperClass);
                }
            }
            return lstOfWrappers;
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getInitialCampaignData', null);
        }
        return null;
    }

    public class CampaignWrapper {
        @AuraEnabled
        public boolean isChecked = false;
        @AuraEnabled
        public Campaign objWrapperCampaign = new Campaign();
         @AuraEnabled
        public Integer invitedCount;
    }

    @AuraEnabled
    public static void AddCampaigns(string incomingCampaignList, Id OpportunityId) {
        try {
            System.Debug('Input Params : incomingCampaignList:'+incomingCampaignList+'  OppId:'+OpportunityId);
            List<CampaignMember> campaignMemberList = new List<CampaignMember>();
            list<campaign> lstOfSelectedCampaign = (list<campaign>) JSON.deserialize(incomingCampaignList, list<campaign>.class);
            Id recordId = Id.valueOf(OpportunityId);
            System.debug('RecordId:'+recordId);
            Opportunity opportunityRecord = OpportunitiesSelector.getOpportunityRecord(recordId);
            System.debug('Opp Record:'+opportunityRecord);
            //Account accountRecord = AccountSelector.getAccountonOpportunity(opportunityRecord);
            //System.debug('Account Record:'+accountRecord);
            for (Campaign campaignRecord : lstOfSelectedCampaign) {
                if (opportunityRecord.Account.PersonContactId != null) {
                    System.debug('Entered If personal Id: ' + opportunityRecord.Account.PersonContactId);
                    CampaignMember member = new CampaignMember();
                    member.ContactId = opportunityRecord.Account.PersonContactId;
                    member.CampaignId = campaignRecord.Id;
                    member.status = 'Invited';
                    campaignMemberList.add(member);
                }
            }
            insert campaignMemberList;
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'AddCampaigns', null);
        }
    }

    @AuraEnabled
    public static String getMarket(Id OpportunityId) {
        try {
            Id recordId = Id.valueOf(OpportunityId);
            Opportunity opportunityRecord = OpportunitiesSelector.getOpportunityRecord(recordId);
            string market = opportunityRecord.Market__c;
            return JSON.serialize(market);
        }
        catch (Exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(), 'InviteToCampaign', 'getMarket', null);
        }
        return null;
    }
}