force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Customer</businessProcess>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>MarkettowhichSalesOfficebelongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created. The value is set through imports and is mapped with the value on Lead.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TimeOutDate__c.field-meta.xml
<CustomField>
    <fullName>TimeOutDate__c</fullName>
    <description>This field is used to determine the Time Out Date of the Opportunity. It determines the date on which the Stage should move from Sales Closed to Closed Lost.</description>
    <label>Time Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/RequestType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CBR</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
    </customValue>
    <customValue>
        <fullName>CU</fullName>
    </customValue>
    <customValue>
        <fullName>IM</fullName>
    </customValue>
    <customValue>
        <fullName>PQ</fullName>
    </customValue>
    <customValue>
        <fullName>REQ</fullName>
    </customValue>
    <customValue>
        <fullName>RES</fullName>
    </customValue>
    <customValue>
        <fullName>IR</fullName>
    </customValue>
    <customValue>
        <fullName>WI</fullName>
        <isActive>false</isActive>
        <label>WI</label>
    </customValue>
    <customValue>
        <fullName>MCR</fullName>
        <isActive>false</isActive>
        <label>MCR</label>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
        <isActive>false</isActive>
        <label>EXC</label>
    </customValue>
    <customValue>
        <fullName>CNT</fullName>
        <isActive>false</isActive>
        <label>CNT</label>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
        <isActive>false</isActive>
        <label>WV</label>
    </customValue>
    <customValue>
        <fullName>VST</fullName>
        <isActive>false</isActive>
        <label>VST</label>
    </customValue>
    <customValue>
        <fullName>TRV</fullName>
        <isActive>false</isActive>
        <label>TRV</label>
    </customValue>
    <customValue>
        <fullName>TRR</fullName>
        <isActive>false</isActive>
        <label>TRR</label>
    </customValue>
    <customValue>
        <fullName>TRM</fullName>
        <isActive>false</isActive>
        <label>TRM</label>
    </customValue>
    <customValue>
        <fullName>PST</fullName>
        <isActive>false</isActive>
        <label>PST</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <isActive>false</isActive>
        <label>TR</label>
    </customValue>
    <masterLabel>RequestType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app++/main/default/classes/DCMergeHelperTest.cls
/**
 * Created by thejasvi.a on 3/9/2018.
 */
@istest
public class DCMergeHelperTest {

    static testMethod void onManualMerge() {
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

            Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
            Map<String, String> leadValues = new Map<String, String>{
                    'Market__c' => 'DEB',
                    'Program__c' => 'AY',
                    'SalesOffice__c' => 'DEB',
                    'Email' => 'test@ef.com'
            };
            Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', '', leadValues, TRUE);
            system.debug('leadRecord>>' + leadRecord);

            for (integer i = 0; i < 6; i++) {
                Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', '', leadValues, FALSE);
                leadList.add(leadRec);
                system.debug('list>>' + leadList);
            }
            insert leadList;

            for (lead leadRecrd : leadList) {
                leadIds.add(leadRecord.Id);
            }
            DCMergeHelper.OnManualMerge('00Q', leadRecord, leadIds);
            DCMergeHelper.validationForHasBookingAccountMerge('00Q', leadRecord, leadList);

            Map<String, String> personAccountFieldValues = new Map<String, String>{
                    'Market__c' => 'DEB'
            };
            Account accountRecord = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, TRUE);

        string dateValue = string.valueof(System.today().addDays(3));
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'SalesOffice__c' =>'DEB',
                'Program__c' => 'AY',
                'StageName' => System.Label.LeadStageWon,
                'Closedate' => dateValue,
                'TimeOutDate__c'=> dateValue

        };
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(accountRecord.id, 'testOpportunityName', opportunityFieldValues, True);


            for (integer i = 0; i < 6; i++) {
                Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName' + i, 'TestAccountFirstName' + i, recordTypeId, personAccountFieldValues, FALSE);
                accountList.add(newAccount);
                system.debug('list>>' + accountList);
            }
            insert accountList;

            for (Account accountRecrd : accountList) {
                accountIds.add(accountRecrd.Id);
            }

        Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;

            DCMergeHelper.OnManualMerge('001P', accountRecord, accountIds);
            DCMergeHelper.validationForHasBookingAccountMerge('001P', accountRecord, accountList);

            //DCMergehelper.changeProgramOnOpportunityForPersonAccountMerge('001P', accountRecord, accountIds);
            DCMergeHelper.taskMergeReasonUpdateonMergeLead('00Q', leadRecord, leadList);
            DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q', leadRecord, leadList);
        }

    static testMethod void onManualMergeOpportunityStageFollowup() {
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> leadValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'Program__c' => 'AY',
                'SalesOffice__c' => 'DEB',
                'Email' => 'test@ef.com'
        };
        Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', '', leadValues, TRUE);
        system.debug('leadRecord>>' + leadRecord);

        for (integer i = 0; i < 6; i++) {
            Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', '', leadValues, FALSE);
            leadList.add(leadRec);
            system.debug('list>>' + leadList);
        }
        insert leadList;

        for (lead leadRecrd : leadList) {
            leadIds.add(leadRecord.Id);
        }
        DCMergeHelper.OnManualMerge('00Q', leadRecord, leadIds);
        DCMergeHelper.validationForHasBookingAccountMerge('00Q', leadRecord, leadList);

        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => 'DEB'
        };
        Account accountRecord = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, TRUE);

        string dateValue = string.valueof(System.today().addDays(3));
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'SalesOffice__c' =>'DEB',
                'Program__c' => 'AY',
                'StageName' => System.Label.LeadStageFollowup,
                'Closedate' => dateValue,
                'TimeOutDate__c'=> dateValue

        };
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(accountRecord.id, 'testOpportunityName', opportunityFieldValues, True);

        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunityPersonAccount);

        for (integer i = 0; i < 6; i++) {
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName' + i, 'TestAccountFirstName' + i, recordTypeId, personAccountFieldValues, FALSE);
            accountList.add(newAccount);
            system.debug('list>>' + accountList);
        }
        insert accountList;

        for (Account accountRecrd : accountList) {
            accountIds.add(accountRecrd.Id);
        }

        Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;

        DCMergeHelper.OnManualMerge('001P', accountRecord, accountIds);
        DCMergeHelper.validationForHasBookingAccountMerge('001P', accountRecord, accountList);
        //DCMergeHelper.OpportunityStageUpdateOnMergeAccount('001P',oppList);
        //DCMergehelper.changeProgramOnOpportunityForPersonAccountMerge('001P', accountRecord, accountIds);
        DCMergeHelper.taskMergeReasonUpdateonMergeLead('00Q', leadRecord, leadList);
        DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q', leadRecord, leadList);
    }

    static testMethod void onManualMergeStageTBC() {
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> leadValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'Program__c' => 'AY',
                'SalesOffice__c' => 'DEB',
                'Email' => 'test@ef.com'
        };
        Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', '', leadValues, TRUE);
        system.debug('leadRecord>>' + leadRecord);

        for (integer i = 0; i < 6; i++) {
            Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', '', leadValues, FALSE);
            leadList.add(leadRec);
            system.debug('list>>' + leadList);
        }
        insert leadList;

        for (lead leadRecrd : leadList) {
            leadIds.add(leadRecord.Id);
        }
        DCMergeHelper.OnManualMerge('00Q', leadRecord, leadIds);
        DCMergeHelper.validationForHasBookingAccountMerge('00Q', leadRecord, leadList);

        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => 'DEB'
        };
        Account accountRecord = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, TRUE);

        string dateValue = string.valueof(System.today().addDays(3));
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'SalesOffice__c' =>'DEB',
                'Program__c' => 'AY',
                'StageName' => System.Label.LeadStageTBC,
                'Closedate' => dateValue,
                'TimeOutDate__c'=> dateValue

        };
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(accountRecord.id, 'testOpportunityName', opportunityFieldValues, True);

        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunityPersonAccount);

        for (integer i = 0; i < 6; i++) {
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName' + i, 'TestAccountFirstName' + i, recordTypeId, personAccountFieldValues, FALSE);
            accountList.add(newAccount);
            system.debug('list>>' + accountList);
        }
        insert accountList;

        for (Account accountRecrd : accountList) {
            accountIds.add(accountRecrd.Id);
        }

        Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;

        DCMergeHelper.OnManualMerge('001P', accountRecord, accountIds);
        DCMergeHelper.validationForHasBookingAccountMerge('001P', accountRecord, accountList);
        //DCMergeHelper.OpportunityStageUpdateOnMergeAccount('001P',oppList);
        //DCMergehelper.changeProgramOnOpportunityForPersonAccountMerge('001P', accountRecord, accountIds);
        DCMergeHelper.taskMergeReasonUpdateonMergeLead('00Q', leadRecord, leadList);
        DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q', leadRecord, leadList);
    }

    static testMethod void onManualMergeOppStageClosedLost() {
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> leadValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'Program__c' => 'AY',
                'SalesOffice__c' => 'DEB',
                'Email' => 'test@ef.com'
        };
        Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', '', leadValues, TRUE);
        system.debug('leadRecord>>' + leadRecord);

        for (integer i = 0; i < 6; i++) {
            Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', '', leadValues, FALSE);
            leadList.add(leadRec);
            system.debug('list>>' + leadList);
        }
        insert leadList;

        for (lead leadRecrd : leadList) {
            leadIds.add(leadRecord.Id);
        }
        DCMergeHelper.OnManualMerge('00Q', leadRecord, leadIds);
        DCMergeHelper.validationForHasBookingAccountMerge('00Q', leadRecord, leadList);

        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => 'DEB'
        };
        Account accountRecord = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, TRUE);

        string dateValue = string.valueof(System.today().addDays(3));
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'SalesOffice__c' =>'DEB',
                'Program__c' => 'AY',
                'StageName' => System.Label.OppStageClosedLost,
                'Closedate' => dateValue,
                'TimeOutDate__c'=> dateValue

        };
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(accountRecord.id, 'testOpportunityName', opportunityFieldValues, True);

        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunityPersonAccount);

        for (integer i = 0; i < 6; i++) {
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName' + i, 'TestAccountFirstName' + i, recordTypeId, personAccountFieldValues, FALSE);
            accountList.add(newAccount);
            system.debug('list>>' + accountList);
        }
        insert accountList;

        for (Account accountRecrd : accountList) {
            accountIds.add(accountRecrd.Id);
        }

        Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;

        DCMergeHelper.OnManualMerge('001P', accountRecord, accountIds);
        DCMergeHelper.validationForHasBookingAccountMerge('001P', accountRecord, accountList);
        //DCMergeHelper.OpportunityStageUpdateOnMergeAccount('001P',oppList);
        //DCMergehelper.changeProgramOnOpportunityForPersonAccountMerge('001P', accountRecord, accountIds);
        DCMergeHelper.taskMergeReasonUpdateonMergeLead('00Q', leadRecord, leadList);
        DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q', leadRecord, leadList);
    }



    static testMethod void ChangeProgramOrStatusForMasterREcord() {
        User tstandardUser= Testdatafactory.createUser( 'Marketing User', TRUE);
        system.debug('tstandardUser>>>'+tstandardUser);
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        string dateValue = string.valueof(System.today().addDays(3));

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> leadValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'Program__c' => 'AY',
                'SalesOffice__c' => 'DEB',
                'Email' => 'test@ef.com',
                'Status'=>'Closed',
                'RequestType__c'=>'BR'

        };

        Id leadrecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', leadrecordTypeId, leadValues, TRUE);
        system.debug('leadRecord>>' + leadRecord);

        for (integer i = 0; i < 6; i++) {
            Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', leadrecordTypeId, leadValues, FALSE);
            leadList.add(leadRec);
            system.debug('list>>' + leadList);
        }
        insert leadList;

        for (lead leadRecrd : leadList) {
            leadIds.add(leadRecord.Id);
        }
        DCMergeHelper.OnManualMerge('00Q', leadRecord, leadIds);
        DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q', leadRecord, leadList);
    }

    static testMethod void changeProgramOnOpportunityForPersonAccountMergeTest(){
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> personAccountFieldValues = new Map<String, String>{
                'Market__c' => 'DEB'
        };
        Account accountRecord = TestDataFactory.createPersonAccount('TestAccountFirstName', 'TestAccountFirstName', recordTypeId, personAccountFieldValues, TRUE);
        accountRecord = [SELECT PersonContactId FROM Account WHERE Id =:accountRecord.Id LIMIT 1];
        system.debug('accountrecord>>>'+accountRecord.PersonContactId);
        string dateValue = string.valueof(System.today().addDays(3));
        Map<String, String> opportunityFieldValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'SalesOffice__c' =>'DEB',
                'Program__c' => 'MULTI',
                'StageName' => System.Label.OpportunityBookingStage,
                'Closedate' => dateValue,
                'TimeOutDate__c'=> dateValue

        };
        Opportunity newOpportunityPersonAccount = TestDataFactory.createOpportunityForAccount(accountRecord.id, 'testOpportunityName', opportunityFieldValues, True);

        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(newOpportunityPersonAccount);

        for (integer i = 0; i < 6; i++) {
            Account newAccount = TestDataFactory.createPersonAccount('TestAccountFirstName' + i, 'TestAccountFirstName' + i, recordTypeId, personAccountFieldValues, FALSE);
            accountList.add(newAccount);
            system.debug('list>>' + accountList);
        }
        insert accountList;

        for (Account accountRecrd : accountList) {
            accountIds.add(accountRecrd.Id);
        }

        Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;
        system.debug('event>>>'+imEvent);

        DCMergeHelper.changeProgramOnOpportunityForPersonAccountMerge('001P',accountRecord,accountIds);
        DCMergeHelper.OnManualMerge('001P', accountRecord, accountIds);
    }

    static testMethod void changeProgramOnOpportunityBooking(){
        List<Lead> leadList = new List<Lead>();
        List<Account> accountList = new List<Account>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        string dateValue = string.valueof(System.today().addDays(3));

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Account.SobjectType).get('PersonAccount').Id;
        Map<String, String> leadValues = new Map<String, String>{
                'Market__c' => 'DEB',
                'Program__c' => 'MULTI',
                'SalesOffice__c' => 'DEB',
                'Email' => 'test@ef.com',
                'Status'=>'Closed',
                'RequestType__c'=>''

        };

        Id leadrecordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        Lead leadRecord = TestDataFactory.createLead('FirstName', 'strLastName', '', leadrecordTypeId, leadValues, TRUE);
        system.debug('leadRecord>>' + leadRecord);

        for (integer i = 0; i < 6; i++) {
            Lead leadRec = TestDataFactory.createLead('FirstName' + i, 'strLastName' + i, '', leadrecordTypeId, leadValues, FALSE);
            leadList.add(leadRec);
            system.debug('list>>' + leadList); 
        }
        insert leadList;

        for (lead leadRecrd : leadList) {
            leadIds.add(leadRecord.Id);
        }

        /*Event imEvent = new Event();
        imEvent.WhoId = accountRecord.PersonContactId;
        imEvent.DurationInMinutes = 30;
        imEvent.ActivityDateTime = DateTime.now();
        imEvent.Type = 'RES';
        insert imEvent;
        system.debug('event>>>'+imEvent);*/

        DCMergeHelper.ChangeProgramOrStatusForMasterREcord('00Q',leadRecord,leadList);

    }



}