force-app/main/default/objects/Account/fields/TotalBooking__c.field-meta.xml
<CustomField>
    <fullName>TotalBooking__c</fullName>
    <description>This is used to know how many bookings we have under this account</description>
    <label>TotalBooking</label>
    <summaryForeignKey>Booking__c.AccountId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/AccountContactID__c.field-meta.xml
<CustomField>
    <fullName>AccountContactID__c</fullName>
    <description>This field is used to store the Account ID of the Contact in the relation. This is used for integration with Poseidon.</description>
    <formula>Contact.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Contact Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/TotalBooking__c.field-meta.xml
<CustomField>
    <fullName>TotalBooking__c</fullName>
    <description>Used for Sending Family Details to Poseidon only if the related Account has Booking</description>
    <formula>Account.TotalBooking__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalBooking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountContactRelationHelper.cls
/**
 * Created by arjun.mohan on 2/9/2018.
 */

public with sharing class AccountContactRelationHelper {

    public static void validateAndSendDetailsToPoseidon(Map<Id, AccountContactRelation> AccountContactMap, String DMLType) {
        Id MasterRecordId;
        List<Map<String, String>> updateAccountInfo = new List<Map<String, String>>();
        String market='DEB';
        for (AccountContactRelation accountContactRecord : AccountContactMap.values()) {
            Map<String, String> AccountContactrelationfieldValueMap = new Map<String, String>();
            if (accountContactRecord.TotalBooking__c > 0) {

                for (Schema.FieldSetMember f : SObjectType.Account.FieldSets.UpdatePersonalInfo.getFields()) {
                    AccountContactrelationfieldValueMap.put(f.getFieldPath(), String.valueOf(accountContactRecord.get(f.getFieldPath())));
                }
                if (AccountContactrelationfieldValueMap.size() > 0) {
                    AccountContactrelationfieldValueMap.put('CreatedById',String.valueOf(accountContactRecord.CreatedById));
                    AccountContactrelationfieldValueMap.put('CreatedDate',String.valueOf(accountContactRecord.CreatedDate));
                    AccountContactrelationfieldValueMap.put('LastModifiedById',String.valueOf(accountContactRecord.LastModifiedById));
                    AccountContactrelationfieldValueMap.put('LastModifiedDate',String.valueOf(accountContactRecord.LastModifiedDate));
                    AccountContactrelationfieldValueMap.put('AccountId', String.valueOf(accountContactRecord.AccountContactID__c));
                    AccountContactrelationfieldValueMap.put('DMLType', DMLType);
                    AccountContactrelationfieldValueMap.put('MasterRecordId', String.valueOf(accountContactRecord.accountid));
                    updateAccountInfo.add(AccountContactrelationfieldValueMap);
                }

            }
        }
        if (updateAccountInfo.size() > 0) {
            SyncAccountRelationWrapper objSyncAccountRelationWrapper=new SyncAccountRelationWrapper(updateAccountInfo,market);
            String JSONValue= JSON.serialize(objSyncAccountRelationWrapper);
            ExternalRouter.callUpdateAccountFamilyDetailsService(updateAccountInfo);
        }

    }

    public class SyncAccountRelationWrapper
    {
        public String market { get; set; }
        public List<Map<String, String>> updateAccountInfo { get; set; }

        public SyncAccountRelationWrapper(List<Map<String, String>> updateAccountInfo, String market) {
            this.updateAccountInfo = updateAccountInfo;
            this.market = market;
        }
    }
}