force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/Apttus_Config2__ProductConfiguration__c.object-meta.xml
<CustomObject>
    <description>Represents a product configuration</description>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__TempObject__c/Apttus_Config2__TempObject__c.object-meta.xml
<CustomObject>
    <description>A container for temporary objects used by the application</description>
    <label>Temp Object  (CPQ)</label>
    <nameField>
        <displayFormat>TO-{0000000000}</displayFormat>
        <label>Temp Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Objects (CPQ)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/Apttus_Proposal__Proposal_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/APTS_Discount_Reason__c.field-meta.xml
<CustomField>
    <fullName>APTS_Discount_Reason__c</fullName>
    <description>Copy of the field on the Line Item in order to show up on the Proposal line Item as a separate line.</description>
    <label>Discount Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DI</fullName>
                <label>Discount</label>
            </value>
            <value>
                <fullName>DIDIS1</fullName>
                <label>Discount 1st Distribution</label>
            </value>
            <value>
                <fullName>DICORP</fullName>
                <label>Discount Corporation</label>
            </value>
            <value>
                <fullName>DIF</fullName>
                <label>Discount Flight</label>
            </value>
            <value>
                <fullName>DIFF</fullName>
                <label>Discount Free Flight</label>
            </value>
            <value>
                <fullName>DIVIP</fullName>
                <label>Discount VIP Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/APTS_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>APTS_Product_Code__c</fullName>
    <formula>if(Apttus_QPConfig__OptionId__c != null, Apttus_QPConfig__OptionId__r.ProductCode ,
Apttus_Proposal__Product__r.ProductCode
)</formula>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <formula>IF( TEXT(Apttus_QPConfig__AdjustmentType__c) = "% Discount" ,  TEXT(Apttus_QPConfig__AdjustmentAmount__c)&amp; "%" , IF(TEXT(Apttus_QPConfig__AdjustmentType__c) = "Discount Amount","-" &amp; TEXT(Apttus_QPConfig__AdjustmentAmount__c),""))</formula>
    <label>Discount</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/LTCourseNumber__c.field-meta.xml
<CustomField>
    <fullName>LTCourseNumber__c</fullName>
    <description>Used to display LT Course Number on Quote Preview Page</description>
    <formula>Apttus_QPConfig__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_LTCourseNumber__c</formula>
    <label>LT Course Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/LTDestinationCode__c.field-meta.xml
<CustomField>
    <fullName>LTDestinationCode__c</fullName>
    <description>Used for LT Bundle</description>
    <formula>Apttus_QPConfig__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_DestinationCode__c</formula>
    <label>LTDestinationCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Non_Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discounted_Price__c</fullName>
    <label>Non Discounted Price</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_QPConfig__ProposalAdjustmentLineItem__c/Apttus_QPConfig__ProposalAdjustmentLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents an adjustment to the price of a product/service</description>
    <label>Proposal Adjustment Line Item</label>
    <nameField>
        <displayFormat>AD-{0000000000}</displayFormat>
        <label>Adjustment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Adjustment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_QPConfig__ProposalAdjustmentLineItem__c/fields/Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Price__c</fullName>
    <formula>Apttus_QPConfig__LineItemId__r.Net_Price_2_decimals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_QPConfig__ProposalAdjustmentLineItem__c/fields/Non_Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discounted_Price__c</fullName>
    <formula>Apttus_QPConfig__LineItemId__r.Non_Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TemporaryQuoteLineItem__c/TemporaryQuoteLineItem__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the discount logic temporary in Salesforce and scribe deletes.</description>
    <label>Temporary Quote Line Item</label>
    <nameField>
        <label>Temporary Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TemporaryQuoteLineItem__c/fields/Article_Name__c.field-meta.xml
<CustomField>
    <fullName>Article_Name__c</fullName>
    <description>This will contain Discount reason value and Incentive name of the proposal adjustment line items.</description>
    <label>Article Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TemporaryQuoteLineItem__c/fields/Discount_Reason__c.field-meta.xml
<CustomField>
    <fullName>Discount_Reason__c</fullName>
    <description>This will contain Discount reason code and Incentive codeof the proposal adjustment line items.</description>
    <label>Discount Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TemporaryQuoteLineItem__c/fields/Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Price__c</fullName>
    <description>This field is used to save the sum of discounted prices in quote preview component.</description>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemporaryQuoteLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Number of Adjustment line items.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemporaryQuoteLineItem__c/fields/Quote_Proposal__c.field-meta.xml
<CustomField>
    <fullName>Quote_Proposal__c</fullName>
    <description>Quote ID from Proposal Line Items.</description>
    <label>Quote/Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Temporary Quote Line Items</relationshipLabel>
    <relationshipName>Temporary_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuotePreview.cls
public class QuotePreview {
    public static List<Apttus_Proposal__Proposal_Line_Item__c> fetchLineItems;

    //Create list of wrapper to grab all sobject records
    @AuraEnabled
    public static List<LineitemProductWrapper> Preview(String rcrdId){
        Id currentrecord;
        List<LineitemProductWrapper> PreviewList = new List<LineitemProductWrapper>();

        try{

            fetchLineItems = [select id,name,Apttus_Proposal__Product__c,Product_Code__c ,Apttus_Proposal__Description__c ,Apttus_Proposal__Product__r.ProductCode,
                    Apttus_Proposal__Product__r.name,Apttus_Proposal__Proposal__c,APTS_Product_Code__c,Apttus_QPConfig__LineType__c,
                    Non_Discounted_Price__c,Apttus_QPConfig__Quantity2__c,Apttus_Proposal__Quantity__c,Apttus_Proposal__Proposal__r.Program__c,
                    Apttus_QPConfig__StartDate__c,Apttus_QPConfig__EndDate__c,Discount__c,LTDestinationCode__c,LTCourseNumber__c,
                    APTS_Discount_Reason__c,Apttus_QPConfig__NetPrice__c,CurrencyIsoCode,
                    Apttus_QPConfig__IsOptional__c,(Select Id,Apttus_QPConfig__IncentiveCode__c,Apttus_QPConfig__IncentiveId__r.name,Apttus_QPConfig__IncentiveAdjustmentAmount__c FROM Apttus_QPConfig__AdjustmentLineItems__r)
            from Apttus_Proposal__Proposal_Line_Item__c where Apttus_Proposal__Proposal__c =:rcrdId];
            system.debug(' array size is '+fetchLineItems);
            for(Apttus_Proposal__Proposal_Line_Item__c lineItemrecord : fetchLineItems){
                system.debug(' lineItemrecord'+lineItemrecord);
                if(!(lineItemrecord.APTS_Product_Code__c ==Label.FTEFX_Article_Code && lineItemrecord.Non_Discounted_Price__c == 0)){
                    LineitemProductWrapper wrapobj=new LineitemProductWrapper();
                    wrapobj.lineitem=lineItemrecord;
                    wrapobj.NonDiscountedPrice=0;
                    wrapobj.calculatedPrice = (lineItemrecord.Non_Discounted_Price__c!=null?lineItemrecord.Non_Discounted_Price__c:0.0) * (lineItemrecord.Apttus_QPConfig__Quantity2__c);

                    PreviewList.add(wrapobj);
                }
            }


        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotePreview', 'Preview', currentrecord);
            System.debug('Cannot Preview Line Items '+ex.getMessage());

            //return fetchLineItems;
        }
        return PreviewList;
    }

    @AuraEnabled
    public static List<LineItemGroupWrapper> getSummaryData(String rcrdId){
        Id currentrecord;
        List<LineItemGroupWrapper> lstOfSummary = new List<LineItemGroupWrapper>();
        try{
            Schema.DescribeFieldResult fieldResult = Apttus_Proposal__Proposal_Line_Item__c.APTS_Discount_Reason__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            String currencyCode='';
            Map<String,String> mapOfPicklistVal = new Map<String,String>();
            for(Schema.PicklistEntry picklistFld:ple){
                mapOfPicklistVal.put(picklistFld.getValue(),picklistFld.getLabel());
            }
            if(fetchLineItems==null || fetchLineItems.isEmpty()){
                fetchLineItems = [select id,name,Apttus_Proposal__Product__c,Product_Code__c ,Apttus_Proposal__Description__c ,Apttus_Proposal__Product__r.ProductCode,
                        Apttus_Proposal__Product__r.name,Apttus_Proposal__Proposal__c,APTS_Product_Code__c,Apttus_QPConfig__LineType__c,
                        Non_Discounted_Price__c,Apttus_QPConfig__Quantity2__c,LTDestinationCode__c,Apttus_Proposal__Proposal__r.Program__c,
                        Apttus_QPConfig__StartDate__c,Apttus_QPConfig__EndDate__c,Discount__c,LTCourseNumber__c,
                        APTS_Discount_Reason__c,Apttus_QPConfig__NetPrice__c,CurrencyIsoCode,
                        Apttus_QPConfig__IsOptional__c,(Select Id,Apttus_QPConfig__IncentiveCode__c,Apttus_QPConfig__IncentiveId__r.name,Apttus_QPConfig__IncentiveAdjustmentAmount__c FROM Apttus_QPConfig__AdjustmentLineItems__r)
                from Apttus_Proposal__Proposal_Line_Item__c where Apttus_Proposal__Proposal__c =:rcrdId];
            }
            AggregateResult[] groupedResults =[Select Sum(Apttus_QPConfig__NetPrice__c)netPrice,Sum(Non_Discounted_Price__c)orgPrice,APTS_Discount_Reason__c,Sum(Apttus_QPConfig__Quantity2__c)DiscountQuantity,MAX(CurrencyIsoCode)currency
                                                from Apttus_Proposal__Proposal_Line_Item__c WHERE (Apttus_Proposal__Proposal__c =: rcrdId AND (NOT(APTS_Product_Code__c=:Label.FTEFX_Article_Code AND Non_Discounted_Price__c =: 0))) group by APTS_Discount_Reason__c];
            for(AggregateResult ar:groupedResults){
                currencyCode = String.valueOf(ar.get('currency'));
                if(ar.get('APTS_Discount_Reason__c')!=null && String.valueOf(ar.get('APTS_Discount_Reason__c'))!=''){
                    LineItemGroupWrapper lineItemWrp = new LineItemGroupWrapper();
                    lineItemWrp.ProductCode = String.valueOf(ar.get('APTS_Discount_Reason__c'));
                    //lineItemWrp.ProductCode = mapOfPicklistVal.get(String.valueOf(ar.get('APTS_Discount_Reason__c')));
                    System.debug('lineItemWrp.ProductCode== '+lineItemWrp.ProductCode);
                    lineItemWrp.netPrice = (Decimal)ar.get('netPrice')-(Decimal)ar.get('orgPrice');
                    lineItemWrp.DiscountQuantity = (Decimal)ar.get('DiscountQuantity');
                    lineItemWrp.ProductName = mapOfPicklistVal.get(String.valueOf(ar.get('APTS_Discount_Reason__c')));
                    //lineItemWrp.ProductName = String.valueOf(ar.get('APTS_Discount_Reason__c'));
                    System.debug('lineItemWrp.ProductName== '+lineItemWrp.ProductName);
                    lineItemWrp.CurrencyPreview = String.valueOf(ar.get('currency'));
                    lineItemWrp.calculatedPrice = lineItemWrp.netPrice * lineItemWrp.DiscountQuantity;
                    lstOfSummary.add(lineItemWrp);
                }
            }
            System.debug('currencyCode =$$$$== '+currencyCode);
            Map<String,LineItemGroupWrapper> mapOfIncentiveCode = new Map<String,LineItemGroupWrapper>();
            for(Apttus_Proposal__Proposal_Line_Item__c proposal: fetchLineItems){
                for(Apttus_QPConfig__ProposalAdjustmentLineItem__c adj:proposal.Apttus_QPConfig__AdjustmentLineItems__r){
                    if(adj.Apttus_QPConfig__IncentiveCode__c!=null && adj.Apttus_QPConfig__IncentiveCode__c!=''){
                        if(mapOfIncentiveCode.containsKey(adj.Apttus_QPConfig__IncentiveCode__c)){
                            LineItemGroupWrapper lineItem = mapOfIncentiveCode.get(adj.Apttus_QPConfig__IncentiveCode__c);
                            lineItem.netPrice += adj.Apttus_QPConfig__IncentiveAdjustmentAmount__c!=null?adj.Apttus_QPConfig__IncentiveAdjustmentAmount__c:0.0;
                            lineItem.calculatedPrice  = lineItem.netPrice;
                        }else{
                            LineItemGroupWrapper lineItem = new LineItemGroupWrapper();
                            lineItem.netPrice = adj.Apttus_QPConfig__IncentiveAdjustmentAmount__c!=null?adj.Apttus_QPConfig__IncentiveAdjustmentAmount__c:0.0;
                            lineItem.ProductCode = adj.Apttus_QPConfig__IncentiveCode__c;
                            lineItem.ProductName = adj.Apttus_QPConfig__IncentiveId__r.name;
                            lineItem.CurrencyPreview = currencyCode;
                            lineItem.calculatedPrice  = lineItem.netPrice;
                            mapOfIncentiveCode.put(lineItem.ProductCode,lineItem);
                            lstOfSummary.add(lineItem);
                        }
                    }
                }
            }
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotePreview', 'Preview', currentrecord);
            System.debug('Cannot Preview Line Items '+ex.getMessage());
        }

        return lstOfSummary;
    }

    @AuraEnabled
    public static string getCurrentOrgUrl(){
        return URL.getSalesforceBaseUrl().toExternalForm();
    }
    @AuraEnabled
    public static List<string> getConfigIds(string quoteId)
    {
        List<String> IdList=new List<String>();
        Id Quote=Id.valueOf(quoteId);
        List<Apttus_Config2__ProductConfiguration__c> configList=[select Id from Apttus_Config2__ProductConfiguration__c where Apttus_QPConfig__Proposald__c=:Quote Limit 1];
        if(configList.size() > 0)
        {
            IdList.add(configList[0].Id);
            List<Apttus_Config2__TempObject__c> configReqIdList=[select Id from Apttus_Config2__TempObject__c where Apttus_Config2__ConfigurationId__c=:configList[0].Id limit 1];
            if(configReqIdList.size() > 0)
            {

                IdList.add(configReqIdList[0].Id);
            }

        }


        return IdList;

    }

    @AuraEnabled
    public static boolean saveTempData(string summaryData, String rcrdId){
        Id currentrecord;
        List<TemporaryQuoteLineItem__c> lstOfQuoteData = new List<TemporaryQuoteLineItem__c>();
        List<LineItemGroupWrapper> lstOfSummaryData = (List<LineItemGroupWrapper>)JSON.deserialize(summaryData,List<LineItemGroupWrapper>.class);
        try{
            lstOfQuoteData = [Select id from TemporaryQuoteLineItem__c where Quote_Proposal__c =: rcrdId];
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotePreview', 'Preview', currentrecord);
            System.debug('Cannot Preview Line Items '+ex.getMessage());

            lstOfQuoteData = new List<TemporaryQuoteLineItem__c>();
        }
        if(lstOfQuoteData.size()>0){
            delete lstOfQuoteData;
        }

        try{
            system.debug('======>> '+lstOfSummaryData.size());
            TemporaryQuoteLineItem__c QLine;
            for(LineItemGroupWrapper lst: lstOfSummaryData){
                QLine = new TemporaryQuoteLineItem__c();
                QLine.Quote_Proposal__c = (Id) rcrdId;
                QLine.Quantity__c = lst.DiscountQuantity;
                QLine.Discount_Reason__c = lst.ProductCode;
                QLine.Article_Name__c = lst.ProductName;
                QLine.Net_Price__c = lst.netPrice;
                lstOfQuoteData.add(QLine);
            }
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotePreview', 'Preview', currentrecord);
            System.debug('Cannot Preview Line Items '+ex.getMessage());
            return false;
        }
        try{
            insert lstOfQuoteData;
        }catch(Exception ex){
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotePreview', 'Preview', currentrecord);
            System.debug('Cannot Preview Line Items '+ex.getMessage());
            return false;
        }
        return true;
    }


    Public class LineitemProductWrapper{
        @AuraEnabled
        public Apttus_Proposal__Proposal_Line_Item__c lineitem {get;set;}
        @AuraEnabled
        public Decimal PriceQuantity {get;set;}
        @AuraEnabled
        public Decimal NonDiscountedPrice {get;set;}
        @AuraEnabled
        public Product2 product {get;set;}
        @AuraEnabled
        public Decimal calculatedPrice{get;set;}


    }

    public class LineItemGroupWrapper{
        @AuraEnabled
        public Decimal netPrice{get;set;}
        @AuraEnabled
        public String ProductName{get;set;}
        @AuraEnabled
        public String ProductCode{get;set;}
        @AuraEnabled
        public Decimal DiscountQuantity{get;set;}
        @AuraEnabled
        public Decimal calculatedPrice{get;set;}
        @AuraEnabled
        public String CurrencyPreview{get;set;}

    }


}