force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Models the quotes sent to the customers</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The opportunity this quote is related to</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The Quote program</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Quote__c/fields/QuoteCreatedBy__c.field-meta.xml
<CustomField>
    <fullName>QuoteCreatedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app++/main/default/objects/Quote__c/fields/QuotePDF__c.field-meta.xml
<CustomField>
    <fullName>QuotePDF__c</fullName>
    <description>The url to retrieve the Quote PDF</description>
    <label>Quote PDF</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SentByEmail__c.field-meta.xml
<CustomField>
    <fullName>SentByEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates whether the quote has been sent via Email</description>
    <label>Sent by Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/SPQTask.recordType-meta.xml
<RecordType>
    <fullName>SPQTask</fullName>
    <active>true</active>
    <description>Reffered for SPQ Task</description>
    <label>SPQ Task</label>
</RecordType>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/QuotesHelper.cls
/**
 * Created by thejasvi.a on 3/16/2018.
 */

public with sharing class QuotesHelper {

    public static void closeSPQTasksAndCreateNewTaskOnOpportunity(List<Quote__c> quoteList) {
        Set<Id> oppIdSet = new Set<Id>();
            for(Quote__c quoteRecord: quoteList){
                if(quoteRecord.Opportunity__c!= null){
                    oppIdSet.add(quoteRecord.Opportunity__c);
                }
            }
        List<Task> taskList= TasksSelector.getSPQTasks(oppIdSet, system.label.SPQTask);
        closeSPQTasks(taskList);
        createTaskforEmailSent(quoteList);
        } 

    private static void closeSPQTasks(List<Task> taskList){
        List<Task> tasksToUpdate = new List<Task>();
        Id currentRecordId;
        try {
            for (Task pqTaskRecord:taskList) {
                currentRecordId = pqTaskRecord.Id;
                if (!pqTaskRecord.IsClosed) {
                    pqTaskRecord.Status = System.label.TaskStatusCompleted;
                    tasksToUpdate.add(pqTaskRecord);
                }
            }
            if (tasksToUpdate.size() > 0) {
                update tasksToUpdate;
            }
        } catch(exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotesHelper', 'closeSPQTasks',currentRecordId );
        }
    }

    private static void createTaskforEmailSent(List<Quote__c> quoteList){
        List<Task> taskList = new List<Task>();
        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Task.getSObjectType()).get(Label.CallTaskRecordTypeDeveloperName).Id;
        Id oppRecordId;
        try {
            for (Quote__c quoteRecord: quoteList) {
                if (quoteRecord.SentByEmail__c && quoterecord.Opportunity__c!=null) {
                    oppRecordId = quoteRecord.Opportunity__c;
                    Task taskRecord = new Task();
                    taskRecord.TaskSubtype = System.Label.Email;
                    taskRecord.Description = quoteRecord.QuotePDF__c;
                    taskRecord.Status = System.Label.TaskStatusCompleted;
                    taskRecord.WhatId = quoteRecord.Opportunity__c;
                    taskRecord.Program__c = quoteRecord.Program__c;
                    taskRecord.Subject = System.Label.EmailPriceQuote;
                    taskRecord.OwnerId = quoteRecord.QuoteCreatedBy__c;
                    taskRecord.RecordTypeId = recordTypeId;
                    taskList.add(taskRecord);
                }
            }
            if (taskList.size() > 0) {
                insert taskList;
            }
        }
        catch(exception ex) {
            ExceptionHandler.errorLog(ex.getMessage(), ex.getStackTraceString(),
                    'QuotesHelper', 'createTaskforEmailSent',oppRecordId );
        }
    }
}