force-app++/main/default/objects/Account/fields/HadAddressonCreation__c.field-meta.xml
<CustomField>
    <fullName>HadAddressonCreation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicated whether a customer provided an address upon creation.</description>
    <label>Had Address on Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CreationMethod__c.field-meta.xml
<CustomField>
    <fullName>CreationMethod__c</fullName>
    <label>Creation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enteredbyuser</fullName>
                <label>Entered By User</label>
            </value>
            <value>
                <fullName>Excel Import</fullName>
            </value>
            <value>
                <fullName>Ef.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CreationType__c.field-meta.xml
<CustomField>
    <fullName>CreationType__c</fullName>
    <description>this field is used to know the importing as lead/Opportunity/Account
Story # : SF280</description>
    <label>Creation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
                <default>true</default>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/HadAddressonCreation__c.field-meta.xml
<CustomField>
    <fullName>HadAddressonCreation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If customer gave address when contact was created – Maybe on opportunity??</description>
    <label>Had Address on Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsDupeProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsDupeProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be default false and after this record is run through dupe check then this should be set as true</description>
    <label>Is Dupe Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ReadyForRanking__c.field-meta.xml
<CustomField>
    <fullName>ReadyForRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the dupe check process is completed, this flag will be set</description>
    <label>Ready For Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <description>SalesOfficetowhichLeadbelongs</description>
    <label>SalesOffice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/fields/SalesOfficeProgram__c.field-meta.xml
<CustomField>
    <fullName>SalesOfficeProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field populates the corresponding Sales Office of Lead based on Market, Program and Salesoffice.</description>
    <label>Sales Office / Program</label>
    <referenceTo>SalesOfficeProgram__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture the Source during the manual creation of the Lead</description>
    <label>Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Source__c.IsGlobal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Source__c.Market__c</field>
            <operation>equals</operation>
            <valueField>$Source.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>Source__c.AvailableforManualEntry__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SourceCodeAuto__c.field-meta.xml
<CustomField>
    <fullName>SourceCodeAuto__c</fullName>
    <label>Source Code Auto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Customer</businessProcess>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/LeadRankingSetting__c/LeadRankingSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Settings is Market and Product Specific.</description>
    <label>Lead Ranking Setting</label>
</CustomObject>

force-app/main/default/objects/LeadRankingSetting__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Holds ranking value depending on Market and product, which can be 9 or 10.</description>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LegalSettings__c/LegalSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market specific legal settings</description>
    <label>Legal Settings</label>
</CustomObject>

force-app/main/default/objects/SalesOfficeProgram__c/SalesOfficeProgram__c.object-meta.xml
<CustomObject>
    <description>This object stores the address of various Sales offices over globe</description>
    <!-- <externalSharingModel>ReadWrite</externalSharingModel> -->
    <label>Sales Office / Program</label>
    <nameField>
        <label>Sales Office / Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesOffices/Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOfficeProgram__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Used to store the 'Market' of sales office</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOfficeProgram__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Used to store the 'Program ' of sales office</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOfficeProgram__c/fields/SaleOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>SaleOfficeCode__c</fullName>
    <description>Used to store the Sales office code of the region</description>
    <label>Sale Office Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOffice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Source is the way we track information about how the customers came to EF</description>
    <label>Source</label>
    <nameField>
        <label>Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app++/main/default/objects/Source__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Displays the code of the Source</description>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Displays the Market to which the Source belongs; ALL in case of global Source</description>
    <label>Market</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Displays the name of the Code</description>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/RequestType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CBR</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
    </customValue>
    <customValue>
        <fullName>CU</fullName>
    </customValue>
    <customValue>
        <fullName>IM</fullName>
    </customValue>
    <customValue>
        <fullName>PQ</fullName>
    </customValue>
    <customValue>
        <fullName>REQ</fullName>
    </customValue>
    <customValue>
        <fullName>RES</fullName>
    </customValue>
    <customValue>
        <fullName>IR</fullName>
    </customValue>
    <customValue>
        <fullName>WI</fullName>
        <isActive>false</isActive>
        <label>WI</label>
    </customValue>
    <customValue>
        <fullName>MCR</fullName>
        <isActive>false</isActive>
        <label>MCR</label>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
        <isActive>false</isActive>
        <label>EXC</label>
    </customValue>
    <customValue>
        <fullName>CNT</fullName>
        <isActive>false</isActive>
        <label>CNT</label>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
        <isActive>false</isActive>
        <label>WV</label>
    </customValue>
    <customValue>
        <fullName>VST</fullName>
        <isActive>false</isActive>
        <label>VST</label>
    </customValue>
    <customValue>
        <fullName>TRV</fullName>
        <isActive>false</isActive>
        <label>TRV</label>
    </customValue>
    <customValue>
        <fullName>TRR</fullName>
        <isActive>false</isActive>
        <label>TRR</label>
    </customValue>
    <customValue>
        <fullName>TRM</fullName>
        <isActive>false</isActive>
        <label>TRM</label>
    </customValue>
    <customValue>
        <fullName>PST</fullName>
        <isActive>false</isActive>
        <label>PST</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <isActive>false</isActive>
        <label>TR</label>
    </customValue>
    <masterLabel>RequestType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LeadTriggerTest.cls
/**
 * Created by Arkadiusz Celej on 11.01.2018.
 */

@IsTest
private class LeadTriggerTest {

    private static TestDataFactory.DefaultPicklistValuesHelper picklistValuesHelper = new TestDataFactory.DefaultPicklistValuesHelper();

    static testMethod void whenProgramChangesUpdateProgramOnSystemCallTasks() {
        //given
        Integer numberOfLeads = 50;
        TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
        leadBuilder.setDefaultPicklistHelper(picklistValuesHelper);
        Lead[] leads = new Lead[]{};
        Task[] systemTasks = new Task[]{};
        for(Integer i = 0 ; i < numberOfLeads; i++){
            leads.add((Lead)leadBuilder.build().getRecord());
            systemTasks.addAll(leadBuilder.tasks);
        }
        insert leads;

        TestDataFactory.TaskBuilder tb = new TestDataFactory.TaskBuilder();
        for(Integer i = 0 ; i < numberOfLeads; i++){
            tb.build();
            tb.withRecordType(Label.SystemCallTaskRecordTypeDeveloperName);
            tb.setField('Program__c', picklistValuesHelper.program);
            tb.setWho(leads[i].Id);
            systemTasks.add((Task)tb.getRecord());
        }
        insert systemTasks;

        for(Lead l : leads){
            l.Program__c = picklistValuesHelper.program2;
        }

        //when
        Test.startTest();
        update leads;
        Test.stopTest();

        //then
        Set<Id> leadIds = (new Map<Id, Lead>(leads)).keySet();
        Lead[] updatedLeads = LeadsSelector.getLeadsWithOpenTasks(leadIds, Label.SystemCallTaskRecordTypeDeveloperName);
        System.assert(updatedLeads.size() > 0);
        for(Lead l : updatedLeads){
            System.assertEquals(picklistValuesHelper.program2, l.Tasks[0].Program__c,' Incorrect program');
        }
    }

    static testMethod void whenOwnerChangesReassignOpenTasks() {
        User u = TestDataFactory.createAdminUser(true);
        System.runAs(u){
            Integer numberOfLeads = 50;
            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            leadBuilder.setDefaultPicklistHelper(picklistValuesHelper);
            Lead[] leads = new Lead[]{};
            Task[] systemTasks = new Task[]{};
            for(Integer i = 0 ; i < numberOfLeads; i++){
                leads.add((Lead)leadBuilder.build().getRecord());
            }
            insert leads;
    
            TestDataFactory.TaskBuilder tb = new TestDataFactory.TaskBuilder();
            for(Integer i = 0 ; i < numberOfLeads; i++){
                tb.build();
                tb.withRecordType(Label.SystemCallTaskRecordTypeDeveloperName);
                tb.setWho(leads[i].Id);
                systemTasks.add((Task)tb.getRecord());
            }
            insert systemTasks;
    
            for(Lead l : leads){
                l.OwnerId = u.Id;
            }
    
            Test.startTest();
            update leads;
            Test.stopTest();
    
            Set<Id> leadIds = (new Map<Id, Lead>(leads)).keySet();
            Lead[] updatedLeads = LeadsSelector.getLeadsWithOpenTasks(leadIds, Label.SystemCallTaskRecordTypeDeveloperName);
            System.assert(updatedLeads.size() > 0);
            for(Lead l : updatedLeads){
                System.assertEquals(u.Id, l.Tasks[0].OwnerId,'Tasks should be reassigned to new Lead Owner');
            }
        }
    }

    static testMethod void whenOwnerChangesCreateSystemCallTasks() {
        User u = TestDataFactory.createAdminUser(true);
        System.runAs(u){
            Integer numberOfLeads = 50;
            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            leadBuilder.setDefaultPicklistHelper(picklistValuesHelper);
            Lead[] leads = new Lead[]{};
            Task[] systemTasks = new Task[]{};
            for(Integer i = 0 ; i < numberOfLeads; i++){
                leads.add((Lead)leadBuilder.build().getRecord());
            }
            insert leads;
    
            for(Lead l : leads){
                l.OwnerId = u.Id;
            }
    
            Test.startTest();
            update leads;
            Test.stopTest();
    
            Set<Id> leadIds = (new Map<Id, Lead>(leads)).keySet();
            Lead[] updatedLeads = LeadsSelector.getLeadsWithOpenTasks(leadIds, Label.SystemCallTaskRecordTypeDeveloperName);
            System.assert(updatedLeads.size() > 0);
            //for(Lead l : updatedLeads){
            //    System.assertEquals(1, l.Tasks.size(),'Lead should have one and only one system call task');
            //    System.assertEquals(u.Id, l.Tasks[0].OwnerId,'Tasks should be reassigned to new Lead Owner');
            //}
        }
    }

    static testMethod void whenLeadCreatedPopulateSalesOfficeProgram(){
        Map<String,String> salesOfficeValues = new Map<String,String>{
                'Market__c'=>'DEB',
                'program__c' => 'AY',
                'SaleOfficeCode__c'=>'DEB'
        };
        SalesOfficeProgram__c salesOffieRecord = TestDataFactory.createSalesOfficeProgram('Name', '' ,salesOfficeValues,true);

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        List<Lead> leadlist = new List<Lead>();
        Map<String, String> leadFieldValues = new Map<String, String>{
                'program__c' => 'AY',
                'Market__c' => 'DEB',
                'SalesOffice__c'=>'DEB',
                'Email'=>'record@ef.com'
        };
        Lead newLead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);
        leadlist.add(newLead);
        LeadsHelper.populateSalesOfficeProgram(leadlist);
    }

    static testMethod void whenLeadCreatedPopulateSource(){
        Map<String,String> sourceValues = new Map<String,String>{
                'Name'=>'testSource',
                'Market__c'=>'DEB',
                'Code__c'=>'E007'
        };

        Source__c sourceRecord = TestDataFactory.createSource('SourceName', '', sourceValues ,TRUE);

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        List<Lead> leadlist = new List<Lead>();
        Map<String, String> leadFieldValues = new Map<String, String>{
                'program__c' => 'AY',
                'Market__c' => 'DEB',
                'SalesOffice__c'=>'DEB',
                'Email'=>'record@ef.com',
                'SourceCodeAuto__c'=>'E007'
        };
        Lead newLead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);
        leadlist.add(newLead);
        LeadsHelper.populateSourceBasedonSourceCodeAuto(leadlist);
    }

    static testMethod void whenLeadCreatedPopulateSourceCodeAndPartner(){
        Map<String,String> sourceValues = new Map<String,String>{
                'Name'=>'testSource',
                'Market__c'=>'DEB',
                'Code__c'=>'E007'
        };

        Source__c sourceRecord = TestDataFactory.createSource('SourceName', '', sourceValues ,TRUE);

        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        List<Lead> leadlist = new List<Lead>();
        Map<String, String> leadFieldValues = new Map<String, String>{
                'program__c' => 'AY',
                'Market__c' => 'DEB',
                'SalesOffice__c'=>'DEB',
                'Email'=>'record@ef.com',
                'Source__c'=>sourceRecord.Id,
                'Street'=>'2Main'
        };
        Lead newLead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);
        leadlist.add(newLead); 
        LeadsHelper.populateSourceCodeAutoAndPartnerFromSource(leadlist);
        LeadsHelper.updateHadAddressFilledOnCreation(leadList);
    }

    private static testMethod void whenLeadCreatedPopulatePublicGroup() {
        User tAdminUser = TestDataFactory.createAdminUser(True);
        tAdminUser = [SELECT Id FROM User WHERE Id = :tAdminUser.ID];
        system.runAs(tAdminUser) {
            TestDataFactory.createPublicGroup(TRUE, 'DEB_DEB_AYP', 'DEB_DEB_AYP');
            Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
            List<Lead> leadlist = new List<Lead>();
            Map<String, String> leadFieldValues = new Map<String, String>{
                    'program__c' => 'AYP',
                    'Market__c' => 'DEB',
                    'SalesOffice__c' => 'DEB',
                    'Email' => 'record@ef.com'
            };
            Lead newLead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '', leadFieldValues, true);
            leadlist.add(newLead);
            LeadsHelper.createShareRecordsOnInsert(leadlist);
        }
    }
    static testMethod void leadSelector(){
        Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
        Map<String, String> leadFieldValues = new Map<String, String>{
                'program__c' => 'AY',
                'Market__c' => 'DEB',
                'SalesOffice__c'=>'DEB',
                'Email'=>'record@ef.com'
        };
        Lead newLead = TestDataFactory.createLead('LoganAction', 'Test', 'EF', '',leadFieldValues, true);

        LeadsSelector.leadRecordMap(new List<Id>{newLead.Id});
        LeadsSelector.getNotConvertedLeadMapById(new List<Id>{newLead.Id});
        LeadsSelector.getLeadByConvertedOpportunityId(new Set<Id>{newLead.Id});

    }
    
     private static testMethod void whenLeadCreatedPopulateRanking() {
         //User tAdminUser = TestDataFactory.createAdminUser(True);
         //system.runAs(tAdminUser) {
             List<LeadRankingSetting__c> leadRankingSetting = Test.loadData(LeadRankingSetting__c.sObjectType, 'File_LeadRankingSettings');
             List<LegalSettings__c> legalSetting = Test.loadData(LegalSettings__c.sObjectType, 'File_LegalSettings');
        	Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
            Lead leadRec=new Lead();
            leadRec.FirstName = 'tyyu89';
            leadRec.LastName = 'lastname89';
            leadRec.program__c = 'AY';
            leadRec.Market__c = 'DEB';
            leadRec.SalesOffice__c='DEB';
            leadRec.Email='record@ef.com';
            leadRec.ReadyForRanking__c=TRUE;
            leadRec.IsDupeProcessed__c=TRUE;              
            leadRec.Ranking__c=5;
            leadRec.RequestType__c='BR';
            insert leadRec;
                
            RankingHandler.getLeadSettings(new List<Lead>{leadRec});         
        //}
     }
        
    private static testMethod void whenLeadCreateCheckRanking() {
        //User tAdminUser = TestDataFactory.createAdminUser(True);
        //system.runAs(tAdminUser) {
            List<LeadRankingSetting__c> leadRankingSetting = Test.loadData(LeadRankingSetting__c.sObjectType, 'File_LeadRankingSettings');
            List<LegalSettings__c> legalSetting = Test.loadData(LegalSettings__c.sObjectType, 'File_LegalSettings');
            Id recordTypeId = RecordTypesSelector.getActiveRecTypesByDevName(Lead.SobjectType).get('Customer').Id;
            Lead leadRec=new Lead();
            leadRec.FirstName = 'tyyu89';
            leadRec.LastName = 'lastname89';
            leadRec.program__c = 'AY';
            leadRec.Market__c = 'DEB';
            leadRec.SalesOffice__c='DEB';
            leadRec.Email='record@ef.com';
            leadRec.ReadyForRanking__c=TRUE;
            leadRec.IsDupeProcessed__c=TRUE;              
            leadRec.creationType__c='Account';
            leadRec.CreationMethod__c='Excel Import';
            leadRec.RequestType__c='BR';
            insert leadRec;
   
            RankingHandler.getLeadSettings(new List<Lead>{leadRec});         
        //}
    }
	
	@IsTest
    static void when_LeadHasAddressOnCreation_Expect_FlagIsSetToTrue(){

        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
        System.runAs(adminUser){

            //given
            Integer numOfLeads = 10;
            String testAddress = 'Marszalkowska 15';
            Set<Id> leadIds = new Set<Id>();

            List<Lead> leads = new List<Lead>();
            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            for(Integer i = 0; i < numOfLeads; i++){
                Lead lead = (Lead)leadBuilder.getRecord();
                lead.Street = testAddress;
                leads.add(lead);
                leadBuilder.build();
            }

            //when
            Test.startTest();
            insert leads;
            Test.stopTest();

            //then
            for(Lead lead : leads){
                leadIds.add(lead.Id);
            }
            List<Lead> insertedLeads = [
                    SELECT HadAddressonCreation__c, Address, Street
                    FROM Lead
                    WHERE Id IN :leadIds
            ];

            System.assertEquals(numOfLeads, insertedLeads.size());
            for(Integer i = 0; i<numOfLeads; i++){
                System.assertEquals(testAddress, insertedLeads[i].Street);
                System.assertEquals(TRUE, insertedLeads[i].HadAddressonCreation__c);
            }
        }
    }

	@IsTest
    static void when_LeadDoesNotHaveAddressOnCreation_Expect_FlagIsSetToFalse(){

        User adminUser = TestDataFactory.createAdminUser(true);
        TestDataFactory.bypassValidationsTriggersForUsers(new Set<String>{adminUser.Id},true,true);
        System.runAs(adminUser){

            //given
            Integer numOfLeads = 10;

            List<Lead> leads = new List<Lead>();
            Set<Id> leadIds = new Set<Id>();
            TestDataFactory.LeadBuilder leadBuilder = new TestDataFactory.LeadBuilder();
            for(Integer i = 0; i < numOfLeads; i++){
                Lead lead = (Lead)leadBuilder.getRecord();
                leads.add(lead);
                leadBuilder.build();
            }

            //when
            Test.startTest();
            insert leads;
            Test.stopTest();

            //then
            for(Lead lead : leads){
                leadIds.add(lead.Id);
            }
            List<Lead> insertedLeads = [
                    SELECT HadAddressonCreation__c, Address, Street
                    FROM Lead
                    WHERE Id IN :leadIds
            ];

            System.assertEquals(numOfLeads, insertedLeads.size());
            for(Integer i = 0; i<numOfLeads; i++){
                System.assertEquals(null, insertedLeads[i].Street);
                System.assertEquals(FALSE, insertedLeads[i].HadAddressOnCreation__c);
            }
        }
    }
}