force-app/main/default/objects/TaskSetting__mdt/TaskSetting__mdt.object-meta.xml
<CustomObject>
    <description>This will help in mapping Customer Request to Tasks And Tasks to Tasks</description>
    <label>Task Setting</label>
    <pluralLabel>Task Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TaskSetting__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <description>This field will be used for Naming the task subject</description>
    <label>Task Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/EventsHelper.cls
/**
 * Created by aneesh.bhat on 27-Oct-17.
 */

public class EventsHelper {
    public static Map<String, TaskSetting__mdt> taskSettingsMap = MetaDataSelector.getTaskSettingMetada();
    
    // Updates the subject on all the events
    public static void updateSubjectOnEvents(List<Event> events){
        for ( Event newEvent : events ) {
            UpdateSubjectOnEvent(newEvent);
        }
    }

    // Update the event subject to appropriate value
    public static void updateSubjectOnEvent(Event eventObj){
        if(taskSettingsMap !=null && taskSettingsMap.containsKey(eventObj.Type)){
            String eventSubject = taskSettingsMap.get(eventObj.Type).TaskSubject__c;
            eventSubject = eventSubject +' - '+ eventObj.Program__c;
            eventObj.Subject = String.isBlank(eventSubject)? eventObj.Type : eventSubject;
        }
    }
}