force-app/main/default/objects/Lead/fields/CreationMethod__c.field-meta.xml
<CustomField>
    <fullName>CreationMethod__c</fullName>
    <label>Creation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enteredbyuser</fullName>
                <label>Entered By User</label>
            </value>
            <value>
                <fullName>Excel Import</fullName>
            </value>
            <value>
                <fullName>Ef.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DeviceType__c.field-meta.xml
<CustomField>
    <fullName>DeviceType__c</fullName>
    <label>Device Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HadAddressonCreation__c.field-meta.xml
<CustomField>
    <fullName>HadAddressonCreation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If customer gave address when contact was created – Maybe on opportunity??</description>
    <label>Had Address on Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HearAboutUs__c.field-meta.xml
<CustomField>
    <fullName>HearAboutUs__c</fullName>
    <label>Hear About Us</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HearAboutUs</valueSetName>
    </valueSet>
</CustomField>

force-app++/main/default/objects/Lead/fields/IsDupe__c.field-meta.xml
<CustomField>
    <fullName>IsDupe__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once it is identified as Dupe, this flag will be set for further processing</description>
    <label>Is Dupe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsExpressCall__c.field-meta.xml
<CustomField>
    <fullName>IsExpressCall__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ExpressCall</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsParent__c.field-meta.xml
<CustomField>
    <fullName>IsParent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This comes from ef.com, when a Parent submits a request on behalf of their kids.</description>
    <inlineHelpText>Either this Lead is a parent or a request on ef.com was submitted by a parent</inlineHelpText>
    <label>Is Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ReadyForRanking__c.field-meta.xml
<CustomField>
    <fullName>ReadyForRanking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the dupe check process is completed, this flag will be set</description>
    <label>Ready For Ranking</label>
    <type>Checkbox</type>
</CustomField>

force-app++/main/default/objects/Lead/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>This field is used to determine which Event Type should be created.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SourceCodeAuto__c.field-meta.xml
<CustomField>
    <fullName>SourceCodeAuto__c</fullName>
    <label>Source Code Auto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/HearAboutUs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>Ex-Pax/Ex-ENQ</fullName>
    </customValue>
    <customValue>
        <fullName>I haven't asked</fullName>
    </customValue>
    <customValue>
        <fullName>Search Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement (offline/online)</fullName>
    </customValue>
    <customValue>
        <fullName>Customer doesn't know</fullName>
    </customValue>
    <customValue>
        <fullName>Fair/Exhibitions</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>At School</fullName>
    </customValue>
    <customValue>
        <fullName>EF distributions</fullName>
    </customValue>
    <description>How did you hear about us?</description>
    <masterLabel>HearAboutUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/RequestType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>CAM</fullName>
    </customValue>
    <customValue>
        <fullName>CBR</fullName>
    </customValue>
    <customValue>
        <fullName>CM</fullName>
    </customValue>
    <customValue>
        <fullName>CU</fullName>
    </customValue>
    <customValue>
        <fullName>IM</fullName>
    </customValue>
    <customValue>
        <fullName>PQ</fullName>
    </customValue>
    <customValue>
        <fullName>REQ</fullName>
    </customValue>
    <customValue>
        <fullName>RES</fullName>
    </customValue>
    <customValue>
        <fullName>IR</fullName>
    </customValue>
    <customValue>
        <fullName>WI</fullName>
        <isActive>false</isActive>
        <label>WI</label>
    </customValue>
    <customValue>
        <fullName>MCR</fullName>
        <isActive>false</isActive>
        <label>MCR</label>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
        <isActive>false</isActive>
        <label>EXC</label>
    </customValue>
    <customValue>
        <fullName>CNT</fullName>
        <isActive>false</isActive>
        <label>CNT</label>
    </customValue>
    <customValue>
        <fullName>WV</fullName>
        <isActive>false</isActive>
        <label>WV</label>
    </customValue>
    <customValue>
        <fullName>VST</fullName>
        <isActive>false</isActive>
        <label>VST</label>
    </customValue>
    <customValue>
        <fullName>TRV</fullName>
        <isActive>false</isActive>
        <label>TRV</label>
    </customValue>
    <customValue>
        <fullName>TRR</fullName>
        <isActive>false</isActive>
        <label>TRR</label>
    </customValue>
    <customValue>
        <fullName>TRM</fullName>
        <isActive>false</isActive>
        <label>TRM</label>
    </customValue>
    <customValue>
        <fullName>PST</fullName>
        <isActive>false</isActive>
        <label>PST</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <isActive>false</isActive>
        <label>TR</label>
    </customValue>
    <masterLabel>RequestType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/DCBusinessFlowHelper.cls
/**
 * Created by shravan.boddula on 9/6/2017.
 */

public class DCBusinessFlowHelper {
    //notify ranking
    public static void notifyForRanking(Lead sourceLead) {
        try {
            if (sourceLead.IsDupe__c == false) {
                sourceLead.ReadyForRanking__c = true;
            }
            List<Lead> sourceLeads = new List<Lead>();
            sourceLeads.Add(sourceLead);
           List<RankingServiceResponse> finalResponse = webServiceCallForRanking(sourceLeads);
          system.debug('Finalresponse@@@'+finalResponse);
          if(finalResponse[0].LeadID==sourceLead.id && finalResponse[0].IsRanked){
                sourceLead.ranking__c = finalResponse[0].Rank;
                system.debug('ranking>>>>'+sourceLead.ranking__c);
                //SObjectUnitOfWork.executeUpdateLeads(new List<Lead>{sourceLead});               

            }           
             update sourceLead; 
        } catch (Exception ex) {
            system.debug('Exception after notifying for ranking'+ex);
            ExceptionHandler.errorLog(ex.getMessage(),

                    ex.getStackTraceString(), 'DCBusinessFlowHelper', 'notifyForRanking', '');
        }
    }
    public static List<RankingServiceResponse> webServiceCallForRanking(List<Lead> sourceLeads){
    system.debug('sourceLead>>>>'+sourceLeads);
        //Make sure your Salesforce instance URL is added in remote site settings
        //String sfdcURL = URL.getSalesforceBaseUrl().toExternalForm();
       if (!Test.isRunningTest()) {
        String restAPIURL = label.End_Point_URL;
        List<RankingServiceParams> serviceParamsList = new List<RankingServiceParams>();
        RankingServiceParams serviceParams = null;          
        for(Lead sourceLead: sourceLeads){
            serviceParams = new RankingServiceParams();
            serviceParams.LeadID = sourcelead.id;
            serviceParams.OpportunityID = '';
            serviceParams.RankingType = 'Original';
            serviceParams.RequestType = sourcelead.requesttype__c;
            serviceParams.HasAddressonCreation = sourceLead.HadAddressonCreation__c;
            serviceParams.LastPQDateTime = sourcelead.requesttype__c=='PQ'?sourcelead.createddate:null;
            serviceParams.LastRESDateTime = sourcelead.requesttype__c=='RES'?sourcelead.createddate:null;
            serviceParams.IsParent = sourcelead.isparent__c;
            serviceParams.IsExpressCall = sourcelead.IsExpressCall__c;
            serviceParams.HasBooking = false;
            serviceParams.Program = sourceLead.Program__c;
            serviceParams.Market = sourceLead.market__c;
            serviceParams.CreatedDate = sourcelead.createddate;
            serviceParams.CreationMethod = sourceLead.CreationMethod__c;
            serviceParams.Source = sourceLead.SourceCodeAuto__c;
            serviceParams.Address = (sourceLead.street + ','+ sourceLead.region__c+ ',' + sourceLead.city +',' + sourceLead.country +',' + sourceLead.postalcode).replace('null', '');
            serviceParams.HearAboutUs = sourceLead.hearaboutus__c;
            serviceParams.DeviceType = sourceLead.DeviceType__c;        
            serviceParamsList.Add(serviceParams);
        }
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setHeader('Content-Type', 'application/json');
        system.debug('My Json body'+JSON.serialize(serviceParamsList));
        httpRequest.setBody(JSON.serialize(serviceParamsList));
        httpRequest.setEndpoint(restAPIURL + '?SalesForceApplicationId=' + serviceParams.LeadID);
        String response = '';       
            Http http = new Http();
            HttpResponse httpResponse = http.send(httpRequest);
            if (httpResponse.getStatusCode() == 200 ) {
                //response = JSON.serializePretty( JSON.deserializeUntyped(httpResponse.getBody()) );
                List<RankingServiceResponse> serviceResponse =
                        (List<RankingServiceResponse>)JSON.deserialize(httpResponse.getBody(),List<RankingServiceResponse>.class);
                System.debug(' ** response ** : ' + serviceResponse );             
                return serviceResponse;
            } else {
                System.debug(' httpResponse ' + httpResponse.getBody() );
                throw new CalloutException( httpResponse.getBody() );
            }   
}           
        return null;
   
    }
 
}