force-app/main/default/objects/Lead/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.TF_Default_Market__c</defaultValue>
    <description>Market to which Lead belongs</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/PreferredDuration__c.field-meta.xml
<CustomField>
    <fullName>PreferredDuration__c</fullName>
    <description>This is the preferred duration of customer which is stored from Lead/Opportunity screen.</description>
    <label>Preferred Duration</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Program__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1 week</fullName>
            </value>
            <value>
                <fullName>2 weeks</fullName>
            </value>
            <value>
                <fullName>3 weeks</fullName>
            </value>
            <value>
                <fullName>4 weeks</fullName>
            </value>
            <value>
                <fullName>5 Weeks</fullName>
            </value>
            <value>
                <fullName>6 Weeks</fullName>
                <label>6 weeks</label>
            </value>
            <value>
                <fullName>7 Weeks</fullName>
            </value>
            <value>
                <fullName>8 Weeks</fullName>
                <label>8 weeks</label>
            </value>
            <value>
                <fullName>9 Weeks</fullName>
            </value>
            <value>
                <fullName>10 Weeks</fullName>
            </value>
            <value>
                <fullName>11 Weeks</fullName>
            </value>
            <value>
                <fullName>12 Weeks</fullName>
            </value>
            <value>
                <fullName>>12 Weeks</fullName>
            </value>
            <value>
                <fullName>Semester</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Extended Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program to which Lead belongs</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/FieldUtilityClassTest.cls
@isTest
private class FieldUtilityClassTest{
     @testSetup static void setup(){
         FieldUtilityClass obj01 = new FieldUtilityClass();
        FieldUtilityClass.PicklistDetails obj11 = new FieldUtilityClass.PicklistDetails();
        obj11.active = 'test data';
        obj11.defaultValue = 'test data';
        obj11.label = 'test data';
        obj11.value = 'test data';
        obj11.validFor = 'test data'; 
     }
  static testMethod void testHasFieldAccess(){
    FieldUtilityClass.hasFieldAccess(new Lead(),'Program__c');
  }
  static testMethod void testGetPickListValues(){
    FieldUtilityClass.getPickListValues(Lead.getSObjectType(),'test data');
  }
  static testMethod void testgetDependentOptions(){
    FieldUtilityClass.getDependentOptions('Lead','Program__c','PreferredDuration__c');
  }
  static testMethod void testGetFieldDependencies(){
    FieldUtilityClass.getFieldDependencies('Lead','Market__c','Program__c');
  }
  static testMethod void testGetFieldDependenciesMap(){
    FieldUtilityClass.getFieldDependenciesMap('Lead','Market__c','Program__c');
  }
}