force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture the Source during the manual creation of the Lead</description>
    <label>Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Source__c.IsGlobal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Source__c.Market__c</field>
            <operation>equals</operation>
            <valueField>$Source.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>Source__c.AvailableforManualEntry__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture the Source during the manual creation of the Opportunity</description>
    <label>Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Source__c.IsGlobal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Source__c.Market__c</field>
            <operation>equals</operation>
            <valueField>$Source.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>Source__c.AvailableforManualEntry__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Source is the way we track information about how the customers came to EF</description>
    <label>Source</label>
    <nameField>
        <label>Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app++/main/default/objects/Source__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Displays the code of the Source</description>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Displays the name of the Code</description>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SourcesSelector.cls
/**
 * Created by thejasvi.a on 2/21/2018.
 */

public with sharing class SourcesSelector {
    public static List<Source__c> getSourceRecords(Set<string> sourceAutoCodeValues){
        List<Source__c> sourceList = new List<Source__c>();
        if(sourceAutoCodeValues!=null) {
            sourceList=[select Id, Code__c,Name from Source__c where Code__c in:sourceAutoCodeValues];
        }
        return sourceList;
    }

    public static Map<Id,Source__c>  getSourceMapRecordforLead (Map<Id,List<Lead>> leadMap) {
        Map<Id, Source__c> sourceMap = new Map<Id, Source__c>();
        if (leadMap != null) {
            sourceMap = new Map<Id, Source__c>([select Id, Name, Code__c from Source__c where Id in :leadMap.keySet()]);
        }
        return sourceMap;
    }

    public static Map<Id,Source__c>  getSourceMapRecordforOpportunity (Map<Id,List<Opportunity>> opportunityMap) { 
        Map<Id, Source__c> sourceMap = new Map<Id, Source__c>();
        if (opportunityMap != null) {
            sourceMap = new Map<Id, Source__c>([select Id, Name, Code__c from Source__c where Id in :opportunityMap.keySet()]);
        }
        return sourceMap;
    }

}