force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APTS_AY_Course_Type__c.field-meta.xml
<CustomField>
    <fullName>APTS_AY_Course_Type__c</fullName>
    <formula>TEXT(Apttus_Config2__ProductId__r.APTS_AY_Course_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AY Course Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APTS_EnableStartDateEndDate__c.field-meta.xml
<CustomField>
    <fullName>APTS_EnableStartDateEndDate__c</fullName>
    <description>This Field  Will capture weather product has start date and end date enabled</description>
    <formula>IF ( TEXT( Apttus_Config2__LineType__c ) = "Product/Service", Apttus_Config2__ProductId__r.EnableStartDateEndDate__c, Apttus_Config2__OptionId__r.EnableStartDateEndDate__c)</formula>
    <label>Enable Start Date &amp; End Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APTS_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>APTS_Product_Type__c</fullName>
    <description>This field will have Product Type populated from the product which is selected on line item.</description>
    <label>Product Type</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APTS_QunatityModifiable__c.field-meta.xml
<CustomField>
    <fullName>APTS_QunatityModifiable__c</fullName>
    <description>we use this field for start date VF page to check weather user can modify quantity or not</description>
    <formula>IF ( TEXT( Apttus_Config2__LineType__c ) = "Product/Service", Apttus_Config2__ProductId__r.QunatityModifiable__c, Apttus_Config2__OptionId__r.QunatityModifiable__c)</formula>
    <label>Qunatity Modifiable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__EndDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__EndDate__c</fullName>
    <description>The end date for products and services</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__PricingStatus__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PricingStatus__c</fullName>
    <description>The pricing status</description>
    <label>Pricing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__StartDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__StartDate__c</fullName>
    <description>The start date for products and services</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Beginner__c.field-meta.xml
<CustomField>
    <fullName>Beginner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will indicate weather the student is beginner or not(We added this field in line item so that we can select the field in new custom page)</description>
    <label>Beginner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/DestinationCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationCode__c</fullName>
    <description>This field is used for Price Dimension "Destination Code" that drives pricing for some products that have Price Matrices with Dimension "Destination Code". 
Note: Values of Product Codes for Destination Bundles = Destination Code</description>
    <formula>Apttus_Config2__ProductId__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>This field fetches the market value from the Quote/Proposal</description>
    <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <formula>Apttus_Config2__OptionId__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Product_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Product_Subtype__c</fullName>
    <label>Product Subtype</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>This field fetches the PROGRAM picklist value from the quote</description>
    <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Program__c)</formula>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Start_Dates__c/Start_Dates__c.object-meta.xml
<CustomObject>
    <description>This Object is Mainly used for integration of start date project to salesforce as we need start date for course start date in apttus</description>
    <label>Start Dates</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StartDates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start_Dates__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>we need to make sure that start dates are saved based on program (CAT has confirmed that they have this info).</description>
    <label>Program</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/StartDateSettings__mdt.object-meta.xml
<CustomObject>
    <description>In this setting we will store all the off set rules for different markets for different cases</description>
    <label>Start Date Settings</label>
    <pluralLabel>StartDateSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/StartDateSettings__mdt/fields/DestinationCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationCode__c</fullName>
    <description>Destination code will be stored in this field</description>
    <label>Destination Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>This field is used o specify the program for which the settings is used for</description>
    <label>Program</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DatesQuantityConfiguratorController.cls
/**
 * Created by Arkadiusz Celej on 31.01.2018.
 * @description Controller class for DatesQuantityConfigurator And DatesQuantityConfigurator related Lightning Components
 */

public class DatesQuantityConfiguratorController {
    public Id cartId {get;set;}
    public String backCartUrl{ get; set; }
    public DatesQuantityConfiguratorController(){
        this.cartId = ApexPages.CurrentPage().getparameters().get('id');
        String configId2 = ApexPages.currentPage().getParameters().get('id');
        String configRequestId = ApexPages.currentPage().getParameters().get('configRequestId');
        String cartStatus = ApexPages.currentPage().getParameters().get('cartStatus');
        String cartFlow = ApexPages.currentPage().getParameters().get('flow');
        backCartUrl = Site.getPathPrefix() + '/apex/Apttus_Config2__Cart?id=' + configId2 + '&configRequestId=' + configRequestId;
        if(cartStatus != NULL){
            backCartUrl = backCartUrl +'&cartStatus=' + cartStatus;
        }
        if(cartFlow != NULL){
            backCartUrl = backCartUrl + '&flow=' +cartFlow;
        }
    }

    @AuraEnabled
    public static Map<Decimal, List<Apttus_Config2__LineItem__c>> getCartLineItems(Id cartId){
        try {
            String query = 'SELECT ';
            for (Schema.FieldSetMember f : SObjectType.Apttus_Config2__LineItem__c.FieldSets.EditStartEndDateFieldSet.getFields()) {
                query += f.getFieldPath() + ', ';
            }

            query += 'Id, Product_Subtype__c, Name, Beginner__c, Apttus_Config2__ProductId__r.Name, Apttus_Config2__LineType__c, APTS_EnableStartDateEndDate__c, Program__c, ';
            query += 'Apttus_Config2__Uom__c, Apttus_Config2__EndDate__c, APTS_QunatityModifiable__c, Apttus_Config2__StartDate__c, Apttus_Config2__Quantity__c, ';
            query += 'DestinationCode__c, Apttus_Config2__ProductId__r.APTS_Destination_Location__c, Apttus_Config2__OptionId__r.APTS_AY_Course_Type__c,Apttus_Config2__OptionId__r.Available_Programs__c,Apttus_Config2__LineNumber__c, Apttus_Config2__OptionId__c, ';
            query += 'Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Market__c ';
            query += 'from Apttus_Config2__LineItem__c ';
            query += 'where Apttus_Config2__ConfigurationId__c = :cartId ' ;
            query += ' and APTS_EnableStartDateEndDate__c = TRUE ORDER BY Apttus_Config2__LineNumber__c, APTTUS_CONFIG2__ITEMSEQUENCE__C' ;

            List<Apttus_Config2__LineItem__c> lineItems = Database.query(query);
            return mapLineItems(lineItems);
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void saveLineItems(String cartId, List<Apttus_Config2__LineItem__c> lineItems){
        try {
            updateItemsBeforeSave(lineItems);
            update lineItems;
            resetSeasonSuplements(cartId, mapLineItems(lineItems));
        }catch (Exception ex){
            throw new AuraException(ex.getMessage());
        }
    }

    private static void updateItemsBeforeSave(List<Apttus_Config2__LineItem__c> lineItems){
        for(Apttus_Config2__LineItem__c item : lineItems){
            item.Apttus_Config2__PricingStatus__c = 'Pending';
        }
    }

    private static void resetSeasonSuplements(String cartId, Map<Decimal, List<Apttus_Config2__LineItem__c>> itemsByLineNumber){
        for(Decimal lineNumber: itemsByLineNumber.keySet()){
            for(Apttus_Config2__LineItem__c lineItem : itemsByLineNumber.get(lineNumber)) {
                if (lineItem.APTS_Product_Type__c == 'Course') {
                    SeasonSupplementsHelper.createOptionLineItem(cartId, lineItem, itemsByLineNumber);
                }
            }
        }
    }

    @AuraEnabled
    public static Integer repriceCart(String cartId){
        Apttus_CpqApi.CPQ.UpdatePriceRequestDO priceRequestDO = new Apttus_CpqApi.CPQ.UpdatePriceRequestDO();
        priceRequestDO.cartId = cartId;
        Apttus_CpqApi.CPQ.UpdatePriceResponseDO result = Apttus_CpqApi.CPQWebService.updatePriceForCart(priceRequestDO);
        return result.PendingLineNumbers.size();
    }

    @AuraEnabled
    public static List<Start_Dates__c> getAvailableStartDates(Apttus_Config2__LineItem__c item) {
        System.debug('ITEM '+item);
        Boolean isAdmin = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId()].Name == 'System Administrator';
        return StartDateHelper.getAvailableStartDates(item.Product_Code__c, item.DestinationCode__c, item.Beginner__c, isAdmin, item.Program__c);
    }

    @AuraEnabled
    public static List<StartDateSettings__mdt> getAvailableStartDateSettings(Apttus_Config2__LineItem__c item) {
        return StartDatesSelector.getStartDateSettings(item.DestinationCode__c,item.Program__c);
    }

    private static Map<Decimal, List<Apttus_Config2__LineItem__c>> mapLineItems(List<Apttus_Config2__LineItem__c> lineItems){
        Map<Decimal, List<Apttus_Config2__LineItem__c>> mappedItems = new Map<Decimal, List<Apttus_Config2__LineItem__c>>();
        for(Apttus_Config2__LineItem__c lineItem : lineItems){
            if(!mappedItems.containsKey(lineItem.Apttus_Config2__LineNumber__c)){
                mappedItems.put(lineItem.Apttus_Config2__LineNumber__c, new List<Apttus_Config2__LineItem__c>());
            }
            mappedItems.get(lineItem.Apttus_Config2__LineNumber__c).add(lineItem);
        }
        return mappedItems;
    }

    public class AuraException extends Exception{}
}