force-app/main/default/objects/ProfileNamesForAdminAccess__mdt/ProfileNamesForAdminAccess__mdt.object-meta.xml
<CustomObject>
    <description>This is used to Update the profile Name which has access to access all the Information in SalesForce</description>
    <label>ProfileNamesForAdminAccess</label>
    <pluralLabel>Profilenames</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProfileNamesForAdminAccess__mdt/fields/Profiles__c.field-meta.xml
<CustomField>
    <fullName>Profiles__c</fullName>
    <description>All the Profiles Which has access will be stored in this Meta data</description>
    <label>Profiles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProfileNamesForAdminAccess__mdt/fields/SObjectname__c.field-meta.xml
<CustomField>
    <fullName>SObjectname__c</fullName>
    <description>S Object Api name will be captured Here</description>
    <label>SObjectname</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Start_Dates__c/Start_Dates__c.object-meta.xml
<CustomObject>
    <description>This Object is Mainly used for integration of start date project to salesforce as we need start date for course start date in apttus</description>
    <label>Start Dates</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StartDates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start_Dates__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>we need to make sure that start dates are saved based on program (CAT has confirmed that they have this info).</description>
    <label>Program</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/StartDateSettings__mdt.object-meta.xml
<CustomObject>
    <description>In this setting we will store all the off set rules for different markets for different cases</description>
    <label>Start Date Settings</label>
    <pluralLabel>StartDateSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/StartDateSettings__mdt/fields/DestinationCode__c.field-meta.xml
<CustomField>
    <fullName>DestinationCode__c</fullName>
    <description>Destination code will be stored in this field</description>
    <label>Destination Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/EndDateOffSet__c.field-meta.xml
<CustomField>
    <fullName>EndDateOffSet__c</fullName>
    <description>End Date off set for product</description>
    <label>EndDate Off-Set</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <description>All the product Code will be stored in this field</description>
    <label>Product Code</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/ProductSubType__c.field-meta.xml
<CustomField>
    <fullName>ProductSubType__c</fullName>
    <description>All the product sub types which follows start date rules will be stored in comma seperated string</description>
    <label>Product Sub Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>All the product Types will be stored in this field</description>
    <label>Product Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>This field is used o specify the program for which the settings is used for</description>
    <label>Program</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/StartDateOffSet__c.field-meta.xml
<CustomField>
    <fullName>StartDateOffSet__c</fullName>
    <description>Start Date off set for product</description>
    <label>StartDate Off-Set</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StartDateSettings__mdt/fields/ValidAccommodationDays__c.field-meta.xml
<CustomField>
    <fullName>ValidAccommodationDays__c</fullName>
    <description>This Field is used to Specify Valid Accommodation days
Ex:FRIDAY,SATURDAY,SUNDAY</description>
    <label>Valid Accommodation Days</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StartDatesSelector.cls
/**************************************************************************************
Apex Class Name    : StartDatesSelector
Version            : 1.0
Created Date       : September 22 2017
Function           :
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Arjun.Mohan                 09/22/2017              Original Version
*******************************************************************************/

public class StartDatesSelector {

    Public static List<Start_Dates__c> getStartDatesForSelectedBundle(String query) {
        List<Start_Dates__c> startdateList = Database.query(query);
        system.debug('Startdate count is' + startdateList);
        return startdateList;
    }

    Public static List<ProfileNamesForAdminAccess__mdt> getProfilesForAdminAccess(String sObjectname) {
        return [Select Id,Profiles__c,SObjectname__c from ProfileNamesForAdminAccess__mdt where SObjectname__c = :sObjectname];
    }

    Public static List<StartDateSettings__mdt> getStartDateSettings(String destinationCode, string program) {

        List<StartDateSettings__mdt> startDateSettingsList = new List<StartDateSettings__mdt>();
        List<StartDateSettings__mdt> actualstartDateSettingsList = new List<StartDateSettings__mdt>();
        System.debug('Destination Code ' + destinationCode + ' program ' + program);
        startDateSettingsList = [
                Select Id, DestinationCode__c, Program__c,EndDateOffSet__c, ProductCode__c, ProductSubType__c, ProductType__c, StartDateOffSet__c, ValidAccommodationDays__c
                from StartDateSettings__mdt
                where DestinationCode__c = :destinationCode
        ];

        if (startDateSettingsList.size() == 0) {
            startDateSettingsList = [
                    Select Id, DestinationCode__c,Program__c, EndDateOffSet__c, ProductCode__c, ProductSubType__c, ProductType__c, StartDateOffSet__c, ValidAccommodationDays__c
                    from StartDateSettings__mdt
                    where DestinationCode__c = 'ALL'
            ];
        }
        for (StartDateSettings__mdt settingRecord : startDateSettingsList) {
            String[] ProgramsList = settingRecord.Program__c.split(';');
            for (String programrecord : ProgramsList) {
                string rec = program.toUpperCase().trim();
                if (rec.equals(program.toUpperCase().trim())) {
                    actualstartDateSettingsList.add(settingRecord);
                    break;
                }
            }
            if (actualstartDateSettingsList.size() > 0) {
                break;
            }
        }
        system.debug('Selected Start dates settings are ' + startDateSettingsList);
        return actualstartDateSettingsList;

    }
}