force-app/main/default/objects/APXTConga4__Conga_Template__c/APXTConga4__Conga_Template__c.object-meta.xml
<CustomObject>
    <description>Template manager for use with Conga Composer and Conga Mail Merge.</description>
    <label>Conga Template</label>
    <nameField>
        <displayFormat>CMT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/APXTConga4__Template_Group__c.field-meta.xml
<CustomField>
    <fullName>APXTConga4__Template_Group__c</fullName>
    <inlineHelpText>Identify the group name to which this template belongs. Used in conjunction with the "&amp;TemplateGroup=" parameter in PointMerge.</inlineHelpText>
    <label>Template Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/APXTConga4__Template_Type__c.field-meta.xml
<CustomField>
    <fullName>APXTConga4__Template_Type__c</fullName>
    <label>Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Envelope</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Letter</fullName>
                <default>true</default>
                <label>Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market to which Lead belongs.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The user shall select the program for which he would like to add a setting.</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/APXTConga4__Conga_Template__c/fields/RecordSharingKey__c.field-meta.xml
<CustomField>
    <fullName>RecordSharingKey__c</fullName>
    <description>text key for sharing records with users thru public groups</description>
    <formula>TEXT(Market__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Sharing Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILSU</fullName>
    </customValue>
    <customValue>
        <fullName>ILSH</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>AY</fullName>
    </customValue>
    <customValue>
        <fullName>AYP</fullName>
    </customValue>
    <customValue>
        <fullName>MLY</fullName>
    </customValue>
    <customValue>
        <fullName>ILSP</fullName>
    </customValue>
    <customValue>
        <fullName>MULTI</fullName>
    </customValue>
    <customValue>
        <fullName>PRW</fullName>
    </customValue>
    <customValue>
        <fullName>EXC</fullName>
    </customValue>
    <customValue>
        <fullName>MLYP</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>HUG</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <masterLabel>Programs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CongaTemplateTriggerTest.cls
@isTest
public class CongaTemplateTriggerTest {
private static TestDataFactory.DefaultPicklistValuesHelper picklistValuesHelper = new TestDataFactory.DefaultPicklistValuesHelper();
        Public static ID recordId;
        Public static ID userOrGroupId; 
        Public static String accessLevel;
    
    @testSetup
    static void testDataSetup(){
        Profile SystemAdminProfile = TestDataFactory.getProfile('System Administrator', true);
        User tAdminUser = TestDataFactory.createAdminUser(True);
         Group	group1	=	new Group(name = 'NOO',type	=	'Regular');
        	insert group1;
        Group group2 = new Group(name = 'CNB', Type='Regular');
        	insert group2;
        
        
        APXTConga4__Conga_Template__c Conga = new APXTConga4__Conga_Template__c();
        Conga.Market__c = 'NOO';
        Conga.Program__c = 'ILS';
        Conga.Language__c = 'NO';
       
        insert Conga;
    
	}
    
    static testMethod void WhenCreateShareOnInsert(){
      Test.startTest();
        Map<Id, String> templateMap = new Map<Id, String>();
        Map<String, Id> publicGroupMap = publicGroupsSelector.getRegularPublicGroupsByName(templateMap.values());        
        List<APXTConga4__Conga_Template__share> templateShareList = new List<APXTConga4__Conga_Template__share>();
        
        List<APXTConga4__Conga_Template__c> templateList1 = [SELECT ID,APXTConga4__Template_Type__c,APXTConga4__Template_Group__c,
                                                                     APXTConga4__Template_Extension__c,APXTConga4__Name__c,
                                                                     APXTConga4__Master_Field_to_Set_3__c,Market__c,
                                                                     APXTConga4__Master_Field_to_Set_2__c,Program__c,
                                                                     APXTConga4__Master_Field_to_Set_1__c,
                                                                     Language__c,CurrencyIsoCode, RecordSharingKey__c,OwnerId
                                                            FROM APXTConga4__Conga_Template__c];
      
       
        List<APXTConga4__Conga_Template__c> templateList2 = [SELECT ID,APXTConga4__Template_Type__c,APXTConga4__Template_Group__c,
                                                                     APXTConga4__Template_Extension__c,APXTConga4__Name__c,
                                                                     APXTConga4__Master_Field_to_Set_3__c,Market__c,
                                                                     APXTConga4__Master_Field_to_Set_2__c,Program__c,
                                                                     APXTConga4__Master_Field_to_Set_1__c,
                                                                     Language__c,CurrencyIsoCode, RecordSharingKey__c,OwnerId	
                                                              FROM APXTConga4__Conga_Template__c];
        templateList2[0].Market__c = 'CNB';
        templateList2[0].Language__c = 'ZH';
        templateList2[0].Program__c = 'ILS';
        update templateList2[0];
        
        Map<Id,String> temMap = new Map<Id,String>();
            for(APXTConga4__Conga_Template__c ct : templateList1){
                temMap.put(ct.id, 'test');
            }
        
        CongaTemplateHelper.createShareOnInsert(templateList1);
        CongaTemplateHelper.createShareRecord(recordId, userOrGroupId, accessLevel);
        CongaTemplateHelper.createTemplateShareRec(temMap, publicGroupMap);
        CongaTemplateHelper.createShareOnUpdateTypes(templateList2, templateList1);
        system.assertEquals(1, templateList1.size());
      Test.stopTest();  
        
    }
   

}