force-app/main/default/objects/AccountContactRelation/fields/AccountContactID__c.field-meta.xml
<CustomField>
    <fullName>AccountContactID__c</fullName>
    <description>This field is used to store the Account ID of the Contact in the relation. This is used for integration with Poseidon.</description>
    <formula>Contact.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Contact Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/TotalBooking__c.field-meta.xml
<CustomField>
    <fullName>TotalBooking__c</fullName>
    <description>Used for Sending Family Details to Poseidon only if the related Account has Booking</description>
    <formula>Account.TotalBooking__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalBooking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountContactRelationsSelector.cls
/**
 * Created by arjun.mohan on 2/12/2018.
 */

public  class AccountContactRelationsSelector {

    public Static Map<Id,AccountContactRelation> getAccountContactRelationForAccountId(List<Id> AccountIdList)
    {
        Map<Id,AccountContactRelation> accountContactRelationMap=new Map<Id,AccountContactRelation>();
        List<AccountContactRelation> accountContactRelationList=new List<AccountContactRelation>();
        accountContactRelationList=[Select Id,AccountId,ContactId,Roles,AccountContactId__c,CreatedById,LastModifiedById,TotalBooking__c,CreatedDate,LastModifiedDate from AccountContactRelation Where AccountId in : AccountIdList];
        for (AccountContactRelation accountContactRecord:accountContactRelationList) {
            accountContactRelationMap.put(accountContactRecord.Id,accountContactRecord);
        }
        return accountContactRelationMap;
    }

}